/**
 * The codegen pipeline (Phase 1 §1.3), both stages:
 *   src schemas ──z.toJSONSchema──► schemas/*.schema.json ──cargo-typify──► rust/src/gen/*.rs
 *
 * `pnpm gen`        — regenerate in place (output is COMMITTED)
 * `pnpm gen:check`  — regenerate into a temp dir and diff; nonzero exit on
 *                     drift. This is the CI freshness gate.
 *
 * Tooling per the reconciled plan: zod v4 native toJSONSchema (no
 * zod-to-json-schema shim) and cargo-typify (pinned; see contracts/README) —
 * builds never need typify, only regeneration does, because output is
 * committed. Hand-written Rust wrappers (rust/src/{heartbeat,device_record}.rs)
 * re-export the generated types and add behavior (LWT helper, v40 mapping).
 */
import { execFileSync } from 'node:child_process'
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import { z } from 'zod'

import { DeviceRecordSchema } from '../src/device-record.js'
import { AgentHeartbeatSchema } from '../src/heartbeat.js'

const CONTRACTS_DIR = join(dirname(fileURLToPath(import.meta.url)), '..')

/** Every schema that crosses the TS→Rust boundary registers here. */
const REGISTRY: Record<string, z.ZodType> = {
  AgentHeartbeat: AgentHeartbeatSchema,
  DeviceRecord: DeviceRecordSchema,
}

const check = process.argv.includes('--check')

/**
 * Post-processing per the plan's typify config rules (Phase 1 §1.3):
 * - `additionalProperties: false` is stripped everywhere — tolerant reader is
 *   POLICY (§2.1); strict writing is zod's job at the write site, and typify
 *   must not emit `deny_unknown_fields`.
 * - for the typify INPUT only, string `format`s are dropped so datetimes stay
 *   plain `String` in Rust (no chrono — the crate rule is serde+serde_json
 *   only). The committed schema keeps formats for other consumers; the Rust
 *   side gets the structural subset and the vectors carry the load.
 */
function scrub(node: unknown, dropFormats: boolean): void {
  if (Array.isArray(node)) {
    for (const n of node) scrub(n, dropFormats)
    return
  }
  if (node && typeof node === 'object') {
    const o = node as Record<string, unknown>
    if (o['additionalProperties'] === false) delete o['additionalProperties']
    if (dropFormats && typeof o['format'] === 'string') delete o['format']
    for (const v of Object.values(o)) scrub(v, dropFormats)
  }
}

function jsonSchemaDocFor(name: string, schema: z.ZodType): Record<string, unknown> {
  const js = z.toJSONSchema(schema, { target: 'draft-2020-12', io: 'output' })
  const doc = {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: `https://open-air.contracts/${name}.schema.json`,
    title: name,
    $comment: 'GENERATED by contracts/scripts/gen.ts — DO NOT EDIT. Source: contracts/src.',
    ...js,
  }
  scrub(doc, false)
  return doc
}

function rustFor(name: string, doc: Record<string, unknown>, outPath: string): string {
  const typifyInput = structuredClone(doc)
  scrub(typifyInput, true) // drop formats: datetimes stay String, no chrono
  const inputPath = join(mkdtempSync(join(tmpdir(), 'typify-in-')), `${name}.schema.json`)
  writeFileSync(inputPath, JSON.stringify(typifyInput, null, 2))
  try {
    execFileSync('cargo', ['typify', inputPath, '--no-builder', '-d', 'PartialEq', '-o', outPath], {
      encoding: 'utf8',
    })
  } finally {
    rmSync(dirname(inputPath), { recursive: true, force: true })
  }
  const generated = readFileSync(outPath, 'utf8')
  const header = `// GENERATED by contracts/scripts/gen.ts via cargo-typify — DO NOT EDIT.\n// Source schema: contracts/schemas/${name}.schema.json (formats stripped for typify — structural subset)\n`
  const withHeader = header + generated
  writeFileSync(outPath, withHeader)
  return withHeader
}

function generate(intoDir: string): Record<string, string> {
  const files: Record<string, string> = {}
  const schemasDir = join(intoDir, 'schemas')
  const genDir = join(intoDir, 'rust', 'src', 'gen')
  mkdirSync(schemasDir, { recursive: true })
  mkdirSync(genDir, { recursive: true })

  const modNames: string[] = []
  for (const [name, schema] of Object.entries(REGISTRY)) {
    const doc = jsonSchemaDocFor(name, schema)
    const json = JSON.stringify(doc, null, 2) + '\n'
    writeFileSync(join(schemasDir, `${name}.schema.json`), json)
    files[`schemas/${name}.schema.json`] = json

    const snake = name.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toLowerCase()
    files[`rust/src/gen/${snake}.rs`] = rustFor(name, doc, join(genDir, `${snake}.rs`))
    modNames.push(snake)
  }

  const mod =
    '// GENERATED by contracts/scripts/gen.ts — DO NOT EDIT.\n' +
    modNames.map((m) => `pub mod ${m};`).join('\n') +
    '\n'
  writeFileSync(join(genDir, 'mod.rs'), mod)
  files['rust/src/gen/mod.rs'] = mod
  return files
}

if (check) {
  const tmp = mkdtempSync(join(tmpdir(), 'contracts-gen-'))
  try {
    const fresh = generate(tmp)
    const stale: string[] = []
    for (const [rel, content] of Object.entries(fresh)) {
      let current = ''
      try {
        current = readFileSync(join(CONTRACTS_DIR, rel), 'utf8')
      } catch {
        /* missing counts as stale */
      }
      if (current !== content) stale.push(rel)
    }
    if (stale.length) {
      console.error(`gen:check FAILED — stale generated output (run \`pnpm gen\`):\n  ${stale.join('\n  ')}`)
      process.exit(1)
    }
    console.log(`gen:check OK — ${Object.keys(fresh).length} generated files fresh`)
  } finally {
    rmSync(tmp, { recursive: true, force: true })
  }
} else {
  const files = generate(CONTRACTS_DIR)
  console.log(`gen: wrote ${Object.keys(files).length} files`)
}
