# ==========================================
# Header: migrateRust-refactor.py
# Purpose: migrateRust-refactor.py implementation.
# Description: Logic and implementation for migrateRust-refactor.py implementation.
# 
# Version: 26.07.05.1
# Change Log:
# - 2026-07-05: Initial annotation and documentation added.
# ==========================================

import os
import re

# The mapping of old module names to the new snake_case submodules in oaRustCore
# This matches the names generated by your previous migration script.
IMPORT_MAP = {
    "oaAudioMixer_rs": "oa_audio_mixer",
    "oaConfigEngine_rs": "oa_config_engine",
    "oaAsyncSink_rs": "oa_async_sink",
    "oaLoggingGate_rs": "oa_logging_gate",
    "oaSafetyCore_rs": "oa_safety_core",
    "oaHeartbeatCore_rs": "oa_heartbeat_core",
    "oaThreadPool_rs": "oa_thread_pool",
    "oaClockSync_rs": "oa_clock_sync",
    "oaCoreRouter_rs": "oa_core_router",
    "oaAES70Core_rs": "oa_aes70_core",
    "oaEmberTree_rs": "oa_ember_tree",
    "oaMidiMapper_rs": "oa_midi_mapper",
    "oaMidiEngine_rs": "oa_midi_engine",
    "oaMQTTManager_rs": "oa_mqtt_manager",
    "oaOSCCore_rs": "oa_osc_core",
    "oaFastAPI_rs": "oa_fast_api",
    "oaST2138Codec_rs": "oa_st2138_codec",
    "oaMIBCache_rs": "oa_mib_cache",
    "oaSNMPAgent_rs": "oa_snmp_agent",
    "oaVisaCore_rs": "oa_visa_core",
    "oaVisaFormat_rs": "oa_visa_format",
    "oaVisaScanner_rs": "oa_visa_scanner",
    "oaPTPClock_rs": "oa_ptp_clock",
    "oaPtpParser_rs": "oa_ptp_parser",
    "oaFastDir_rs": "oa_fast_dir",
    "oaLayoutEngine_rs": "oa_layout_engine",
    "oaPatternEngine_rs": "oa_pattern_engine",
    "oaGeometryMath_rs": "oa_geometry_math",
    "oaEditorState_rs": "oa_editor_state",
    "oaHitboxMath_rs": "oa_hitbox_math",
    "oaMeteringEngine_rs": "oa_metering_engine",
    "oaCMDPMath_rs": "oa_cmdp_math",
    "oaNeedleEngine_rs": "oa_needle_engine",
    "oaNeedleGeometry_rs": "oa_needle_geometry",
    "oaProceduralArt_rs": "oa_procedural_art",
    "oaRotaryCore_rs": "oa_rotary_core",
    "oaFastScanner_rs": "oa_fast_scanner",
    "oaBlueprintParser_rs": "oa_blueprint_parser",
    "oaImageScaler_rs": "oa_image_scaler",
    "oaTimeSeriesDB_rs": "oa_time_series_db",
    "oaCSSParser_rs": "oa_css_parser",
    "oaCSVWriter_rs": "oa_csv_writer",
    "oaCSVParser_rs": "oa_csv_parser",
    "oaHTMLScraper_rs": "oa_html_scraper",
    "oaPDFParser_rs": "oa_pdf_parser",
    "oaShowfileUnpacker_rs": "oa_showfile_unpacker",
    "oaSplinkRegistry_rs": "oa_splink_registry",
    "oaSplinkCore_rs": "oa_splink_core",
    "oaDiskFlusher_rs": "oa_disk_flusher",
    "oaTaskPool_rs": "oa_task_pool",
    "oaTranslatorCore_rs": "oa_translator_core",
    "oaTrie_rs": "oa_trie",
    "oaStateDiffer_rs": "oa_state_differ",
    "oaStateRegistry_rs": "oa_state_registry",
    "oaMarkdownCompiler_rs": "oa_markdown_compiler",
    "oaLogAligner_rs": "oa_log_aligner",
    "oaDebugToggler_rs": "oa_debug_toggler",
    "oaLogProcessor_rs": "oa_log_processor",
    "oaManifestGen_rs": "oa_manifest_gen"
}

# Inline comment: Logic for refactor_python_imports
def refactor_python_imports(root_dir):
    print(f"Starting project-wide import refactor in: {root_dir}")

    # Pre-compile regex patterns for performance
    # This matches 'import oaName_rs' or 'from oaName_rs import ...'
    patterns = {}
    for old, new in IMPORT_MAP.items():
        patterns[old] = (
            re.compile(rf"\bimport {old}\b"),
            re.compile(rf"\bfrom {old} import\b")
        )

    for root, dirs, files in os.walk(root_dir):
        # Skip the new Rust core directory to avoid circular confusion
        if "oaRustCore" in root:
            continue

        for file in files:
            if file.endswith(".py"):
                file_path = os.path.join(root, file)

                with open(file_path, encoding='utf-8') as f:
                    content = f.read()

                original_content = content
                for old, (imp_pattern, from_pattern) in patterns.items():
                    new_module = IMPORT_MAP[old]

                    # Replace 'import oaName_rs' -> 'from oaRustCore import oa_name_rs as oaName_rs'
                    # We use 'as' to keep your existing variable names working!
                    content = imp_pattern.sub(f"from oaRustCore import {new_module} as {old}", content)

                    # Replace 'from oaName_rs import X' -> 'from oaRustCore.oa_name_rs import X'
                    content = from_pattern.sub(f"from oaRustCore.{new_module} import", content)

                if content != original_content:
                    with open(file_path, 'w', encoding='utf-8') as f:
                        f.write(content)
                    print(f"Refactored: {file_path}")

    print("\nRefactor Complete. All Python files now point to oaRustCore.")

if __name__ == "__main__":
    # Run from the OPEN-AIR root
    refactor_python_imports(".")
