var namespaceaes70_1_1types_1_1ocamediaconnectorstatuschangedeventdata =
[
    [ "IOcaMediaConnectorStatusChangedEventData", "d3/d4a/classaes70_1_1types_1_1ocamediaconnectorstatuschangedeventdata_1_1IOcaMediaConnectorStatusChangedEventData.html", "d3/d4a/classaes70_1_1types_1_1ocamediaconnectorstatuschangedeventdata_1_1IOcaMediaConnectorStatusChangedEventData" ],
    [ "OcaMediaConnectorStatusChangedEventData", "dd/d11/classaes70_1_1types_1_1ocamediaconnectorstatuschangedeventdata_1_1OcaMediaConnectorStatusChangedEventData.html", "dd/d11/classaes70_1_1types_1_1ocamediaconnectorstatuschangedeventdata_1_1OcaMediaConnectorStatusChangedEventData" ]
];