import re

with open('FrontEnd/libControl/graphing/Equalization/Equalization.jsx', 'r') as f:
    code = f.read()

old_c_header = """                            // Format coefficients as C Header for DSP
                            let cHeader = `// DSP FIR Filter Coefficients\\n`;
                            cHeader += `// Generated by OpenAir Equalizer\\n\\n`;
                            cHeader += `#ifndef EQ_FILTER_H\\n`;
                            cHeader += `#define EQ_FILTER_H\\n\\n`;
                            cHeader += `#include <stdint.h>\\n\\n`;
                            cHeader += `#define FIR_TAPS ${N}\\n`;
                            cHeader += `#define FIR_SYMMETRIC 1\\n\\n`;
                            
                            cHeader += `// 32-bit Floating Point Coefficients\\n`;
                            cHeader += `// Aligned to 32-byte boundary for SIMD processing\\n`;
                            cHeader += `__attribute__((aligned(32)))\\n`;
                            cHeader += `const float fir_taps_f32[FIR_TAPS] = {\\n    `;
                            
                            for (let i = 0; i < ir.length; i++) {
                                cHeader += ir[i].toExponential(8) + "f";
                                if (i < ir.length - 1) cHeader += ", ";
                                if ((i + 1) % 4 === 0) cHeader += "\\n    ";
                            }
                            cHeader += `\\n};\\n\\n`;
                            
                            cHeader += `// 32-bit Fixed Point Coefficients (Q31 format)\\n`;
                            cHeader += `// Aligned to 32-byte boundary for SIMD processing\\n`;
                            cHeader += `__attribute__((aligned(32)))\\n`;
                            cHeader += `const int32_t fir_taps_q31[FIR_TAPS] = {\\n    `;
                            
                            for (let i = 0; i < ir.length; i++) {
                                let q31 = Math.round(ir[i] * 2147483648.0);
                                if (q31 > 2147483647) q31 = 2147483647;
                                if (q31 < -2147483648) q31 = -2147483648;
                                cHeader += q31.toString();
                                if (i < ir.length - 1) cHeader += ", ";
                                if ((i + 1) % 4 === 0) cHeader += "\\n    ";
                            }
                            cHeader += `\\n};\\n\\n`;

                            cHeader += `// 16-bit Fixed Point Coefficients (Q15 format)\\n`;
                            cHeader += `// Aligned to 32-byte boundary for SIMD processing\\n`;
                            cHeader += `__attribute__((aligned(32)))\\n`;
                            cHeader += `const int16_t fir_taps_q15[FIR_TAPS] = {\\n    `;
                            
                            for (let i = 0; i < ir.length; i++) {
                                let q15 = Math.round(ir[i] * 32768.0);
                                if (q15 > 32767) q15 = 32767;
                                if (q15 < -32768) q15 = -32768;
                                cHeader += q15.toString();
                                if (i < ir.length - 1) cHeader += ", ";
                                if ((i + 1) % 8 === 0) cHeader += "\\n    ";
                            }
                            cHeader += `\\n};\\n\\n`;
                            
                            cHeader += `#endif // EQ_FILTER_H\\n`;

                            const blob = new Blob([cHeader], { type: 'text/x-c;charset=utf-8;' });
                            const url = URL.createObjectURL(blob);
                            const a = document.createElement('a');
                            a.href = url;
                            a.download = 'eq_filter.h';
                            document.body.appendChild(a);
                            a.click();
                            document.body.removeChild(a);
                            URL.revokeObjectURL(url);"""

new_fir = """                            // Format coefficients as .fir for DSP processors
                            let firContent = '';
                            for (let i = 0; i < ir.length; i++) {
                                firContent += ir[i].toFixed(10) + '\\n';
                            }
                            const blobFir = new Blob([firContent], { type: 'text/plain;charset=utf-8;' });
                            const urlFir = URL.createObjectURL(blobFir);
                            const aFir = document.createElement('a');
                            aFir.href = urlFir;
                            aFir.download = 'eq_filter.fir';
                            document.body.appendChild(aFir);
                            aFir.click();
                            document.body.removeChild(aFir);
                            URL.revokeObjectURL(urlFir);"""

code = code.replace(old_c_header, new_fir)

with open('FrontEnd/libControl/graphing/Equalization/Equalization.jsx', 'w') as f:
    f.write(code)

