/**
 * gen-legacy — parses FrontEnd/index.html and regenerates src/legacy.ts:
 * one side-effect import per local <script src> tag, in EXACT tag order
 * (the order encodes the dependency graph nobody wrote down — Phase 2 §2.3).
 *
 * - CDN tags are dropped: react/react-dom/echarts/echarts-gl/mqtt are npm
 *   dependencies now (exposed as globals by main.tsx); Babel dies with the
 *   bundle.
 * - Tags pointing at files that no longer exist are skipped with a comment
 *   (index.html still references deleted Sampler files).
 * - ?v=N cache-buster suffixes are stripped — Vite content-hashes output.
 *
 * Deterministic: same index.html in, same legacy.ts out. Every conversion
 * (step 2+) git-mv's a file into ui/src and deletes one line here; empty
 * file = migration structurally done.
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const UI_DIR = join(dirname(fileURLToPath(import.meta.url)), '..')
const REPO_ROOT = join(UI_DIR, '..')
const INDEX_HTML = join(REPO_ROOT, 'FrontEnd/index.html')
const OUT = join(UI_DIR, 'src/legacy.ts')

const html = readFileSync(INDEX_HTML, 'utf8')
const tagRe = /<script\b[^>]*\bsrc="([^"]+)"[^>]*>/g

const lines: string[] = [
  '// GENERATED by scripts/gen-legacy.ts from FrontEnd/index.html — regenerate with `pnpm gen:legacy`.',
  '// Side-effect imports of every unconverted legacy file, in EXACT script-tag order.',
  '// Converting a file (git mv into ui/src) deletes its line here. Empty file = done.',
  '',
]
let kept = 0
let skippedMissing = 0
let droppedCdn = 0

for (const match of html.matchAll(tagRe)) {
  const rawSrc = match[1]!
  if (/^https?:\/\//.test(rawSrc)) {
    droppedCdn++
    continue
  }
  const clean = rawSrc.replace(/^\.\//, '').replace(/\?.*$/, '')
  const abs = join(REPO_ROOT, 'FrontEnd', clean)
  if (!existsSync(abs)) {
    lines.push(`// SKIPPED (file missing on disk — dead tag in index.html): ../../FrontEnd/${clean}`)
    skippedMissing++
    continue
  }
  lines.push(`import '../../FrontEnd/${clean}'`)
  kept++
}

lines.push('')
writeFileSync(OUT, lines.join('\n'))
console.log(`legacy.ts: ${kept} imports, ${skippedMissing} missing skipped, ${droppedCdn} CDN dropped`)
