/**
 * gen-globals — scans the unconverted FrontEnd tree for `window.X = ...`
 * assignments and regenerates src/globals.d.ts: the typed inventory of the
 * implicit module system (Phase 2 §2.1).
 *
 * Every global starts as `any` — burned down to real types as conversion
 * proceeds. THE METRIC: `grep -c 'any //' src/globals.d.ts` only goes down.
 * Regen never downgrades: a hand-typed entry (no `any //` marker) survives
 * regeneration; only new/still-untyped globals get `any`.
 */
import { readFileSync, readdirSync, statSync, writeFileSync, existsSync } from 'node:fs'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

const UI_DIR = join(dirname(fileURLToPath(import.meta.url)), '..')
const FRONTEND = join(UI_DIR, '../FrontEnd')
const OUT = join(UI_DIR, 'src/globals.d.ts')

// window.Name = | window['Name'] =   (assignment, not reads)
const ASSIGN_RE = /window(?:\.([A-Za-z_$][\w$]*)|\[['"]([A-Za-z_$][\w$]*)['"]\])\s*=(?!=)/g
const SKIP_DIRS = new Set(['Gui_Frames', 'api', 'node_modules', 'wasm'])

const owners = new Map<string, Set<string>>()

function walk(dir: string) {
  for (const e of readdirSync(dir).sort()) {
    if (SKIP_DIRS.has(e)) continue
    const p = join(dir, e)
    if (statSync(p).isDirectory()) walk(p)
    else if (/\.(jsx?|tsx?)$/.test(e)) {
      const src = readFileSync(p, 'utf8')
      for (const m of src.matchAll(ASSIGN_RE)) {
        const name = (m[1] ?? m[2])!
        owners.set(name, (owners.get(name) ?? new Set()).add(relative(FRONTEND, p)))
      }
    }
  }
}
walk(FRONTEND)

// Preserve hand-typed entries from the existing file.
const handTyped = new Map<string, string>()
if (existsSync(OUT)) {
  for (const line of readFileSync(OUT, 'utf8').split('\n')) {
    const m = /^\s{4}([A-Za-z_$][\w$]*):\s(.+)$/.exec(line)
    if (m && !m[2]!.startsWith('any //')) handTyped.set(m[1]!, m[2]!)
  }
}

const names = [...owners.keys()].sort((a, b) => a.localeCompare(b))
const lines = [
  '// GENERATED by scripts/gen-globals.ts — regenerate with `pnpm gen:globals`.',
  '// The window.* inventory of the unconverted FrontEnd tree: the implicit',
  '// module system, typed. `any // from <file>` entries are the debt; replace',
  '// them with real types as files convert (hand-typed lines survive regen).',
  `// METRIC: ${names.length} globals, ${names.length - handTyped.size} still \`any\`.`,
  '',
  'export {}',
  '',
  'declare global {',
  '  interface Window {',
]
for (const name of names) {
  const files = [...owners.get(name)!]
  const entry = handTyped.get(name) ?? `any // from ${files[0]}${files.length > 1 ? ` (+${files.length - 1} more)` : ''}`
  lines.push(`    ${name}: ${entry}`)
}
lines.push('  }', '}', '')
writeFileSync(OUT, lines.join('\n'))
console.log(`globals.d.ts: ${names.length} globals (${handTyped.size} hand-typed, ${names.length - handTyped.size} any)`)
