def get_core_factory_mapping(self):
    """Returns the core dictionary mapping JSON keys to creator methods."""
    return {
        # Standard Widgets
        "_sliderValue": self.make_slider_value,
        "_Horizontal_with_dial_Value": self.make_composite_horizontal_dial_value,
        "HorizontalWithValue": self.make_composite_horizontal_dial_value,
        "_GuiButtonToggle": self.make_button_toggle,
        "_SmartToggle": self.make_button_toggle,
        "_GuiButtonToggler": self.make_button_toggler,
        "_SmartToggler": self.make_button_toggler,
        "_GuiDropDownOption": self.make_text_gui_dropdown_option,
        "_Value": self.make_text_value_box,
        "_SmartValue": self.make_text_value_box,
        "_GuiValue": self.make_text_value_box,
        "_Label": self.make_text_label_from_config,
        "_SmartLabel": self.make_text_label_from_config,
        "_GuiLabel": self.make_text_label_from_config,
        "_GuiActuator": self.make_button_actuator,
        "_SmartActuator": self.make_button_actuator,
        "_GuiButton": self.make_button_actuator,
        "_GuiCheckbox": self.make_checkbox,
        "_SmartCheckbox": self.make_checkbox,
        "_GuiListbox": self.make_listbox,
        "_SmartList": self.make_listbox,
        "_ProgressBar": self.make_images_progress_bar,
        "_SmartProgress": self.make_images_progress_bar,
        "OcaTable": self.make_text_table,
        "GuiTable": self.make_text_table,
        "DynamicGuiTable": self.make_text_table,
        "DynamicGraph": self._create_plot_widget,
        "DynamicBarGraph": self._create_bar_graph_widget,
        "_SmartGraph": self._create_plot_widget,
        "_DataGraph": self._create_plot_widget,
        "_GuiGraph": self._create_plot_widget,
        "_TextInput": self.make_text_value_with_units,
        "_SmartInput": self.make_text_value_with_units,
        "_WebLink": self.make_text_web_link,
        "_SmartLink": self.make_text_web_link,
        "_ImageDisplay": self.make_images_image_display,
        "_SmartImage": self.make_images_image_display,
        "_GuiImage": self.make_images_image_display,
        "AnimationDisplay": self.make_images_animation_display,
        "_AnimationDisplay": self.make_images_animation_display,
        "_GuiAnimation": self.make_images_animation_display,
        "_SmartAnimation": self.make_images_animation_display,
        "_JsonTree": self.make_data_json_tree,
        "JsonTree": self.make_data_json_tree,
        "_BarGraph": self.make_meter_bar,
        "_SmartMeter": self.make_meter_bar,
        "_MeterBar": self.make_meter_bar,
        "MeterBar": self.make_meter_bar,
        "_Fader": self.make_fader,
        "_GuiVerticalFader": self.make_fader,
        "_Knob": self.make_knob,
        "_SmartKnob": self.make_knob,
        "_GuiHorizontalKnob": self.make_knob,
        "SelectorSwitch": self.make_knob_rotary_selector,
        "_SelectorSwitch": self.make_knob_rotary_selector,
        "_IncDecButtons": self.make_input_inc_dec_buttons,
        "_SmartIncDec": self.make_input_inc_dec_buttons,
        "_DirectionalButtons": self.make_input_directional_buttons,
        "_SmartNav": self.make_input_directional_buttons,
        "_CustomFader": self.make_fader,
        "_SmartFader": self.make_fader,
        "_CustomHorizontalFader": self.make_fader_horizontal,
        "_CustomDualHorizontalFader": self._lazy_wrap("workers.builder.fader_dual.fader_dual", "BuilderFaderDualCreator", "make_fader_dual"),
        "_CustomDualVerticalFader": self._lazy_wrap("workers.builder.fader_dual.fader_dual", "BuilderFaderDualCreator", "make_fader_dual"),
        "_CustomLTP": self._lazy_wrap("workers.builder.fader_linear_travelling_potentiometer.fader_linear_travelling_potentiometer", "BuilderFaderLinearTravellingPotentiometerCreator", "make_fader_linear_travelling_potentiometer"),
        "_NeedleVUMeter": self.make_meter_needle,
        "_GuiAnalogGauge": self.make_meter_needle,
        "_TrapezoidButton": self.make_button_trapezoid,
        "_TrapezoidButtonToggler": self.make_button_trapezoid_toggler,
        "_HeaderStatusLight": self._create_status_light,
        "_SmartLight": self._create_status_light,
        "_WinkButton": self.make_button_wink,
        "_WinkButtonToggler": self.make_button_wink_toggler,
        "wink_toggler": self.make_button_wink_toggler,
        "_VUMeterKnob": self.make_meter_knob_with_vu_meter,
        "_BarGraphKnob": self.make_meter_knob_with_vu_meter,
        "_Radar": self.make_data_radar,
        "_CompositeFader": self._lazy_wrap("workers.builder.fader_ganged_controlled_array.fader_ganged_controlled_array", "BuilderFaderGangedControlledArrayCreator", "make_fader_ganged_controlled_array"),
        "_FaderWithBarGraph": self._lazy_wrap("workers.builder.fader_bar_graph.fader_bar_graph", "BuilderFaderBarGraphCreator", "make_fader_bar_graph"),
        "_MDP": self._lazy_wrap("workers.builder.composite_mdp.composite_mdp", "BuilderCompositeMdpCreator", "make_composite_mdp"),
        "_CMDP": self._lazy_wrap("workers.builder.circular_motion_displacement_potentiometer.circular_motion_displacement_potentiometer", "BuilderCircularMotionDisplacementPotentiometerCreator", "make_circular_motion_displacement_potentiometer"),
        # Complex Adapters
        "plot_widget": self._create_plot_widget,
        "_HorizontalMeterWithText": self._create_horizontal_meter,
        "_VerticalMeter": self._create_vertical_meter,
        "OcaBreakLine": self._create_break_line,
        "OcaSeparator": self._create_break_line,
        "OcaFold": self._create_break_line,
        "OcaArray": self.make_array,
        "OcaCollapsibleBlock": self._create_collapsible_block,
    }
