// GENERATED by scripts/gen-globals.ts — regenerate with `pnpm gen:globals`.
// The window.* inventory of the unconverted FrontEnd tree: the implicit
// module system, typed. `any // from <file>` entries are the debt; replace
// them with real types as files convert (hand-typed lines survive regen).
// METRIC: 184 globals, 181 still `any`.

export {}

declare global {
  interface Window {
    __gca_in_master_move: any // from libControl/faders/GCA/GCA.jsx
    _Aes70: any // from libControl/special/Aes70/Aes70.jsx
    _CommandRouter: any // from libControl/special/CommandRouter/CommandRouter.jsx
    _Dnssd: any // from libControl/special/Dnssd/Dnssd.jsx
    _Ember: any // from libControl/special/Ember/Ember.jsx
    _GraphingCont: any // from libControl/special/GraphingCont/GraphingCont.jsx
    _GraphingCont1: any // from libControl/special/GraphingCont1/GraphingCont1.jsx
    _GraphingElements: any // from libControl/special/GraphingElements/GraphingElements.jsx
    _GuiOsc: any // from libControl/special/GuiOsc/GuiOsc.jsx
    _GuiRest: any // from libControl/special/GuiRest/GuiRest.jsx
    _Mdns: any // from libControl/special/Mdns/Mdns.jsx
    _MediaButtons: any // from libControl/special/MediaButtons/MediaButtons.jsx
    _MidiIn: any // from libControl/special/MidiIn/MidiIn.jsx
    _MidiOutput: any // from libControl/special/MidiOutput/MidiOutput.jsx
    _NmosCommands: any // from libControl/special/NmosCommands/NmosCommands.jsx
    _NmosConnection: any // from libControl/special/NmosConnection/NmosConnection.jsx
    _NmosWebsockets: any // from libControl/special/NmosWebsockets/NmosWebsockets.jsx
    _OA_FACE_CACHE: any // from libControl/metering/NeedleMeter/NeedleMeter.jsx
    _OA_PANEL_CACHE: any // from libControl/Panels/Panel/Panel.jsx
    _ProtocolMatrix: any // from libControl/special/ProtocolMatrix/ProtocolMatrix.jsx
    _Sap: any // from libControl/special/Sap/Sap.jsx
    _Smpte2138Monitor: any // from libControl/special/Smpte2138Monitor/Smpte2138Monitor.jsx
    _SnmpLog: any // from libControl/special/SnmpLog/SnmpLog.jsx
    _SnmpMib: any // from libControl/special/SnmpMib/SnmpMib.jsx
    _SnmpStatus: any // from libControl/special/SnmpStatus/SnmpStatus.jsx
    _SnmpVerify: any // from libControl/special/SnmpVerify/SnmpVerify.jsx
    _SnmpVerifyMib: any // from libControl/special/SnmpVerifyMib/SnmpVerifyMib.jsx
    _YakMonitor: any // from libControl/special/YakMonitor/YakMonitor.jsx
    AnimationDisplay: any // from libControl/images/AnimationDisplay/AnimationDisplay.jsx
    AudioAnalyzerDemo: any // from libControl/metering/AudioAnalyzerDemo/AudioAnalyzerDemo.jsx
    AudioDynamics: any // from libControl/graphing/AudioDynamics/AudioDynamics.jsx
    BreakLine: any // from libControl/BreakLine/BreakLine.jsx
    ButtonToggle: any // from libControl/buttons/ButtonToggle/ButtonToggle.jsx
    ButtonToggler: any // from libControl/buttons/ButtonToggler/ButtonToggler.jsx
    CMDP: any // from libControl/special/CMDP/CMDP.jsx
    CMDPEditor: any // from libControl/special/CMDP/CMDPEditor.jsx
    describeArc: any // from libControl/Knobs/Knob/Knob.jsx
    DirectionalButtons: any // from libControl/input/DirectionalButtons/DirectionalButtons.jsx
    DualFader: any // from libControl/faders/DualFader/DualFader.jsx
    DynamicGraph: any // from libControl/graphing/DynamicGraph/DynamicGraph.jsx
    DynamicsEnvelope: any // from libControl/graphing/DynamicsEnvelope/DynamicsEnvelope.jsx
    DynamicsPresets: any // from libControl/special/DynamicsPresets/DynamicsPresets.jsx
    Equalization: any // from libControl/graphing/Equalization/Equalization.jsx
    Fader: any // from libControl/faders/Fader/Fader.jsx (+1 more)
    FaderCap: any // from libControl/faders/core/Cap.jsx
    FaderDial: any // from libControl/faders/FaderDial/FaderDial.jsx
    FaderScale: any // from libControl/faders/core/Scale.jsx
    FaderSlider: any // from libControl/faders/core/Slider.jsx
    FaderUtils: any // from libControl/faders/core/utils.js
    FaderWithMeter: any // from libControl/faders/FaderWithMeter/FaderWithMeter.jsx
    FieldComponent: any // from frameLayout/FieldComponent.jsx
    GCA: any // from libControl/faders/GCA/GCA.jsx
    HighVisButton: any // from libControl/buttons/HighVisButton/HighVisButton.jsx
    ImageDisplay: any // from libControl/images/ImageDisplay/ImageDisplay.jsx
    IncDecButtons: any // from libControl/input/IncDecButtons/IncDecButtons.jsx
    Knob: any // from libControl/Knobs/Knob/Knob.jsx
    KnobCap1176: any // from libControl/Knobs/Knob/caps/K1176.jsx
    KnobCapAPI: any // from libControl/Knobs/Knob/caps/API.jsx
    KnobCapBritish: any // from libControl/Knobs/Knob/caps/British.jsx
    KnobCapChicken: any // from libControl/Knobs/Knob/caps/Chicken.jsx
    KnobCapCrafty: any // from libControl/Knobs/Knob/caps/Crafty.jsx
    KnobCapFender: any // from libControl/Knobs/Knob/caps/Fender.jsx
    KnobCapMarconi: any // from libControl/Knobs/Knob/caps/Marconi.jsx
    KnobCapMoog: any // from libControl/Knobs/Knob/caps/Moog.jsx
    KnobCapPedal: any // from libControl/Knobs/Knob/caps/Pedal.jsx
    KnobCapStandard: any // from libControl/Knobs/Knob/caps/Standard.jsx
    KnobCapWBSElma: any // from libControl/Knobs/Knob/caps/WBSElma.jsx
    launchWysiwygEditor: any // from editorWYSIWYG/Entry.jsx
    LoaderOrchestrator: any // from frameLayout/LoaderOrchestrator.jsx
    LTPFader: any // from libControl/faders/LTPFader/LTPFader.jsx
    MDP: any // from libControl/faders/MDP/MDP.jsx (+1 more)
    MeterBarGraph: any // from libControl/metering/MeterBarGraph/MeterBarGraph.jsx
    MidiKeyboard: any // from libControl/special/MidiKeyboard/MidiKeyboard.jsx
    MidiMessageLog: any // from libControl/special/MidiMessageLog/MidiMessageLog.jsx
    MqttProvider: import('react').ComponentType<{ brokerUrl: string; username: string; password: string; children?: import('react').ReactNode }>
    MqttSettingsModal: any // from comMQTT/MqttSettings.jsx
    NeedleMeter: any // from libControl/metering/NeedleMeter/NeedleMeter.jsx
    OA_COMPONENTS: any // from libControl/special/Aes70/Aes70.jsx (+27 more)
    OA_MQTT_DEBUG: any // from comMQTT/MqttProvider.jsx
    OA_MQTT_FILTER: any // from comMQTT/MqttProvider.jsx
    OA_MQTT_LAST: any // from comMQTT/MqttProvider.jsx
    OA_PANEL_DEFAULT_CONFIG: any // from libControl/Panels/panel_wasm_loader.js
    OA_SCAN_ACTIVITY: any // from comMQTT/MqttProvider.jsx
    OA_SESSION_FULL_ID: any // from comMQTT/MqttProvider.jsx
    oaCssLen: any // from frameLayout/oaCssLen.js
    OaDesigner_FaderDial: any // from libControl/faders/FaderDial/Designer.jsx
    OaDesigner_NeedleMeter: any // from libControl/metering/NeedleMeter/Designer.jsx
    OaDesignerRegistry: any // from editorWYSIWYG/Interface/PropertyEditor/artistic_designer.jsx (+2 more)
    OaDsp: any // from libControl/graphing/_dsp/dsp.js
    OaEdArtisticCtl: any // from editorWYSIWYG/Interface/PropertyEditor/artistic_designer.jsx
    OaEdArtisticDesigner: any // from editorWYSIWYG/Interface/PropertyEditor/artistic_designer.jsx
    OaEdArtisticGeneric: any // from editorWYSIWYG/Interface/PropertyEditor/artistic_designer.jsx
    OaEdArtisticPreview: any // from editorWYSIWYG/Interface/PropertyEditor/artistic_designer.jsx
    OaEdCanvas: any // from editorWYSIWYG/Interface/Tabs/InteractiveLayout/interactive_layout.jsx
    OaEdComposite: any // from editorWYSIWYG/Constants/composite_schemas.jsx
    OaEdConfigClip: any // from editorWYSIWYG/Interface/PropertyEditor/Copy_config.jsx
    OaEdCopyConfig: any // from editorWYSIWYG/Interface/PropertyEditor/Copy_config.jsx
    OaEdCopyLayout: any // from editorWYSIWYG/Interface/PropertyEditor/CopyLayout.jsx
    OaEdCopyStyle: any // from editorWYSIWYG/Interface/PropertyEditor/CopyStyle.jsx
    OaEdDragMove: any // from editorWYSIWYG/Interface/layout_engine/drag_move.jsx
    OaEdEntry: any // from editorWYSIWYG/Entry.jsx
    OaEdEnum: any // from editorWYSIWYG/Constants/property_options.jsx
    OaEdFileReader: any // from editorWYSIWYG/FileReaders/file_reader.jsx
    OaEdFileWriter: any // from editorWYSIWYG/FileWriters/file_writer.jsx
    OaEdFocus: any // from editorWYSIWYG/Interface/layout_engine/focus.jsx
    OaEdGrabBag: any // from editorWYSIWYG/Interface/Tabs/GrabBagView/grab_bag_view.jsx
    OaEdGrabBagLoader: any // from editorWYSIWYG/FileReaders/grab_bag_loader.jsx
    OaEdGrid: any // from editorWYSIWYG/Methods/builder_editor_grid.jsx
    OaEdJsonEditor: any // from editorWYSIWYG/Interface/Tabs/JsonEditor/json_editor.jsx
    OaEdLayout: any // from editorWYSIWYG/Interface/Window/editor_layout.jsx
    OaEdLayoutClip: any // from editorWYSIWYG/Interface/PropertyEditor/CopyLayout.jsx
    OaEdPreview: any // from editorWYSIWYG/Interface/layout_engine/preview_engine.jsx
    OaEdPreviewCtx: any // from frameLayout/OcaArray.jsx
    OaEdProperties: any // from editorWYSIWYG/Interface/Tabs/ElementProperties/Entry.jsx
    OaEdPropertyLeaf: any // from editorWYSIWYG/Interface/PropertyEditor/property_leaf.jsx
    OaEdPropertyTree: any // from editorWYSIWYG/Interface/renderers/tree_renderer.jsx
    OaEdResizeHandles: any // from editorWYSIWYG/Interface/layout_engine/resize_handles.jsx
    OaEdRuler: any // from editorWYSIWYG/Interface/layout_engine/ruler.jsx
    OaEdSelectionOverlay: any // from editorWYSIWYG/Interface/layout_engine/overlay_manager.jsx
    OaEdSnap: any // from editorWYSIWYG/Interface/layout_engine/snap_logic.jsx
    OaEdState: any // from editorWYSIWYG/Core/state.jsx
    OaEdStyleClip: any // from editorWYSIWYG/Interface/PropertyEditor/CopyStyle.jsx
    OaEdToolbar: any // from editorWYSIWYG/Interface/Window/editor_toolbar.jsx
    OaEdTransparencyControls: any // from editorWYSIWYG/Interface/PropertyEditor/artistic_designer.jsx
    OaEdTree: any // from editorWYSIWYG/Interface/Tabs/TreeRefactor/Entry.jsx
    oaGetMqttConfig: (() => { brokerUrl: string; username: string; password: string }) | undefined
    OaIsMomentaryControl: any // from comMQTT/MqttProvider.jsx
    OaJfir: any // from libControl/graphing/_dsp/jfir.js
    oaLabelStyle: any // from frameLayout/oaCssLen.js
    oaLabelText: any // from frameLayout/oaCssLen.js
    OaNav: any // from tabManager/nav_state.jsx
    OaPanelContext: any // from frameLayout/OcaBin.jsx
    OAPanels: any // from libControl/Panels/panel_wasm_loader.js
    oaPickLabel: any // from frameLayout/oaCssLen.js
    oaPickLabelStyle: any // from frameLayout/oaCssLen.js
    OaTopicMaker: any // from comMQTT/topicMaker.jsx
    OaTransparency: any // from frameLayout/transparency.js
    OcaArray: any // from frameLayout/OcaArray.jsx
    OcaBin: any // from frameLayout/OcaBin.jsx
    OcaBlock: any // from frameLayout/OcaBlock.jsx
    OcaButton: any // from libControl/buttons/Button/Button.jsx
    OcaCheckbox: any // from libControl/input/InputElements/InputElements.jsx (+1 more)
    OcaDropdown: any // from libControl/input/InputElements/InputElements.jsx
    OcaIncDecButtons: any // from libControl/input/InputElements/InputElements.jsx
    OcaJsonTree: any // from libControl/input/JsonTree/JsonTree.jsx
    OcaListbox: any // from libControl/input/OcaListbox/OcaListbox.jsx
    OcaProgressBar: any // from libControl/metering/OcaProgressBar/OcaProgressBar.jsx
    OcaSliderValue: any // from libControl/input/OcaSliderValue/OcaSliderValue.jsx
    OcaTable: any // from libControl/text/OcaTable/OcaTable.jsx
    OcaTextInput: any // from libControl/input/OcaTextInput/OcaTextInput.jsx
    OcaTextLabel: any // from libControl/text/TextElements/TextElements.jsx
    OcaTextValueBox: any // from libControl/text/TextElements/TextElements.jsx
    OcaToggleButton: any // from libControl/buttons/Button/Button.jsx
    OcaTrapezoidButton: any // from libControl/buttons/TrapezoidButton/TrapezoidButton.jsx
    OcaWebLink: any // from libControl/text/OcaWebLink/OcaWebLink.jsx
    OcaWinkButton: any // from libControl/buttons/WinkButton/WinkButton.jsx
    Panel: any // from libControl/Panels/Panel/Panel.jsx
    polarToCartesian: any // from libControl/Knobs/Knob/Knob.jsx
    ProtocolConfigDisplay: any // from libControl/special/ProtocolConfigDisplay/ProtocolConfigDisplay.jsx
    Radar: any // from libControl/graphing/Radar/Radar.jsx
    Reverb: any // from libControl/graphing/Reverb/Reverb.jsx
    ScanActivity: any // from libControl/special/ScanActivity/ScanActivity.jsx
    Screw: any // from libControl/Panels/Screw/Screw.jsx
    SelectorSwitch: any // from libControl/Knobs/SelectorSwitch/SelectorSwitch.jsx
    shadeHex: any // from libControl/Knobs/Knob/Knob.jsx
    SplitLayout: any // from frameLayout/SplitLayout.jsx
    StatusLight: any // from libControl/special/StatusLight/StatusLight.jsx
    TabLayout: any // from frameLayout/TabLayout.jsx
    TabManager: any // from tabManager/TabManager.jsx
    TrapezoidButtonToggler: any // from libControl/buttons/TrapezoidButtonToggler/TrapezoidButtonToggler.jsx
    useDiscoveryActivity: any // from comMQTT/MqttProvider.jsx
    useEditorStore: any // from editorWYSIWYG/Core/state.jsx
    useMqttLang: any // from comMQTT/MqttProvider.jsx
    useMqttMessages: any // from comMQTT/MqttProvider.jsx
    useMqttPublish: any // from comMQTT/MqttProvider.jsx
    useMqttState: any // from comMQTT/MqttProvider.jsx
    useMqttStatus: any // from comMQTT/MqttProvider.jsx
    useMqttTrigger: any // from comMQTT/MqttProvider.jsx
    VUMeterKnob: any // from libControl/metering/VUMeterKnob/VUMeterKnob.jsx
    WidgetFactory: any // from frameLayout/WidgetFactory.jsx
    WindowManager: import('react').ComponentType<{ directoryTree: unknown }>
    WinkButtonToggler: any // from libControl/buttons/WinkButtonToggler/WinkButtonToggler.jsx
    WysiwygEditor: any // from editorWYSIWYG/Managers/wysiwyg_editor.jsx
    YakAutoBuilder: any // from libControl/special/YakAutoBuilder/YakAutoBuilder.jsx
  }
}
