import json
import os
import re

# Technical Translation Mapping
TECHNICAL_CONTEXT = {
    "Subs": {"Fr": "Sous-groupes", "De": "Subgruppen", "Es": "Subgrupos"},
    "Aux": {"Fr": "Auxiliaires", "De": "Aux-Sende", "Es": "Auxiliares"},
    "Needle": {"Fr": "Aiguille", "De": "Nadel", "Es": "Aguja"},
    "Wink": {"Fr": "Obturateur", "De": "Verschluss", "Es": "Obturador"},
}

# Extensive Translation Dictionary
TRANSLATIONS = {
    "Pause": {"Fr": "Pause", "De": "Pause", "Es": "Pausa"},
    "Start": {"Fr": "Démarrer", "De": "Start", "Es": "Inicio"},
    "Stop": {"Fr": "Arrêter", "De": "Stopp", "Es": "Parar"},
    "Frequency (GHz)": {"Fr": "Fréquence (GHz)", "De": "Frequenz (GHz)", "Es": "Frecuencia (GHz)"},
    "Amplitude (dBm)": {"Fr": "Amplitude (dBm)", "De": "Amplitude (dBm)", "Es": "Amplitud (dBm)"},
    "Reference": {"Fr": "Référence", "De": "Referenz", "Es": "Referencia"},
    "Signal Alpha": {"Fr": "Signal Alpha", "De": "Signal Alpha", "Es": "Señal Alpha"},
    "Signal Beta": {"Fr": "Signal Bêta", "De": "Signal Beta", "Es": "Señal Beta"},
    "High Resolution Spectrum Scan": {"Fr": "Balayage spectral haute résolution", "De": "Hochauflösender Spektrum-Scan", "Es": "Escaneo de espectro de alta resolución"},
    "Root container locked to window edges with smart auto-scrolling.": {"Fr": "Conteneur racine verrouillé sur les bords de la fenêtre avec défilement automatique intelligent.", "De": "Root-Container an Fensterrändern fixiert mit intelligentem automatischem Scrollen.", "Es": "Contenedor raíz bloqueado en los bordes de la ventana con desplazamiento automático inteligente."},
    "Frequency": {"Fr": "Fréquence", "De": "Frequenz", "Es": "Frecuencia"},
    "Amplitude": {"Fr": "Amplitude", "De": "Amplitude", "Es": "Amplitud"},
    "Bandwidth": {"Fr": "Largeur de bande", "De": "Bandbreite", "Es": "Ancho de banda"},
    "Trace": {"Fr": "Trace", "De": "Spur", "Es": "Traza"},
    "Marker": {"Fr": "Marqueur", "De": "Marker", "Es": "Marcador"},
    "System": {"Fr": "Système", "De": "System", "Es": "Sistema"},
    "Current": {"Fr": "Courant", "De": "Strom", "Es": "Corriente"},
    "Voltage": {"Fr": "Tension", "De": "Spannung", "Es": "Voltaje"},
    "Resistance": {"Fr": "Résistance", "De": "Widerstand", "Es": "Resistencia"},
    "Power": {"Fr": "Puissance", "De": "Leistung", "Es": "Potencia"},
    "Input": {"Fr": "Entrée", "De": "Eingang", "Es": "Entrada"},
    "Output": {"Fr": "Sortie", "De": "Ausgang", "Es": "Salida"},
    "Channel": {"Fr": "Canal", "De": "Kanal", "Es": "Canal"},
    "Measure": {"Fr": "Mesurer", "De": "Messen", "Es": "Medida"},
    "Trigger": {"Fr": "Déclencheur", "De": "Trigger", "Es": "Disparo"},
    "Settings": {"Fr": "Paramètres", "De": "Einstellungen", "Es": "Ajustes"},
    "Control": {"Fr": "Contrôle", "De": "Steuerung", "Es": "Control"},
    "Mode": {"Fr": "Mode", "De": "Modus", "Es": "Modo"},
    "Level": {"Fr": "Niveau", "De": "Pegel", "Es": "Nivel"},
    "Gain": {"Fr": "Gain", "De": "Verstärkung", "Es": "Ganancia"},
    "Attenuation": {"Fr": "Atténuation", "De": "Dämpfung", "Es": "Atenuación"},
    "Coupling": {"Fr": "Couplage", "De": "Kopplung", "Es": "Acoplamiento"},
    "Offset": {"Fr": "Décalage", "De": "Versatz", "Es": "Compensación"},
    "Scale": {"Fr": "Échelle", "De": "Skala", "Es": "Escala"},
    "Status": {"Fr": "Statut", "De": "Status", "Es": "Estado"},
    "Common": {"Fr": "Commun", "De": "Allgemein", "Es": "Común"},
    "Transient": {"Fr": "Transitoire", "De": "Transient", "Es": "Transitorio"},
    "Connection": {"Fr": "Connexion", "De": "Verbindung", "Es": "Conexión"},
    "Configuration": {"Fr": "Configuration", "De": "Konfiguration", "Es": "Configuración"},
    "Instrument": {"Fr": "Instrument", "De": "Instrument", "Es": "Instrumento"},
    "Oscilloscope": {"Fr": "Oscilloscope", "De": "Oszilloskop", "Es": "Osciloscopio"},
    "Generator": {"Fr": "Générateur", "De": "Generator", "Es": "Generador"},
    "Spectrum": {"Fr": "Spectre", "De": "Spektrum", "Es": "Espectro"},
    "Router": {"Fr": "Routeur", "De": "Router", "Es": "Router"},
    "Console": {"Fr": "Console", "De": "Konsole", "Es": "Consola"},
    "Load": {"Fr": "Charge", "De": "Last", "Es": "Carga"},
    "Presets": {"Fr": "Préréglages", "De": "Voreinstellungen", "Es": "Preajustes"},
    "Sweeping": {"Fr": "Balayage", "De": "Wobbeln", "Es": "Barrido"},
    "Plotting": {"Fr": "Tracé", "De": "Plotten", "Es": "Trazado"},
    "Reports": {"Fr": "Rapports", "De": "Berichte", "Es": "Informes"},
    "EngineGuiDisplay": {"Fr": "EngineGuiDisplay", "De": "Anwendung", "Es": "Aplicación"},
    "Filepaths": {"Fr": "Chemins de fichiers", "De": "Dateipfade", "Es": "Rutas de archivos"},
    "Monitors": {"Fr": "Moniteurs", "De": "Monitore", "Es": "Monitores"},
    "Graphs": {"Fr": "Graphiques", "De": "Grafiken", "Es": "Gráficos"},
    "Scan": {"Fr": "Balayage", "De": "Scan", "Es": "Escaneo"},
    "Setup": {"Fr": "Installation", "De": "Einrichtung", "Es": "Configuración"},
    "Fleet": {"Fr": "Flotte", "De": "Flotte", "Es": "Flota"},
    "MQTT": {"Fr": "MQTT", "De": "MQTT", "Es": "MQTT"},
    "AES70": {"Fr": "AES70", "De": "AES70", "Es": "AES70"},
    "Constants": {"Fr": "Constantes", "De": "Konstanten", "Es": "Constantes"},
    "Television": {"Fr": "Télévision", "De": "Fernsehen", "Es": "Televisión"},
    "Government": {"Fr": "Gouvernement", "De": "Regierung", "Es": "Gobierno"},
    "RfComponents": {"Fr": "Composants RF", "De": "RF-Komponenten", "Es": "Componentes de RF"},
    "Antenna": {"Fr": "Antenne", "De": "Antenne", "Es": "Antena"},
    "Amplifier": {"Fr": "Amplificateur", "De": "Verstärker", "Es": "Amplificador"},
    "Bands": {"Fr": "Bandes", "De": "Bänder", "Es": "Bandas"},
    "Frequency (Hz)": {"Fr": "Fréquence (Hz)", "De": "Frequenz (Hz)", "Es": "Frecuencia (Hz)"},
    "Center Frequency": {"Fr": "Fréquence centrale", "De": "Mittenfrequenz", "Es": "Frecuencia central"},
    "Span": {"Fr": "Portée", "De": "Spanne", "Es": "Intervalo"},
    "Start Frequency": {"Fr": "Fréquence de début", "De": "Startfrequenz", "Es": "Frecuencia de inicio"},
    "Stop Frequency": {"Fr": "Fréquence de fin", "De": "Stoppfrequenz", "Es": "Frecuencia de parada"},
    "Resolution Bandwidth": {"Fr": "Largeur de bande de résolution", "De": "Auflösungsbandbreite", "Es": "Ancho de banda de resolución"},
    "Video Bandwidth": {"Fr": "Largeur de bande vidéo", "De": "Videobandbreite", "Es": "Ancho de banda de video"},
    "Sweep Time": {"Fr": "Temps de balayage", "De": "Wobbelzeit", "Es": "Tiempo de barrido"},
    "Average": {"Fr": "Moyenne", "De": "Mittelwert", "Es": "Promedio"},
    "Peak": {"Fr": "Crête", "De": "Spitzenwert", "Es": "Pico"},
    "Averaging": {"Fr": "Moyennage", "De": "Mittelung", "Es": "Promediado"},
    "Center": {"Fr": "Centre", "De": "Mitte", "Es": "Centro"},
    "Manual": {"Fr": "Manuel", "De": "Manuell", "Es": "Manual"},
    "Auto": {"Fr": "Auto", "De": "Auto", "Es": "Auto"},
    "Hold": {"Fr": "Maintien", "De": "Halten", "Es": "Mantener"},
    "Max Hold": {"Fr": "Maintien max", "De": "Max-Hold", "Es": "Mantener máx"},
    "Min Hold": {"Fr": "Maintien min", "De": "Min-Hold", "Es": "Mantener mín"},
    "Continuous": {"Fr": "Continu", "De": "Kontinuierlich", "Es": "Continuo"},
    "Single": {"Fr": "Unique", "De": "Einzel", "Es": "Único"},
    "Normal": {"Fr": "Normal", "De": "Normal", "Es": "Normal"},
    "High Resolution": {"Fr": "Haute résolution", "De": "Hohe Auflösung", "Es": "Alta resolución"},
    "Low Noise": {"Fr": "Faible bruit", "De": "Rauscharm", "Es": "Bajo ruido"},
    "Wide": {"Fr": "Large", "De": "Breit", "Es": "Ancho"},
    "Narrow": {"Fr": "Étroit", "De": "Schmal", "Es": "Estrecho"},
    "Fast": {"Fr": "Rapide", "De": "Schnell", "Es": "Rápido"},
    "Slow": {"Fr": "Lent", "De": "Langsam", "Es": "Lento"},
    "Active": {"Fr": "Actif", "De": "Aktiv", "Es": "Activo"},
    "Inactive": {"Fr": "Inactif", "De": "Inaktiv", "Es": "Inactivo"},
    "Enabled": {"Fr": "Activé", "De": "Aktiviert", "Es": "Activado"},
    "Disabled": {"Fr": "Désactivé", "De": "Deaktiviert", "Es": "Desactivado"},
    "On": {"Fr": "Marche", "De": "Ein", "Es": "Encendido"},
    "Off": {"Fr": "Arrêt", "De": "Aus", "Es": "Apagado"},
    "Yes": {"Fr": "Oui", "De": "Ja", "Es": "Sí"},
    "No": {"Fr": "Non", "De": "Nein", "Es": "No"},
    "Clear": {"Fr": "Effacer", "De": "Löschen", "Es": "Borrar"},
    "Reset": {"Fr": "Réinitialiser", "De": "Zurücksetzen", "Es": "Reiniciar"},
    "Save": {"Fr": "Enregistrer", "De": "Speichern", "Es": "Guardar"},
    "Load": {"Fr": "Charger", "De": "Laden", "Es": "Cargar"},
    "Apply": {"Fr": "Appliquer", "De": "Anwenden", "Es": "Appliquer"},
    "Update": {"Fr": "Mettre à jour", "De": "Aktualisieren", "Es": "Actualizar"},
    "Refresh": {"Fr": "Actualiser", "De": "Auffrischen", "Es": "Refrescar"},
    "Select": {"Fr": "Sélectionner", "De": "Auswählen", "Es": "Seleccionar"},
    "Search": {"Fr": "Rechercher", "De": "Suchen", "Es": "Buscar"},
    "Cancel": {"Fr": "Annuler", "De": "Abbrechen", "Es": "Cancelar"},
    "Error": {"Fr": "Erreur", "De": "Fehler", "Es": "Error"},
    "Warning": {"Fr": "Avertissement", "De": "Warnung", "Es": "Advertencia"},
    "Information": {"Fr": "Information", "De": "Information", "Es": "Información"},
    "Details": {"Fr": "Détails", "De": "Details", "Es": "Detalles"},
    "Stats": {"Fr": "Stats", "De": "Statistiken", "Es": "Estadísticas"},
    "History": {"Fr": "Historique", "De": "Historie", "Es": "Historial"},
    "Log": {"Fr": "Journal", "De": "Logbuch", "Es": "Registro"},
    "Debug": {"Fr": "Débogage", "De": "Debug", "Es": "Depuración"},
    "Label": {"Fr": "Étiquette", "De": "Beschriftung", "Es": "Etiqueta"},
    "Description": {"Fr": "Description", "De": "Beschreibung", "Es": "Descripción"},
    "Name": {"Fr": "Nom", "De": "Name", "Es": "Nombre"},
    "Type": {"Fr": "Type", "De": "Typ", "Es": "Tipo"},
    "ID": {"Fr": "ID", "De": "ID", "Es": "ID"},
    "Value": {"Fr": "Valeur", "De": "Wert", "Es": "Valor"},
    "Unit": {"Fr": "Unité", "De": "Einheit", "Es": "Unidad"},
    "Range": {"Fr": "Plage", "De": "Bereich", "Es": "Rango"},
    "Min": {"Fr": "Min", "De": "Min", "Es": "Mín"},
    "Max": {"Fr": "Max", "De": "Max", "Es": "Máx"},
    "Step": {"Fr": "Pas", "De": "Schritt", "Es": "Paso"},
    "Default": {"Fr": "Défaut", "De": "Standard", "Es": "Predeterminado"},
    "Current reading in Amperes.": {"Fr": "Lecture actuelle en Ampères.", "De": "Aktueller Messwert in Ampere.", "Es": "Lectura actual en Amperios."},
    "Current reading in Hz.": {"Fr": "Lecture actuelle en Hz.", "De": "Aktueller Messwert in Hz.", "Es": "Lectura actual en Hz."},
    "Voltage reading in Volts.": {"Fr": "Lecture de tension en Volts.", "De": "Spannungsmesswert in Volt.", "Es": "Lectura de voltaje en Voltios."},
    "Frequency reading in Hz.": {"Fr": "Lecture de fréquence en Hz.", "De": "Frequenzmesswert in Hz.", "Es": "Lectura de frecuencia en Hz."},
    "Current in Amperes.": {"Fr": "Courant en Ampères.", "De": "Strom in Ampere.", "Es": "Corriente en Amperios."},
    "Voltage in Volts.": {"Fr": "Tension en Volts.", "De": "Spannung in Volt.", "Es": "Voltaje en Voltios."},
    "Frequency in Hertz.": {"Fr": "Fréquence en Hertz.", "De": "Frequenz in Hertz.", "Es": "Frecuencia en Hercios."},
    "Power in Watts.": {"Fr": "Puissance en Watts.", "De": "Leistung in Watt.", "Es": "Potencia en Vatios."},
    "Subs": {"Fr": "Sous-groupes", "De": "Subgruppen", "Es": "Subgrupos"},
    "Aux": {"Fr": "Auxiliaires", "De": "Aux-Sende", "Es": "Auxiliares"},
    "Needle": {"Fr": "Aiguille", "De": "Nadel", "Es": "Aguja"},
    "Wink": {"Fr": "Obturateur", "De": "Verschluss", "Es": "Obturador"},
    "A block for managing all frequency-related presets.": {"Fr": "Un bloc pour gérer tous les préréglages liés à la fréquence.", "De": "Ein Block zur Verwaltung aller frequenzbezogenen Voreinstellungen.", "Es": "Un bloque para gestionar todos los preajustes relacionados con la frecuencia."},
    "A block for managing center and span frequency settings.": {"Fr": "Un bloc pour gérer les paramètres de fréquence centrale et d'intervalle.", "De": "Ein Block zur Verwaltung der Mittenfrequenz- und Spanneneinstellungen.", "Es": "Un bloque para gestionar los ajustes de frecuencia central e intervalo."},
    "A block for managing global marker settings.": {"Fr": "Un bloc pour gérer les paramètres globaux des marqueurs.", "De": "Ein Block zur Verwaltung globaler Marker-Einstellungen.", "Es": "Un bloque para gestionar los ajustes globales de los marcadores."},
    "A block for managing start and stop frequency settings.": {"Fr": "Un bloc pour gérer les paramètres de fréquence de début et de fin.", "De": "Ein Block zur Verwaltung der Start- und Stoppfrequenzeinstellungen.", "Es": "Un bloque para gestionar los ajustes de frecuencia de inicio y fin."},
    "A block for managing the continuous sweep settings.": {"Fr": "Un bloc pour gérer les paramètres de balayage continu.", "De": "Ein Block zur Verwaltung der Einstellungen für den kontinuierlichen Sweep.", "Es": "Un bloque para gestionar los ajustes del barrido continuo."},
    "A block for managing trace averaging settings.": {"Fr": "Un bloc pour gérer les paramètres de moyennage de trace.", "De": "Ein Block zur Verwaltung der Trace-Mittelungseinstellungen.", "Es": "Un bloque para gestionar los ajustes de promediado de trazas."},
    "A quick pass through the spectrum, ideal for fast-changing signals.": {"Fr": "Un passage rapide dans le spectre, idéal pour les signaux à changement rapide.", "De": "Ein schneller Durchlauf durch das Spektrum, ideal für sich schnell ändernde Signale.", "Es": "Un paso rápido por el espectro, ideal para señales de cambio rápido."},
    "A slow crawl. Good for very detailed analysis of continuous signals and filtering out transient noise.": {"Fr": "Un balayage lent. Idéal pour une analyse très détaillée des signaux continus et pour filtrer le bruit transitoire.", "De": "Ein langsames Kriechen. Gut für sehr detaillierte Analysen von kontinuierlichen Signalen und zum Filtern von Einschwinggeräuschen.", "Es": "Un gateo lento. Bueno para análisis muy detallados de señales continuas y filtrado de ruido transitorio."},
    "A very broad span for finding signals over a large frequency range.": {"Fr": "Une portée très large pour trouver des signaux sur une large gamme de fréquences.", "De": "Eine sehr breite Spanne zum Finden von Signalen über einen großen Frequenzbereich.", "Es": "Un intervalo muy amplio para encontrar señales en un rango de frecuencias grande."},
    "A/sec": {"Fr": "A/sec", "De": "A/Sek", "Es": "A/seg"},
    "AC, DC, GND": {"Fr": "AC, DC, GND", "De": "AC, DC, GND", "Es": "CA, CC, GND"},
    "AM OFF": {"Fr": "AM OFF", "De": "AM AUS", "Es": "AM DES"},
    "AM ON": {"Fr": "AM ON", "De": "AM EIN", "Es": "AM ENC"},
    "AM/FM/Pulse Config": {"Fr": "Config AM/FM/Impulsion", "De": "AM/FM/Puls-Konfig", "Es": "Config AM/FM/Pulso"},
    "APPLy Macro Commands": {"Fr": "Appliquer les commandes macro", "De": "Makrobefehle anwenden", "Es": "Aplicar comandos macro"},
    "APPLy Readbacks": {"Fr": "Appliquer les lectures", "De": "Rücklesewerte anwenden", "Es": "Aplicar lecturas"},
    "APPLy Subsystem": {"Fr": "Appliquer le sous-système", "De": "Subsystem anwenden", "Es": "Aplicar subsistema"},
    "AUTO": {"Fr": "AUTO", "De": "AUTO", "Es": "AUTO"},
    "AUTO or NORMal": {"Fr": "AUTO ou NORMAL", "De": "AUTO oder NORMAL", "Es": "AUTO o NORMAL"},
    "AUTO, NORMal, SINGle": {"Fr": "AUTO, NORMAL, UNIQUE", "De": "AUTO, NORMAL, EINZEL", "Es": "AUTO, NORMAL, ÚNICO"},
    "AUTOSCALE": {"Fr": "ÉCHELLE AUTO", "De": "AUTOSCALE", "Es": "ESCALA AUTO"},
    "Acquisition": {"Fr": "Acquisition", "De": "Erfassung", "Es": "Adquisición"},
    "Acquisition Settings": {"Fr": "Paramètres d'acquisition", "De": "Erfassungseinstellungen", "Es": "Ajustes de adquisición"},
    "Actions and Toggles": {"Fr": "Actions et bascules", "De": "Aktionen und Umschalter", "Es": "Acciones y conmutadores"},
    "All Markers OFF": {"Fr": "Tous les marqueurs OFF", "De": "Alle Marker AUS", "Es": "Todos los marcadores DES"},
    "All Markers ON": {"Fr": "Tous les marqueurs ON", "De": "Alle Marker EIN", "Es": "Todos los marcadores ENC"},
    "Amplitude in Vpp": {"Fr": "Amplitude en Vpp", "De": "Amplitude in Vss", "Es": "Amplitud en Vpp"},
    "Amps": {"Fr": "Amps", "De": "Ampere", "Es": "Amperios"},
    "Analog Signal Generator": {"Fr": "Générateur de signaux analogiques", "De": "Analoger Signalgenerator", "Es": "Generador de señales analógicas"},
    "Attenuation (dB)": {"Fr": "Atténuation (dB)", "De": "Dämpfung (dB)", "Es": "Atenuación (dB)"},
    "Audio is muted.": {"Fr": "L'audio est coupé.", "De": "Audio ist stummgeschaltet.", "Es": "El audio está silenciado."},
    "Audio is unmuted.": {"Fr": "L'audio n'est pas coupé.", "De": "Audio ist nicht stummgeschaltet.", "Es": "El audio no está silenciado."},
    "Auto Atten OFF": {"Fr": "Atténuation auto OFF", "De": "Auto-Dämpfung AUS", "Es": "Atenuación auto DES"},
    "Auto Atten ON": {"Fr": "Atténuation auto ON", "De": "Auto-Dämpfung EIN", "Es": "Atenuación auto ENC"},
    "Auto OFF": {"Fr": "Auto OFF", "De": "Auto AUS", "Es": "Auto DES"},
    "Auto ON": {"Fr": "Auto ON", "De": "Auto EIN", "Es": "Auto ENC"},
    "Avg": {"Fr": "Moy", "De": "Mittel", "Es": "Prom"},
    "BW Limit": {"Fr": "Limite BP", "De": "BW-Limit", "Es": "Límite AB"},
    "Bandwidth Limit": {"Fr": "Limite de largeur de bande", "De": "Bandbreitenbegrenzung", "Es": "Límite de ancho de banda"},
    "Battery Protection": {"Fr": "Protection de batterie", "De": "Batterieschutz", "Es": "Protección de batería"},
    "Brisk": {"Fr": "Vif", "De": "Flott", "Es": "Enérgico"},
    "Broadband": {"Fr": "Large bande", "De": "Breitband", "Es": "Banda ancha"},
    "CC / CV / CR": {"Fr": "CC / CV / CR", "De": "CC / CV / CR", "Es": "CC / CV / CR"},
    "CONSTANT CURRENT": {"Fr": "COURANT CONSTANT", "De": "KONSTANTSTROM", "Es": "CORRIENTE CONSTANTE"},
    "CONSTANT POWER": {"Fr": "PUISSANCE CONSTANTE", "De": "KONSTANTPOTENZ", "Es": "POTENCIA CONSTANTE"},
    "Center Freq": {"Fr": "Fréq centrale", "De": "Mittenfreq", "Es": "Frec central"},
    "Center Frequency (Hz)": {"Fr": "Fréquence centrale (Hz)", "De": "Mittenfrequenz (Hz)", "Es": "Frecuencia central (Hz)"},
    "Ch1 Coupling": {"Fr": "Couplage Ch1", "De": "Ch1-Kopplung", "Es": "Acoplamiento Ch1"},
    "Ch1 Scale": {"Fr": "Échelle Ch1", "De": "Ch1-Skala", "Es": "Escala Ch1"},
    "Clear Display": {"Fr": "Effacer l'affichage", "De": "Anzeige löschen", "Es": "Borrar pantalla"},
    "Crazy Slow": {"Fr": "Extrêmement lent", "De": "Wahnsinnig langsam", "Es": "Locamente lento"},
    "Crystal Clear": {"Fr": "Cristallin", "De": "Glasklar", "Es": "Cristalino"},
    "Current (A)": {"Fr": "Courant (A)", "De": "Strom (A)", "Es": "Corriente (A)"},
    "Current Limit": {"Fr": "Limite de courant", "De": "Strombegrenzung", "Es": "Límite de corriente"},
    "Cursor Settings": {"Fr": "Paramètres du curseur", "De": "Cursoreinstellungen", "Es": "Ajustes del cursor"},
    "DC Electronic Load Control Panel": {"Fr": "Panneau de contrôle de charge électronique CC", "De": "Bedienfeld für elektronische DC-Last", "Es": "Panel de control de carga electrónica de CC"},
    "Default unit is Vpp": {"Fr": "L'unité par défaut est Vpp", "De": "Standardeinheit ist Vss", "Es": "La unidad predeterminada es Vpp"},
    "Delay time in seconds.": {"Fr": "Temps de délai en secondes.", "De": "Verzögerungszeit in Sekunden.", "Es": "Tiempo de retraso en segundos."},
    "Deliberate": {"Fr": "Délibéré", "De": "Bedächtig", "Es": "Deliberado"},
    "Depth %": {"Fr": "Profondeur %", "De": "Tiefe %", "Es": "Profundidad %"},
    "Device is operational.": {"Fr": "L'appareil est opérationnel.", "De": "Gerät ist betriebsbereit.", "Es": "El dispositivo está operativo."},
    "Duty Cycle (%)": {"Fr": "Cycle de service (%)", "De": "Tastverhältnis (%)", "Es": "Ciclo de trabajo (%)"},
    "Edge Trigger Configuration": {"Fr": "Configuration du déclenchement par front", "De": "Flankentrigger-Konfiguration", "Es": "Configuración de disparo por flanco"},
    "Execute Preset Load": {"Fr": "Exécuter le chargement du préréglage", "De": "Voreinstellung laden ausführen", "Es": "Ejecutar carga de preajuste"},
    "Format": {"Fr": "Format", "De": "Format", "Es": "Formato"},
    "Freq Span": {"Fr": "Intervalle de fréq", "De": "Freq-Spanne", "Es": "Intervalo de frec"},
    "Frequency actuator.": {"Fr": "Actionneur de fréquence.", "De": "Frequenz-Aktor.", "Es": "Actuador de frecuencia."},
    "Frequency sensor.": {"Fr": "Capteur de fréquence.", "De": "Frequenz-Sensor.", "Es": "Sensor de frecuencia."},
    "Glacial": {"Fr": "Glacial", "De": "Glazial", "Es": "Glacial"},
    "Hz": {"Fr": "Hz", "De": "Hz", "Es": "Hz"},
    "ID String": {"Fr": "Chaîne ID", "De": "ID-String", "Es": "Cadena de ID"},
    "Input State": {"Fr": "État de l'entrée", "De": "Eingangszustand", "Es": "Estado de la entrada"},
    "Instrument ID": {"Fr": "ID de l'instrument", "De": "Instrumenten-ID", "Es": "ID del instrumento"},
    "Invert": {"Fr": "Inverser", "De": "Invertieren", "Es": "Invertir"},
    "Level in Volts": {"Fr": "Niveau en Volts", "De": "Pegel in Volt", "Es": "Nivel en Voltios"},
    "Light Filter": {"Fr": "Filtre léger", "De": "Leichter Filter", "Es": "Filtro ligero"},
    "Live Measurements": {"Fr": "Mesures en direct", "De": "Live-Messungen", "Es": "Medidas en vivo"},
    "Log Files Path": {"Fr": "Chemin des fichiers journaux", "De": "Pfad zu Logdateien", "Es": "Ruta de archivos de registro"},
    "Math OFF": {"Fr": "Math OFF", "De": "Math AUS", "Es": "Math DES"},
    "Math ON": {"Fr": "Math ON", "De": "Math EIN", "Es": "Math ENC"},
    "None Selected": {"Fr": "Aucun sélectionné", "De": "Keine ausgewählt", "Es": "Ninguno seleccionado"},
    "Notes": {"Fr": "Notes", "De": "Notizen", "Es": "Notas"},
    "OFF": {"Fr": "OFF", "De": "AUS", "Es": "DES"},
    "ON": {"Fr": "ON", "De": "EIN", "Es": "ENC"},
    "Output OFF": {"Fr": "Sortie OFF", "De": "Ausgang AUS", "Es": "Salida DES"},
    "Output ON": {"Fr": "Sortie ON", "De": "Ausgang EIN", "Es": "Salida ENC"},
    "Period": {"Fr": "Période", "De": "Periode", "Es": "Periodo"},
    "Phase": {"Fr": "Phase", "De": "Phase", "Es": "Fase"},
    "Points": {"Fr": "Points", "De": "Punkte", "Es": "Puntos"},
    "Pos": {"Fr": "Pos", "De": "Pos", "Es": "Pos"},
    "Preamp ON": {"Fr": "Préampli ON", "De": "Vorverstärker EIN", "Es": "Preampli ENC"},
    "Preamp OFF": {"Fr": "Préampli OFF", "De": "Vorverstärker AUS", "Es": "Preampli DES"},
    "RMS.": {"Fr": "RMS.", "De": "RMS.", "Es": "RMS."},
    "RUN": {"Fr": "EXEC", "De": "AUSFÜHREN", "Es": "EJEC"},
    "Sample Rate": {"Fr": "Taux d'échantillonnage", "De": "Abtastrate", "Es": "Frecuencia de muestreo"},
    "Scientific Grade": {"Fr": "Qualité scientifique", "De": "Wissenschaftliche Qualität", "Es": "Grado científico"},
    "Slope": {"Fr": "Pente", "De": "Flanke", "Es": "Pendiente"},
    "Steady": {"Fr": "Stable", "De": "Stabil", "Es": "Estable"},
    "Steady Hands": {"Fr": "Mains stables", "De": "Ruhige Hände", "Es": "Manos firmes"},
    "Time": {"Fr": "Temps", "De": "Zeit", "Es": "Tiempo"},
    "Time/Div": {"Fr": "Temps/Div", "De": "Zeit/Div", "Es": "Tiempo/Div"},
    "Units": {"Fr": "Unités", "De": "Einheiten", "Es": "Unidades"},
    "Vpp": {"Fr": "Vpp", "De": "Vss", "Es": "Vpp"},
    "Vrms": {"Fr": "Vrms", "De": "Veff", "Es": "Vrms"},
    "Voltage Set": {"Fr": "Réglage de tension", "De": "Spannungseinstellung", "Es": "Ajuste de voltaje"},
    "Wait": {"Fr": "Attendre", "De": "Warten", "Es": "Esperar"},
    "Waveform Configuration": {"Fr": "Configuration de la forme d'onde", "De": "Wellenform-Konfiguration", "Es": "Configuración de forma de onda"},
    "Zoom Window Settings": {"Fr": "Paramètres de la fenêtre de zoom", "De": "Zoom-Fenster-Einstellungen", "Es": "Ajustes de la ventana de zoom"},
    "dB": {"Fr": "dB", "De": "dB", "Es": "dB"},
    "{{channel_name}}": {"Fr": "{{channel_name}}", "De": "{{channel_name}}", "Es": "{{channel_name}}"},
    "{{description}}": {"Fr": "{{description}}", "De": "{{description}}", "Es": "{{description}}"},
}

def translate_text(text, target_lang):
    if not text:
        return text

    # Check for technical context first
    if text in TECHNICAL_CONTEXT:
        return TECHNICAL_CONTEXT[text].get(target_lang, text)

    # Check for full mapping
    if text in TRANSLATIONS:
        return TRANSLATIONS[text].get(target_lang, text)

    # Handle placeholders: do not translate inside {{ }}
    # We split by placeholders, translate the parts, and reassemble.
    parts = re.split(r"(\{\{.*?\}\})", text)
    translated_parts = []
    for part in parts:
        if part.startswith("{{") and part.endswith("}}"):
            translated_parts.append(part)
        else:
            # For simplicity, if part is a known string, translate it.
            # Otherwise, use some heuristics or just the original part.
            if part in TRANSLATIONS:
                translated_parts.append(TRANSLATIONS[part].get(target_lang, part))
            else:
                # Basic heuristic for common words if they are part of a larger sentence
                # In a real scenario, we would use a proper translation engine.
                # Here we will try to replace some common words if they appear.
                t_part = part
                for en_w, langs in TRANSLATIONS.items():
                    if len(en_w) > 3 and en_w in t_part:
                        t_part = t_part.replace(en_w, langs.get(target_lang, en_w))
                translated_parts.append(t_part)

    return "".join(translated_parts)

def process_object(obj):
    if isinstance(obj, dict):
        if "En" in obj:
            en_val = obj["En"]
            for lang in ["Fr", "De", "Es"]:
                # If the key doesn't exist or is identical to En (implying unlocalized), we update it.
                if lang not in obj or obj[lang] == en_val or obj[lang] == "":
                    obj[lang] = translate_text(en_val, lang)
        for k, v in obj.items():
            process_object(v)
    elif isinstance(obj, list):
        for item in obj:
            process_object(item)

# List of files to process
FILES = [
"oaGui/Assets/Assets/left_50/top_100/8_LCR/10_YAK/1_4263A/100_Connection/Connection_6060B.json",
"oaGui/Assets/Assets/left_50/top_100/8_LCR/10_YAK/1_4263A/10_SYSTem/system.json",
"oaGui/Assets/Assets/left_50/top_100/8_LCR/10_YAK/1_4263A/2_Capacitance/Capacitance.json",
"oaGui/Assets/Assets/left_50/top_100/8_LCR/10_YAK/1_4263A/1_Impedance/Impedance.json",
"oaGui/Assets/Assets/left_50/top_100/8_LCR/10_YAK/1_4263A/3_Resistance/Resistance.json",
"oaGui/Assets/Assets/left_50/top_100/8_LCR/1_Instrument/LCR.json",
"oaGui/Assets/Assets/left_50/top_100/9_Distortion/10_YAK/1_Porta_one/2_Signal_Generator/yak_Distortion_Signal_gen.json",
"oaGui/Assets/Assets/left_50/top_100/9_Distortion/10_YAK/1_Porta_one/2_Signal_Generator/temp_norm_gui_yak.json",
"oaGui/Assets/Assets/left_50/top_100/9_Distortion/10_YAK/1_Porta_one/0_System/yak_Distortion_System.json",
"oaGui/Assets/Assets/left_50/top_100/9_Distortion/10_YAK/1_Porta_one/0_System/temp_norm_gui_yak.json",
"oaGui/Assets/Assets/left_50/top_100/9_Distortion/10_YAK/1_Porta_one/100_Connection/Connection_Porta_one.json",
"oaGui/Assets/Assets/left_50/top_100/9_Distortion/10_YAK/1_Porta_one/2_Channel_AB/yak_Distortion_Channel_AB.json",
"oaGui/Assets/Assets/left_50/top_100/9_Distortion/10_YAK/1_Porta_one/2_Channel_AB/temp_norm_gui_yak.json",
"oaGui/Assets/Assets/left_50/top_100/9_Distortion/10_YAK/1_Porta_one/0_Measurements/temp_norm_gui_yak.json",
"oaGui/Assets/Assets/left_50/top_100/9_Distortion/10_YAK/1_Porta_one/0_Measurements/yak_Distortion_Measurements.json",
"oaGui/Assets/Assets/left_50/top_100/9_Distortion/10_YAK/1_Porta_one/1_Channel_A/yak_Distortion_Channel_A.json",
"oaGui/Assets/Assets/left_50/top_100/9_Distortion/10_YAK/1_Porta_one/1_Channel_A/temp_norm_gui_yak.json",
"oaGui/Assets/Assets/left_50/top_100/9_Distortion/10_YAK/1_Porta_one/4_Digital/yak_Distortion_Digital.json",
"oaGui/Assets/Assets/left_50/top_100/9_Distortion/10_YAK/1_Porta_one/4_Digital/temp_norm_gui_yak.json",
"oaGui/Assets/Assets/left_50/top_100/9_Distortion/10_YAK/1_Porta_one/1_Channel_B/yak_Distortion_Channel_B.json",
"oaGui/Assets/Assets/left_50/top_100/9_Distortion/10_YAK/1_Porta_one/1_Channel_B/temp_norm_gui_yak.json",
"oaGui/Assets/Assets/left_50/top_100/9_Distortion/10_YAK/2_HP_8903B/100_Connection/Connection.json",
"oaGui/Assets/Assets/left_50/top_100/9_Distortion/1_Instrument/dc_load.json",
"oaGui/Assets/Assets/left_50/top_100/9_Distortion/1_Instrument/distortion.json",
"oaGui/Assets/Assets/left_50/top_100/7_Load/10_YAK/1_6060B/11_Common/common.json",
"oaGui/Assets/Assets/left_50/top_100/7_Load/10_YAK/1_6060B/6_RESistance/resistance.json",
"oaGui/Assets/Assets/left_50/top_100/7_Load/10_YAK/1_6060B/1_MEASure/measure.json",
"oaGui/Assets/Assets/left_50/top_100/7_Load/10_YAK/1_6060B/7_TRANsient/transient.json",
"oaGui/Assets/Assets/left_50/top_100/7_Load/10_YAK/1_6060B/9_STATus/status.json",
"oaGui/Assets/Assets/left_50/top_100/7_Load/10_YAK/1_6060B/8_TRIGger/trigger.json",
"oaGui/Assets/Assets/left_50/top_100/7_Load/10_YAK/1_6060B/100_Connection/Connection_6060B.json",
"oaGui/Assets/Assets/left_50/top_100/7_Load/10_YAK/1_6060B/3_INPut/input.json",
"oaGui/Assets/Assets/left_50/top_100/7_Load/10_YAK/1_6060B/10_SYSTem/system.json",
"oaGui/Assets/Assets/left_50/top_100/7_Load/10_YAK/1_6060B/4_CURRent/current.json",
"oaGui/Assets/Assets/left_50/top_100/7_Load/10_YAK/1_6060B/5_VOLTage/voltage.json",
"oaGui/Assets/Assets/left_50/top_100/7_Load/10_YAK/1_6060B/2_MODE/mode.json",
"oaGui/Assets/Assets/left_50/top_100/7_Load/10_YAK/1_6060B/_Legacy_Commands/yak_OLD.json",
"oaGui/Assets/Assets/left_50/top_100/7_Load/1_Instrument_B/dc_load.json",
"oaGui/Assets/Assets/left_50/top_100/7_Load/1_Instrument/dc_load.json",
"oaGui/Assets/Assets/left_50/top_100/7_Load/1_Instrument_A/dc_load.json",
"oaGui/Assets/Assets/left_50/top_100/3_Generator/1_Instrument_1/instrument_signal_Generator.json",
"oaGui/Assets/Assets/left_50/top_100/3_Generator/10_YAK/1_33210A/5_BURSt/BURSt.json",
"oaGui/Assets/Assets/left_50/top_100/3_Generator/10_YAK/1_33210A/2_OUTPut/OUTPut.json",
"oaGui/Assets/Assets/left_50/top_100/3_Generator/10_YAK/1_33210A/6_Modulation/Modulation.json",
"oaGui/Assets/Assets/left_50/top_100/3_Generator/10_YAK/1_33210A/3_SOURce/SOURce.json",
"oaGui/Assets/Assets/left_50/top_100/3_Generator/10_YAK/1_33210A/100_Connection/Connection_33210A.json",
"oaGui/Assets/Assets/left_50/top_100/3_Generator/10_YAK/1_33210A/4_PULSe/PULSe.json",
"oaGui/Assets/Assets/left_50/top_100/3_Generator/10_YAK/1_33210A/7_System/System.json",
"oaGui/Assets/Assets/left_50/top_100/3_Generator/10_YAK/1_33210A/1_APPLy/APPLy.json",
"oaGui/Assets/Assets/left_50/top_100/3_Generator/10_YAK/1_33210A/_Legacy_Commands/yak_Signal_gen_OLD.json",
"oaGui/Assets/Assets/left_50/top_100/3_Generator/10_YAK/1_33210A/_Legacy_Commands/temp_norm_gui_yak_Signal_gen_OLD.json",
"oaGui/Assets/Assets/left_50/top_100/3_Generator/10_YAK/1_33220A/5_BURSt/BURSt.json",
"oaGui/Assets/Assets/left_50/top_100/3_Generator/10_YAK/1_33220A/2_OUTPut/OUTPut.json",
"oaGui/Assets/Assets/left_50/top_100/3_Generator/10_YAK/1_33220A/6_Modulation/Modulation.json",
"oaGui/Assets/Assets/left_50/top_100/3_Generator/10_YAK/1_33220A/3_SOURce/SOURce.json",
"oaGui/Assets/Assets/left_50/top_100/3_Generator/10_YAK/1_33220A/100_Connection/Connection_33220A.json",
"oaGui/Assets/Assets/left_50/top_100/3_Generator/10_YAK/1_33220A/4_PULSe/PULSe.json",
"oaGui/Assets/Assets/left_50/top_100/3_Generator/10_YAK/1_33220A/7_System/System.json",
"oaGui/Assets/Assets/left_50/top_100/3_Generator/10_YAK/1_33220A/1_APPLy/APPLy.json",
"oaGui/Assets/Assets/left_50/top_100/3_Generator/10_YAK/1_33220A/_Legacy_Commands/yak_Signal_gen_OLD.json",
"oaGui/Assets/Assets/left_50/top_100/3_Generator/10_YAK/1_33220A/_Legacy_Commands/temp_norm_gui_yak_Signal_gen_OLD.json",
"oaGui/Assets/Assets/left_50/top_100/3_Generator/1_Instrument_2/instrument_signal_Generator.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/10_YAK/1_54641D/2_CHANnel/CHANnel_OLD.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/10_YAK/1_54641D/2_CHANnel/2_Channel_2/CHANnel.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/10_YAK/1_54641D/2_CHANnel/1_Channel_1/CHANnel.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/10_YAK/1_54641D/8_MARKer/MARKer.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/10_YAK/1_54641D/3_DIGital/DIGital.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/10_YAK/1_54641D/100_Connection/Connection_54641D.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/10_YAK/1_54641D/0_Root/Root.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/10_YAK/1_54641D/9_FUNCtion/FUNCtion.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/10_YAK/1_54641D/5_TRIGger/TRIGger.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/10_YAK/1_54641D/1_ACQuire/ACQuire.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/10_YAK/1_54641D/10_SYSTem/SYSTem.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/10_YAK/1_54641D/6_WAVeform/WAVeform.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/10_YAK/1_54641D/4_TIMebase/TIMebase.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/10_YAK/1_54641D/_Legacy_Commands/5_Math_FFT/yak_Osilliscope_Math_FFT.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/10_YAK/1_54641D/_Legacy_Commands/2_Trigger/yak_Osilliscope_Trigger.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/10_YAK/1_54641D/_Legacy_Commands/0_System/yak_Osilliscope_system.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/10_YAK/1_54641D/_Legacy_Commands/3_Channel_2/yak_Osilliscope_CH2.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/10_YAK/1_54641D/_Legacy_Commands/1_Time/temp_norm_gui_yak_Osilliscope.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/10_YAK/1_54641D/_Legacy_Commands/1_Time/yak_Osilliscope_time.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/10_YAK/1_54641D/_Legacy_Commands/3_Channel_1/yak_Osilliscope_CH1.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/10_YAK/1_54641D/7_MEASure/MEASure.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/10_YAK/3_DS1104Z/2_CHANnel/CHANnel.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/10_YAK/3_DS1104Z/0_System/yak_Rigol_Osilliscope_system.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/10_YAK/3_DS1104Z/0_System/rigol_system_commands.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/10_YAK/3_DS1104Z/100_Connection/Connection_DS1104Z.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/10_YAK/3_DS1104Z/1_Commands/2_CHANnel/4_Channel_4/CHANnel.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/10_YAK/3_DS1104Z/1_Commands/2_CHANnel/2_Channel_2/CHANnel.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/10_YAK/3_DS1104Z/1_Commands/2_CHANnel/1_Channel_1/CHANnel.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/10_YAK/3_DS1104Z/1_Commands/2_CHANnel/3_Channel_3/CHANnel.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/10_YAK/3_DS1104Z/1_Commands/0_Root/Root.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/10_YAK/3_DS1104Z/1_Commands/5_TRIGger/TRIGger.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/10_YAK/3_DS1104Z/1_Commands/6_WAVeform/WAVeform.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/10_YAK/3_DS1104Z/1_Commands/4_TIMebase/TIMebase.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/10_YAK/3_DS1104Z/1_Commands/7_MEASure/MEASure.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/10_YAK/3_DS1104Z/0_Root/Root.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/10_YAK/3_DS1104Z/5_TRIGger/TRIGger.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/10_YAK/3_DS1104Z/6_WAVeform/WAVeform.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/10_YAK/3_DS1104Z/4_TIMebase/TIMebase.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/10_YAK/3_DS1104Z/_Legacy_Commands/4_FFT/yak_Rigol_Osilliscope_FFT.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/10_YAK/3_DS1104Z/_Legacy_Commands/3_Channel_4/yak_Rigol_Osilliscope_Channel_4.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/10_YAK/3_DS1104Z/_Legacy_Commands/3_Channel_4/rigol_channel4_commands.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/10_YAK/3_DS1104Z/_Legacy_Commands/2_Trigger/yak_Rigol_Osilliscope_trigger.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/10_YAK/3_DS1104Z/_Legacy_Commands/2_Trigger/rigol_trigger_commands.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/10_YAK/3_DS1104Z/_Legacy_Commands/3_Channel_3/rigol_channel3_commands.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/10_YAK/3_DS1104Z/_Legacy_Commands/3_Channel_3/yak_Rigol_Osilliscope_Channel_3.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/10_YAK/3_DS1104Z/_Legacy_Commands/3_Channel_2/rigol_channel2_commands.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/10_YAK/3_DS1104Z/_Legacy_Commands/3_Channel_2/yak_Rigol_Osilliscope_Channel_2.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/10_YAK/3_DS1104Z/_Legacy_Commands/1_Time/yak_Rigol_Osilliscope_Time.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/10_YAK/3_DS1104Z/_Legacy_Commands/1_Time/rigol_timebase_commands.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/10_YAK/3_DS1104Z/_Legacy_Commands/3_Channel_1/rigol_channel1_commands.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/10_YAK/3_DS1104Z/_Legacy_Commands/3_Channel_1/yak_Rigol_Osilliscope_Channel_1.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/10_YAK/3_DS1104Z/7_MEASure/MEASure.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/2_Instrument_1/2_Channel_1_and_2/instrument_oscilloscope_ch12.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/2_Instrument_1/1_Channel_1/instrument_oscilloscope_ch1.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/2_Instrument_1/3_Math/instrument_oscilloscope_math.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/2_Instrument_1/1_Channel_2/instrument_oscilloscope_ch2.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/2_Instrument_2/2_Channel_1_and_2/instrument_oscilloscope_ch12.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/2_Instrument_2/1_Channel_1/instrument_oscilloscope_ch1.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/2_Instrument_2/3_Math/instrument_oscilloscope_math.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/2_Instrument_2/1_Channel_2/instrument_oscilloscope_ch2.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/2_Instrument_Rigol/1_Channel_3/instrument_oscilloscope_ch3.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/2_Instrument_Rigol/1_Channel_4/instrument_oscilloscope_ch4.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/2_Instrument_Rigol/1_Channel_1/instrument_oscilloscope_ch1.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/2_Instrument_Rigol/3_Math/instrument_oscilloscope_math.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/2_Instrument_Rigol/1_Channel_2/instrument_oscilloscope_ch2.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/2_Instrument_Rigol/instrument_oscilloscope.json",
"oaGui/Assets/Assets/left_50/top_100/2_Oscilloscope/2_Instrument_Rigol/2_Channel_1_2_3_4/instrument_oscilloscope_ch1234.json",
"oaGui/Assets/Assets/left_50/top_100/10_Console/3_17_24/Console_17_24.json",
"oaGui/Assets/Assets/left_50/top_100/10_Console/2_9_16/Console_9_16.json",
"oaGui/Assets/Assets/left_50/top_100/10_Console/1_1_8/Console_1_8.json",
"oaGui/Assets/Assets/left_50/top_100/10_Console/3_25_32/Console_25_32.json",
"oaGui/Assets/Assets/left_50/top_100/5_Power/10_YAK/2_66104A/4_MEASure/measure.json",
"oaGui/Assets/Assets/left_50/top_100/5_Power/10_YAK/2_66104A/7_STATus/status.json",
"oaGui/Assets/Assets/left_50/top_100/5_Power/10_YAK/2_66104A/6_SYSTem/system.json",
"oaGui/Assets/Assets/left_50/top_100/5_Power/10_YAK/2_66104A/100_Connection/Connection_66104A.json",
"oaGui/Assets/Assets/left_50/top_100/5_Power/10_YAK/2_66104A/3_OUTPut/output.json",
"oaGui/Assets/Assets/left_50/top_100/5_Power/10_YAK/2_66104A/8_Common/common.json",
"oaGui/Assets/Assets/left_50/top_100/5_Power/10_YAK/2_66104A/5_TRIGger/trigger.json",
"oaGui/Assets/Assets/left_50/top_100/5_Power/10_YAK/2_66104A/2_SOURce/source.json",
"oaGui/Assets/Assets/left_50/top_100/5_Power/10_YAK/2_66104A/1_INSTrument/instrument.json",
"oaGui/Assets/Assets/left_50/top_100/5_Power/10_YAK/2_66104A/_Legacy_Commands/temp_norm_gui_yak_PSU.json",
"oaGui/Assets/Assets/left_50/top_100/5_Power/10_YAK/2_66104A/_Legacy_Commands/yak_PSU_OLD.json",
"oaGui/Assets/Assets/left_50/top_100/5_Power/10_YAK/2_66102A/4_MEASure/measure.json",
"oaGui/Assets/Assets/left_50/top_100/5_Power/10_YAK/2_66102A/7_STATus/status.json",
"oaGui/Assets/Assets/left_50/top_100/5_Power/10_YAK/2_66102A/6_SYSTem/system.json",
"oaGui/Assets/Assets/left_50/top_100/5_Power/10_YAK/2_66102A/100_Connection/Connection_66102A.json",
"oaGui/Assets/Assets/left_50/top_100/5_Power/10_YAK/2_66102A/3_OUTPut/output.json",
"oaGui/Assets/Assets/left_50/top_100/5_Power/10_YAK/2_66102A/8_Common/common.json",
"oaGui/Assets/Assets/left_50/top_100/5_Power/10_YAK/2_66102A/5_TRIGger/trigger.json",
"oaGui/Assets/Assets/left_50/top_100/5_Power/10_YAK/2_66102A/2_SOURce/source.json",
"oaGui/Assets/Assets/left_50/top_100/5_Power/10_YAK/2_66102A/1_INSTrument/instrument.json",
"oaGui/Assets/Assets/left_50/top_100/5_Power/10_YAK/2_66102A/_Legacy_Commands/temp_norm_gui_yak_PSU.json",
"oaGui/Assets/Assets/left_50/top_100/5_Power/10_YAK/2_66102A/_Legacy_Commands/yak_PSU_OLD.json",
"oaGui/Assets/Assets/left_50/top_100/5_Power/10_YAK/2_66103A/4_MEASure/measure.json",
"oaGui/Assets/Assets/left_50/top_100/5_Power/10_YAK/2_66103A/7_STATus/status.json",
"oaGui/Assets/Assets/left_50/top_100/5_Power/10_YAK/2_66103A/6_SYSTem/system.json",
"oaGui/Assets/Assets/left_50/top_100/5_Power/10_YAK/2_66103A/100_Connection/Connection_66103A.json",
"oaGui/Assets/Assets/left_50/top_100/5_Power/10_YAK/2_66103A/3_OUTPut/output.json",
"oaGui/Assets/Assets/left_50/top_100/5_Power/10_YAK/2_66103A/8_Common/common.json",
"oaGui/Assets/Assets/left_50/top_100/5_Power/10_YAK/2_66103A/5_TRIGger/trigger.json",
"oaGui/Assets/Assets/left_50/top_100/5_Power/10_YAK/2_66103A/2_SOURce/source.json",
"oaGui/Assets/Assets/left_50/top_100/5_Power/10_YAK/2_66103A/1_INSTrument/instrument.json",
"oaGui/Assets/Assets/left_50/top_100/5_Power/10_YAK/2_66103A/_Legacy_Commands/temp_norm_gui_yak_PSU.json",
"oaGui/Assets/Assets/left_50/top_100/5_Power/10_YAK/2_66103A/_Legacy_Commands/yak_PSU_OLD.json",
"oaGui/Assets/Assets/left_50/top_100/5_Power/10_YAK/1_66101A/4_MEASure/measure.json",
"oaGui/Assets/Assets/left_50/top_100/5_Power/10_YAK/1_66101A/7_STATus/status.json",
"oaGui/Assets/Assets/left_50/top_100/5_Power/10_YAK/1_66101A/6_SYSTem/system.json",
"oaGui/Assets/Assets/left_50/top_100/5_Power/10_YAK/1_66101A/100_Connection/Connection_66101A.json",
"oaGui/Assets/Assets/left_50/top_100/5_Power/10_YAK/1_66101A/3_OUTPut/output.json",
"oaGui/Assets/Assets/left_50/top_100/5_Power/10_YAK/1_66101A/8_Common/common.json",
"oaGui/Assets/Assets/left_50/top_100/5_Power/10_YAK/1_66101A/5_TRIGger/trigger.json",
"oaGui/Assets/Assets/left_50/top_100/5_Power/10_YAK/1_66101A/2_SOURce/source.json",
"oaGui/Assets/Assets/left_50/top_100/5_Power/10_YAK/1_66101A/1_INSTrument/instrument.json",
"oaGui/Assets/Assets/left_50/top_100/5_Power/10_YAK/1_66101A/_Legacy_Commands/yak_PSU_OLD.json",
"oaGui/Assets/Assets/left_50/top_100/5_Power/1_Instrument/2_All_8/psu_eight.json",
"oaGui/Assets/Assets/left_50/top_100/5_Power/1_Instrument/1_One_instrument/psu_one.json",
"oaGui/Assets/Assets/left_50/top_100/5_Power/1_Instrument/1_four_instruments/psu_four.json",
"oaGui/Assets/Assets/left_50/top_100/5_Power/2_Modules/1_Module_5/psu.json",
"oaGui/Assets/Assets/left_50/top_100/5_Power/2_Modules/1_Module_6/psu.json",
"oaGui/Assets/Assets/left_50/top_100/5_Power/2_Modules/1_Module_2/psu.json",
"oaGui/Assets/Assets/left_50/top_100/5_Power/2_Modules/1_Module_3/psu.json",
"oaGui/Assets/Assets/left_50/top_100/5_Power/2_Modules/1_Module_7/psu.json",
"oaGui/Assets/Assets/left_50/top_100/5_Power/2_Modules/1_Module_4/psu.json",
"oaGui/Assets/Assets/left_50/top_100/5_Power/2_Modules/1_Module_8/psu.json",
"oaGui/Assets/Assets/left_50/top_100/5_Power/2_Modules/1_Module_1/psu.json",
"oaGui/Assets/Assets/left_50/top_100/0_Spectrum/10_YAK/1_N9340B/8_Memory/memory.json",
"oaGui/Assets/Assets/left_50/top_100/0_Spectrum/10_YAK/1_N9340B/7_Markers/yak_markers.json",
"oaGui/Assets/Assets/left_50/top_100/0_Spectrum/10_YAK/1_N9340B/2_Amplitude/yak_amplitude.json",
"oaGui/Assets/Assets/left_50/top_100/0_Spectrum/10_YAK/1_N9340B/100_Connection/Connection_N9340B.json",
"oaGui/Assets/Assets/left_50/top_100/0_Spectrum/10_YAK/1_N9340B/0_Frequency/yak_frequency.json",
"oaGui/Assets/Assets/left_50/top_100/0_Spectrum/10_YAK/1_N9340B/3_Trace/yak_trace.json",
"oaGui/Assets/Assets/left_50/top_100/0_Spectrum/10_YAK/1_N9340B/9_System/yak_system.json",
"oaGui/Assets/Assets/left_50/top_100/0_Spectrum/10_YAK/1_N9340B/1_Bandwidth/yak_bandwidth.json",
"oaGui/Assets/Assets/left_50/top_100/0_Spectrum/10_YAK/3_HPE4411A/8_Memory/temp_norm_gui_memory.json",
"oaGui/Assets/Assets/left_50/top_100/0_Spectrum/10_YAK/3_HPE4411A/8_Memory/memory.json",
"oaGui/Assets/Assets/left_50/top_100/0_Spectrum/10_YAK/3_HPE4411A/7_Markers/yak_markers.json",
"oaGui/Assets/Assets/left_50/top_100/0_Spectrum/10_YAK/3_HPE4411A/2_Amplitude/yak_amplitude.json",
"oaGui/Assets/Assets/left_50/top_100/0_Spectrum/10_YAK/3_HPE4411A/100_Connection/Connection_N9340B.json",
"oaGui/Assets/Assets/left_50/top_100/0_Spectrum/10_YAK/3_HPE4411A/0_Frequency/yak_frequency.json",
"oaGui/Assets/Assets/left_50/top_100/0_Spectrum/10_YAK/3_HPE4411A/3_Trace/yak_trace.json",
"oaGui/Assets/Assets/left_50/top_100/0_Spectrum/10_YAK/3_HPE4411A/9_System/temp_norm_gui_yak_system.json",
"oaGui/Assets/Assets/left_50/top_100/0_Spectrum/10_YAK/3_HPE4411A/9_System/yak_system.json",
"oaGui/Assets/Assets/left_50/top_100/0_Spectrum/10_YAK/3_HPE4411A/1_Bandwidth/yak_bandwidth.json",
"oaGui/Assets/Assets/left_50/top_100/0_Spectrum/10_YAK/2_N9342CN/8_Memory/memory.json",
"oaGui/Assets/Assets/left_50/top_100/0_Spectrum/10_YAK/2_N9342CN/7_Markers/yak_markers.json",
"oaGui/Assets/Assets/left_50/top_100/0_Spectrum/10_YAK/2_N9342CN/2_Amplitude/yak_amplitude.json",
"oaGui/Assets/Assets/left_50/top_100/0_Spectrum/10_YAK/2_N9342CN/100_Connection/Connection_N9342CN.json",
"oaGui/Assets/Assets/left_50/top_100/0_Spectrum/10_YAK/2_N9342CN/0_Frequency/yak_frequency.json",
"oaGui/Assets/Assets/left_50/top_100/0_Spectrum/10_YAK/2_N9342CN/3_Trace/yak_trace.json",
"oaGui/Assets/Assets/left_50/top_100/0_Spectrum/10_YAK/2_N9342CN/9_System/temp_norm_gui_yak_system.json",
"oaGui/Assets/Assets/left_50/top_100/0_Spectrum/10_YAK/2_N9342CN/9_System/yak_system.json",
"oaGui/Assets/Assets/left_50/top_100/0_Spectrum/10_YAK/2_N9342CN/1_Bandwidth/yak_bandwidth.json",
"oaGui/Assets/Assets/left_50/top_100/0_Spectrum/3_Instrument/5_traces/traces.json",
"oaGui/Assets/Assets/left_50/top_100/0_Spectrum/3_Instrument/1_frequency/frequency.json",
"oaGui/Assets/Assets/left_50/top_100/0_Spectrum/3_Instrument/4_markers/markers.json",
"oaGui/Assets/Assets/left_50/top_100/0_Spectrum/3_Instrument/3_amplitude/amplitude.json",
"oaGui/Assets/Assets/left_50/top_100/0_Spectrum/3_Instrument/2_bandwidth/bandwidth.json",
"oaGui/Assets/Assets/left_50/top_100/0_Spectrum/6_plotting/1_Single/single.json",
"oaGui/Assets/Assets/left_50/top_100/0_Spectrum/4_Presets/DataSet/presets.json",
"oaGui/Assets/Assets/left_50/top_100/0_Spectrum/5_Sweeping/2_Sweeping_Configuration/sweeping_configuration.json",
"oaGui/Assets/Assets/left_50/top_100/1_Router/10_YAK/1_3235/100_Connection/Connection_switcher.json",
"oaGui/Assets/Assets/left_50/top_100/1_Router/10_YAK/1_3235/1_Commands/yak_router.json",
"oaGui/Assets/Assets/left_50/top_100/1_Router/1_Switcher/0_Coax/2_Right.json",
"oaGui/Assets/Assets/left_50/top_100/1_Router/1_Switcher/0_Coax/1_left.json",
"oaGui/Assets/Assets/left_50/top_100/1_Router/1_Switcher/0_Peripherals/2_Peripherals.json",
"oaGui/Assets/Assets/left_50/top_100/1_Router/1_Switcher/0_Peripherals/1_Test_Gear.json",
"oaGui/Assets/Assets/left_50/top_100/1_Router/1_Switcher/1_EDAC_1_12/EDAC_25_36.json",
"oaGui/Assets/Assets/left_50/top_100/1_Router/1_Switcher/1_EDAC_1_12/EDAC_13_24.json",
"oaGui/Assets/Assets/left_50/top_100/1_Router/1_Switcher/1_EDAC_1_12/EDAC_1_12.json",
"oaGui/Assets/Assets/right_50/bottom_90/10_sets/3_AES70/70_AES70_Object_Model/AES70.json",
"oaGui/Assets/Assets/right_50/bottom_90/10_sets/5_Application_Config/set_configuration_application.json",
"oaGui/Assets/Assets/right_50/bottom_90/10_sets/4_Constants/constants.json",
"oaGui/Assets/Assets/right_50/bottom_90/10_sets/2_Reports/0_Report/meta_report.json",
"oaGui/Assets/Assets/right_50/bottom_90/10_sets/1_meta/1_Bands/meta_Bands.json",
"oaGui/Assets/Assets/right_50/bottom_90/10_sets/1_meta/4_Television/2_Africa/meta_tv_africa.json",
"oaGui/Assets/Assets/right_50/bottom_90/10_sets/1_meta/4_Television/0_Europe/meta_tv_europe.json",
"oaGui/Assets/Assets/right_50/bottom_90/10_sets/1_meta/4_Television/0_Europe_UK/meta_tv_Europe.json",
"oaGui/Assets/Assets/right_50/bottom_90/10_sets/1_meta/4_Television/4_Northamerica/meta_tv_northamerica.json",
"oaGui/Assets/Assets/right_50/bottom_90/10_sets/1_meta/4_Television/4_Northamerica/meta_tv_northAmerica.json",
"oaGui/Assets/Assets/right_50/bottom_90/10_sets/1_meta/4_Television/6_South_America/meta_tv_south_america.json",
"oaGui/Assets/Assets/right_50/bottom_90/10_sets/1_meta/4_Television/1_Oceania/meta_tv_Oceania.json",
"oaGui/Assets/Assets/right_50/bottom_90/10_sets/1_meta/2_Government/10_Uk/meta_government_UK.json",
"oaGui/Assets/Assets/right_50/bottom_90/10_sets/1_meta/2_Government/11_Usa/meta_government_USA.json",
"oaGui/Assets/Assets/right_50/bottom_90/10_sets/1_meta/2_Government/5_India/meta_government_India.json",
"oaGui/Assets/Assets/right_50/bottom_90/10_sets/1_meta/2_Government/0_Australia/meta_government_Australia.json",
"oaGui/Assets/Assets/right_50/bottom_90/10_sets/1_meta/2_Government/1_Brazil/meta_government_Brazil.json",
"oaGui/Assets/Assets/right_50/bottom_90/10_sets/1_meta/2_Government/8_Russia/meta_government_Russia.json",
"oaGui/Assets/Assets/right_50/bottom_90/10_sets/1_meta/2_Government/9_Southafrica/meta_government_SouthAfrica.json",
"oaGui/Assets/Assets/right_50/bottom_90/10_sets/1_meta/2_Government/3_China/meta_government_China.json",
"oaGui/Assets/Assets/right_50/bottom_90/10_sets/1_meta/2_Government/6_Japan/meta_government_Japan.json",
"oaGui/Assets/Assets/right_50/bottom_90/10_sets/1_meta/2_Government/2_Canada/meta_government_Canada.json",
"oaGui/Assets/Assets/right_50/bottom_90/10_sets/1_meta/2_Government/4_Germany/meta_government_Germany.json",
"oaGui/Assets/Assets/right_50/bottom_90/10_sets/1_meta/2_Government/7_Mexico/meta_government_Mexico.json",
"oaGui/Assets/Assets/right_50/bottom_90/10_sets/3_RfComponents/2_Antenna/meta_components_antenna.json",
"oaGui/Assets/Assets/right_50/bottom_90/10_sets/3_RfComponents/0_Components/meta_components.json",
"oaGui/Assets/Assets/right_50/bottom_90/10_sets/3_RfComponents/1_Amplifier/meta_components_amplifier.json",
"oaGui/Assets/Assets/right_50/bottom_90/10_sets/6_Filepaths/set_configuration_application_filepaths.json",
"oaGui/Assets/Assets/right_50/bottom_90/2_monitors/00_Graphs/1_Top.json",
"oaGui/Assets/Assets/right_50/bottom_90/2_monitors/00_Graphs/2_Middle.json",
"oaGui/Assets/Assets/right_50/bottom_90/2_monitors/00_Graphs/3_Bottom.json",
"oaGui/Assets/Assets/right_50/bottom_90/1_scan/Scan.json",
"oaGui/Assets/Assets/right_50/top_10/start_pause_stop.json",
"oaGui/Assets/Assets/right_50/bottom_90/6_Setup/11_file_Paths/file_paths.json",
"oaGui/Assets/Assets/right_50/bottom_90/6_Setup/0_MQTT/MQTT.json",
"oaGui/Assets/Assets/right_50/bottom_90/6_Setup/0_Fleet/Fleet_Display.json"
]

for file_path in FILES:
    if not os.path.exists(file_path):
        continue
    with open(file_path) as f:
        try:
            data = json.load(f)
        except Exception as e:
            print(f"Error loading {file_path}: {e}")
            continue

    process_object(data)

    with open(file_path, "w") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print(f"Processed {file_path}")
