var namespaceoaGuiElements_1_1Tests_1_1metering_1_1meter__needle_1_1test__meter__needle__batch =
[
    [ "TestMeterNeedleBatch", "d4/dbf/classoaGuiElements_1_1Tests_1_1metering_1_1meter__needle_1_1test__meter__needle__batch_1_1TestMeterNeedleBatch.html", "d4/dbf/classoaGuiElements_1_1Tests_1_1metering_1_1meter__needle_1_1test__meter__needle__batch_1_1TestMeterNeedleBatch" ]
];