//! Minimal SDP parser for RAVENNA / AES67 stream announcements.
//!
//! Only the fields an operator actually needs are extracted. A general SDP
//! parser would be a much larger surface for no benefit here — these records are
//! machine-generated by the device and highly regular.
//!
//! A real record from the bench (Merging/Neumann hardware):
//!
//! ```text
//! v=0
//! o=- 5 0 IN IP4 44.44.44.166
//! s=Desk preMO
//! t=0 0
//! a=clock-domain:PTPv2 0
//! m=audio 5004 RTP/AVP 97
//! c=IN IP4 239.1.44.117/1
//! a=rtpmap:97 L24/48000/2
//! a=recvonly
//! a=ptime:1
//! a=ts-refclk:ptp=IEEE1588-2008:00-07-F5-FF-FE-00-54-72:0
//! a=mediaclk:direct=0
//! ```

/// What a RAVENNA stream announcement tells us.
#[derive(Debug, Default, Clone, PartialEq)]
pub struct StreamInfo {
    /// `s=` — the session name, which is also the RTSP `/by-name/` key.
    pub session: String,
    /// `a=rtpmap:` encoding, e.g. `L24`.
    pub codec: String,
    /// Sample rate in Hz, e.g. 48000.
    pub sample_rate: u32,
    /// Channel count.
    pub channels: u32,
    /// `c=` destination — a multicast group for a live RAVENNA stream.
    pub destination: String,
    /// `m=audio <port>` — the RTP port.
    pub rtp_port: u16,
    /// `a=ptime:` in milliseconds. RAVENNA's low-latency profiles use 0.125–1ms.
    pub ptime_ms: String,
    /// `a=clock-domain:` — e.g. `PTPv2 0`.
    pub clock_domain: String,
    /// `a=ts-refclk:` — identifies the PTP grandmaster the stream is locked to.
    pub refclk: String,
    /// `a=recvonly` / `a=sendonly` / `a=sendrecv`.
    pub direction: String,
    /// True when an `m=audio` line is present.
    ///
    /// This is the honest discriminator between a RAVENNA node and any other
    /// device answering RTSP on 554 — an IP camera will describe `m=video`.
    /// Presence on port 554 alone proves nothing.
    pub is_audio: bool,
}

impl StreamInfo {
    /// Human summary for a table cell, e.g. `L24 48000Hz 2ch`.
    pub fn format_summary(&self) -> String {
        if !self.is_audio {
            return "not an audio stream".to_string();
        }
        let mut parts = Vec::new();
        if !self.codec.is_empty() {
            parts.push(self.codec.clone());
        }
        if self.sample_rate > 0 {
            parts.push(format!("{}Hz", self.sample_rate));
        }
        if self.channels > 0 {
            parts.push(format!("{}ch", self.channels));
        }
        if parts.is_empty() { "audio".to_string() } else { parts.join(" ") }
    }
}

/// Parse an SDP payload into [`StreamInfo`].
///
/// Unknown or absent fields are left empty rather than guessed. Tolerates the
/// RTSP response headers being present before the body.
pub fn parse(sdp: &str) -> StreamInfo {
    let mut info = StreamInfo::default();

    for raw_line in sdp.lines() {
        let line = raw_line.trim();
        let (key, value) = match line.split_once('=') {
            Some(kv) => kv,
            None => continue,
        };
        match key {
            "s" => info.session = value.trim().to_string(),
            "c" => {
                // c=IN IP4 239.1.44.117/1  -> keep the address, drop the TTL.
                if let Some(addr) = value.split_whitespace().nth(2) {
                    info.destination =
                        addr.split('/').next().unwrap_or(addr).to_string();
                }
            }
            "m" => {
                // m=audio 5004 RTP/AVP 97
                let mut it = value.split_whitespace();
                if let Some(media) = it.next() {
                    info.is_audio = media.eq_ignore_ascii_case("audio");
                }
                if let Some(port) = it.next() {
                    info.rtp_port = port.parse().unwrap_or(0);
                }
            }
            "a" => {
                if let Some(rest) = value.strip_prefix("rtpmap:") {
                    // rtpmap:97 L24/48000/2
                    if let Some(enc) = rest.split_whitespace().nth(1) {
                        let mut f = enc.split('/');
                        info.codec = f.next().unwrap_or("").to_string();
                        info.sample_rate = f.next().and_then(|v| v.parse().ok()).unwrap_or(0);
                        // Mono streams omit the channel count entirely.
                        info.channels = f.next().and_then(|v| v.parse().ok()).unwrap_or(1);
                    }
                } else if let Some(rest) = value.strip_prefix("ptime:") {
                    info.ptime_ms = rest.trim().to_string();
                } else if let Some(rest) = value.strip_prefix("clock-domain:") {
                    info.clock_domain = rest.trim().to_string();
                } else if let Some(rest) = value.strip_prefix("ts-refclk:") {
                    info.refclk = rest.trim().to_string();
                } else if ["recvonly", "sendonly", "sendrecv", "inactive"]
                    .contains(&value.trim())
                {
                    info.direction = value.trim().to_string();
                }
            }
            _ => {}
        }
    }
    info
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Verbatim from 44.44.44.166 on the bench.
    const DESK_PREMO: &str = "\
RTSP/1.0 200 OK\r\nContent-Type: application/sdp\r\nContent-Length: 287\r\nCSeq: 1\r\n\r\n\
v=0\n\
o=- 5 0 IN IP4 44.44.44.166\n\
s=Desk preMO\n\
t=0 0\n\
a=clock-domain:PTPv2 0\n\
m=audio 5004 RTP/AVP 97\n\
c=IN IP4 239.1.44.117/1\n\
a=rtpmap:97 L24/48000/2\n\
a=recvonly\n\
a=framecount:48\n\
a=ptime:1\n\
a=ts-refclk:ptp=IEEE1588-2008:00-07-F5-FF-FE-00-54-72:0\n\
a=mediaclk:direct=0\n";

    #[test]
    fn parses_a_real_ravenna_announcement() {
        let s = parse(DESK_PREMO);
        assert_eq!(s.session, "Desk preMO");
        assert_eq!(s.codec, "L24");
        assert_eq!(s.sample_rate, 48000);
        assert_eq!(s.channels, 2);
        assert_eq!(s.destination, "239.1.44.117"); // TTL suffix stripped
        assert_eq!(s.rtp_port, 5004);
        assert_eq!(s.ptime_ms, "1");
        assert_eq!(s.clock_domain, "PTPv2 0");
        assert_eq!(s.direction, "recvonly");
        assert!(s.refclk.starts_with("ptp=IEEE1588-2008"));
        assert!(s.is_audio);
        assert_eq!(s.format_summary(), "L24 48000Hz 2ch");
    }

    /// The discriminator that stops an IP camera being filed as an audio node.
    #[test]
    fn video_streams_are_not_audio() {
        let s = parse("v=0\ns=Front Door\nm=video 5006 RTP/AVP 96\na=rtpmap:96 H264/90000\n");
        assert!(!s.is_audio);
        assert_eq!(s.format_summary(), "not an audio stream");
    }

    /// Mono announcements omit the trailing channel count.
    #[test]
    fn mono_defaults_to_one_channel() {
        let s = parse("m=audio 5004 RTP/AVP 96\na=rtpmap:96 L24/48000\n");
        assert_eq!(s.channels, 1);
        assert_eq!(s.sample_rate, 48000);
    }

    #[test]
    fn missing_fields_stay_empty_rather_than_guessed() {
        let s = parse("v=0\ns=Bare\n");
        assert_eq!(s.session, "Bare");
        assert_eq!(s.codec, "");
        assert_eq!(s.sample_rate, 0);
        assert!(!s.is_audio);
    }
}
