var namespaceaes70_1_1types_1_1ocamediasinkconnectorchangedeventdata =
[
    [ "IOcaMediaSinkConnectorChangedEventData", "db/d59/classaes70_1_1types_1_1ocamediasinkconnectorchangedeventdata_1_1IOcaMediaSinkConnectorChangedEventData.html", "db/d59/classaes70_1_1types_1_1ocamediasinkconnectorchangedeventdata_1_1IOcaMediaSinkConnectorChangedEventData" ],
    [ "OcaMediaSinkConnectorChangedEventData", "dd/dc5/classaes70_1_1types_1_1ocamediasinkconnectorchangedeventdata_1_1OcaMediaSinkConnectorChangedEventData.html", "dd/dc5/classaes70_1_1types_1_1ocamediasinkconnectorchangedeventdata_1_1OcaMediaSinkConnectorChangedEventData" ]
];