# Constants/mqtt_config.py
# Author: Anthony Peter Kuzub
# Version: 1.1.0
#
# Description: Standard MQTT configuration defaults and state constants.

DEFAULT_MQTT_KEEPALIVE = 60
DEFAULT_MQTT_TIMEOUT = 10
DEFAULT_QOS = 0
RECONNECT_DELAY = 5.0

# System Topics
TOPIC_STATUS = "OPEN-AIR/status"
PAYLOAD_OFFLINE = "OFFLINE"
PAYLOAD_ONLINE = "ONLINE"

# Worker Settings
WORKER_KICK_TIMEOUT = 5.0
MAX_PUBLISH_BATCH = 100
ASYNC_JOIN_TIMEOUT = 2.0
QUEUE_GET_TIMEOUT = 0.1
MATCH_CACHE_LIMIT = 1000
BOOTSTRAP_WAIT_TIME = 2.0
BROKER_CONNECT_TIMEOUT = 60
LOG_FLUSH_INTERVAL = 0.01
