use pyo3::prelude::*;

pub mod oa_audio_mixer_rs;
pub mod oa_config_engine_rs;
pub mod oa_async_sink_rs;
pub mod oa_logging_gate_rs;
pub mod oa_safety_core_rs;
pub mod oa_heartbeat_core_rs;
pub mod oa_thread_pool_rs;
pub mod oa_clock_sync_rs;
pub mod oa_core_router_rs;
pub mod oa_aes70_core_rs;
pub mod oa_ember_tree_rs;
pub mod oa_midi_mapper_rs;
pub mod oa_midi_engine_rs;
pub mod oa_mqtt_manager_rs;
pub mod oa_osc_core_rs;
pub mod oa_fast_api_rs;
pub mod oa_st2138_codec_rs;
pub mod oa_mib_cache_rs;
pub mod oa_snmp_agent_rs;
pub mod oa_visa_core_rs;
pub mod oa_visa_format_rs;
pub mod oa_visa_scanner_rs;
pub mod oa_ptp_clock_rs;
pub mod oa_ptp_parser_rs;
pub mod oa_fast_dir_rs;
pub mod oa_layout_engine_rs;
pub mod oa_pattern_engine_rs;
pub mod oa_geometry_math_rs;
pub mod oa_editor_state_rs;
pub mod oa_hitbox_math_rs;
pub mod oa_metering_engine_rs;
pub mod oa_cmdp_math_rs;
pub mod oa_needle_engine_rs;
pub mod oa_needle_geometry_rs;
pub mod oa_procedural_art_rs;
pub mod oa_rotary_core_rs;
pub mod oa_fast_scanner_rs;
pub mod oa_blueprint_parser_rs;
pub mod oa_image_scaler_rs;
pub mod oa_time_series_db_rs;
pub mod oa_css_parser_rs;
pub mod oa_csv_writer_rs;
pub mod oa_csv_parser_rs;
pub mod oa_html_scraper_rs;
pub mod oa_pdf_parser_rs;
pub mod oa_showfile_unpacker_rs;
pub mod oa_splink_registry_rs;
pub mod oa_splink_core_rs;
pub mod oa_disk_flusher_rs;
pub mod oa_task_pool_rs;
pub mod oa_translator_core_rs;
pub mod oa_trie_rs;
pub mod oa_state_differ_rs;
pub mod oa_state_registry_rs;
pub mod oa_markdown_compiler_rs;
pub mod oa_log_aligner_rs;
pub mod oa_debug_toggler_rs;
pub mod oa_log_processor_rs;
pub mod oa_manifest_gen_rs;

#[pymodule]
fn oaRustCore(m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.add_submodule(&oa_audio_mixer_rs::oaaudiomixer_rs(m.py())?)?;
    m.add_submodule(&oa_config_engine_rs::oaconfigengine_rs(m.py())?)?;
    m.add_submodule(&oa_async_sink_rs::oaasyncsink_rs(m.py())?)?;
    m.add_submodule(&oa_logging_gate_rs::oalogginggate_rs(m.py())?)?;
    m.add_submodule(&oa_safety_core_rs::oasafetycore_rs(m.py())?)?;
    m.add_submodule(&oa_heartbeat_core_rs::oaHeartbeatCore_rs(m.py())?)?;
    m.add_submodule(&oa_thread_pool_rs::oathreadpool_rs(m.py())?)?;
    m.add_submodule(&oa_clock_sync_rs::oaclocksync_rs(m.py())?)?;
    m.add_submodule(&oa_core_router_rs::oacorerouter_rs(m.py())?)?;
    m.add_submodule(&oa_aes70_core_rs::oaaes70core_rs(m.py())?)?;
    m.add_submodule(&oa_ember_tree_rs::oaembertree_rs(m.py())?)?;
    m.add_submodule(&oa_midi_mapper_rs::oamidimapper_rs(m.py())?)?;
    m.add_submodule(&oa_midi_engine_rs::oamidiengine_rs(m.py())?)?;
    m.add_submodule(&oa_mqtt_manager_rs::oamqttmanager_rs(m.py())?)?;
    m.add_submodule(&oa_osc_core_rs::oaosccore_rs(m.py())?)?;
    m.add_submodule(&oa_fast_api_rs::oafastapi_rs(m.py())?)?;
    m.add_submodule(&oa_st2138_codec_rs::oast2138codec_rs(m.py())?)?;
    m.add_submodule(&oa_mib_cache_rs::oaMIBCache_rs(m.py())?)?;
    m.add_submodule(&oa_snmp_agent_rs::oasnmpagent_rs(m.py())?)?;
    m.add_submodule(&oa_visa_core_rs::oavisacore_rs(m.py())?)?;
    m.add_submodule(&oa_visa_format_rs::oavisaformat_rs(m.py())?)?;
    m.add_submodule(&oa_visa_scanner_rs::oavisascanner_rs(m.py())?)?;
    m.add_submodule(&oa_ptp_clock_rs::oaptpclock_rs(m.py())?)?;
    m.add_submodule(&oa_ptp_parser_rs::oaptpparser_rs(m.py())?)?;
    m.add_submodule(&oa_fast_dir_rs::oaFastDir_rs(m.py())?)?;
    m.add_submodule(&oa_layout_engine_rs::oaLayoutEngine_rs(m.py())?)?;
    m.add_submodule(&oa_pattern_engine_rs::oapatternengine_rs(m.py())?)?;
    m.add_submodule(&oa_geometry_math_rs::oageometrymath_rs(m.py())?)?;
    m.add_submodule(&oa_editor_state_rs::oaeditorstate_rs(m.py())?)?;
    m.add_submodule(&oa_hitbox_math_rs::oaHitboxMath_rs(m.py())?)?;
    m.add_submodule(&oa_metering_engine_rs::oameteringengine_rs(m.py())?)?;
    m.add_submodule(&oa_cmdp_math_rs::oacmdpmath_rs(m.py())?)?;
    m.add_submodule(&oa_needle_engine_rs::oaneedleengine_rs(m.py())?)?;
    m.add_submodule(&oa_needle_geometry_rs::oaneedlegeometry_rs(m.py())?)?;
    m.add_submodule(&oa_procedural_art_rs::oaproceduralart_rs(m.py())?)?;
    m.add_submodule(&oa_rotary_core_rs::oarotarycore_rs(m.py())?)?;
    m.add_submodule(&oa_fast_scanner_rs::oafastscanner_rs(m.py())?)?;
    m.add_submodule(&oa_blueprint_parser_rs::oablueprintparser_rs(m.py())?)?;
    m.add_submodule(&oa_image_scaler_rs::oaImageScaler_rs(m.py())?)?;
    m.add_submodule(&oa_time_series_db_rs::oaTimeSeriesDB_rs(m.py())?)?;
    m.add_submodule(&oa_css_parser_rs::oaCSSParser_rs(m.py())?)?;
    m.add_submodule(&oa_csv_writer_rs::oacsvwriter_rs(m.py())?)?;
    m.add_submodule(&oa_csv_parser_rs::oacsvparser_rs(m.py())?)?;
    m.add_submodule(&oa_html_scraper_rs::oahtmlscraper_rs(m.py())?)?;
    m.add_submodule(&oa_pdf_parser_rs::oapdfparser_rs(m.py())?)?;
    m.add_submodule(&oa_showfile_unpacker_rs::oashowfileunpacker_rs(m.py())?)?;
    m.add_submodule(&oa_splink_registry_rs::oasplinkregistry_rs(m.py())?)?;
    m.add_submodule(&oa_splink_core_rs::oasplinkcore_rs(m.py())?)?;
    m.add_submodule(&oa_disk_flusher_rs::oadiskflusher_rs(m.py())?)?;
    m.add_submodule(&oa_task_pool_rs::oataskpool_rs(m.py())?)?;
    m.add_submodule(&oa_translator_core_rs::oatranslatorcore_rs(m.py())?)?;
    m.add_submodule(&oa_trie_rs::oatrie_rs(m.py())?)?;
    m.add_submodule(&oa_state_differ_rs::oaStateDiffer_rs(m.py())?)?;
    m.add_submodule(&oa_state_registry_rs::oastateregistry_rs(m.py())?)?;
    m.add_submodule(&oa_markdown_compiler_rs::oaMarkdownCompiler_rs(m.py())?)?;
    m.add_submodule(&oa_log_aligner_rs::oalogaligner_rs(m.py())?)?;
    m.add_submodule(&oa_debug_toggler_rs::oadebugtoggler_rs(m.py())?)?;
    m.add_submodule(&oa_log_processor_rs::oalogprocessor_rs(m.py())?)?;
    m.add_submodule(&oa_manifest_gen_rs::oamanifestgen_rs(m.py())?)?;
    Ok(())
}
