use pyo3::prelude::*;

pub mod oa_audio_mixer_rs;
pub mod oa_config_engine_rs;
pub mod oa_async_sink_rs;
pub mod oa_logging_gate_rs;
pub mod oa_safety_core_rs;
pub mod oa_heartbeat_core_rs;
pub mod oa_thread_pool_rs;
pub mod oa_clock_sync_rs;
pub mod oa_core_router_rs;
pub mod oa_aes70_core_rs;
pub mod oa_ember_tree_rs;
pub mod oa_midi_mapper_rs;
pub mod oa_midi_engine_rs;
pub mod oa_mqtt_manager_rs;
pub mod oa_osc_core_rs;
pub mod oa_fast_api_rs;
pub mod oa_st2138_codec_rs;
pub mod oa_mib_cache_rs;
pub mod oa_snmp_agent_rs;
pub mod oa_visa_core_rs;
pub mod oa_visa_format_rs;
pub mod oa_visa_scanner_rs;
pub mod oa_ptp_clock_rs;
pub mod oa_ptp_parser_rs;
pub mod oa_fast_dir_rs;
pub mod oa_layout_engine_rs;
pub mod oa_pattern_engine_rs;
pub mod oa_geometry_math_rs;
pub mod oa_editor_state_rs;
pub mod oa_hitbox_math_rs;
pub mod oa_metering_engine_rs;
pub mod oa_cmdp_math_rs;
pub mod oa_needle_engine_rs;
pub mod oa_needle_geometry_rs;
pub mod oa_procedural_art_rs;
pub mod oa_rotary_core_rs;
pub mod oa_fast_scanner_rs;
pub mod oa_blueprint_parser_rs;
pub mod oa_image_scaler_rs;
pub mod oa_time_series_db_rs;
pub mod oa_css_parser_rs;
pub mod oa_csv_writer_rs;
pub mod oa_csv_parser_rs;
pub mod oa_html_scraper_rs;
pub mod oa_pdf_parser_rs;
pub mod oa_showfile_unpacker_rs;
pub mod oa_splink_registry_rs;
pub mod oa_splink_core_rs;
pub mod oa_disk_flusher_rs;
pub mod oa_task_pool_rs;
pub mod oa_translator_core_rs;
pub mod oa_trie_rs;
pub mod oa_state_differ_rs;
pub mod oa_state_registry_rs;
pub mod oa_markdown_compiler_rs;
pub mod oa_log_aligner_rs;
pub mod oa_debug_toggler_rs;
pub mod oa_log_processor_rs;
pub mod oa_manifest_gen_rs;

#[pymodule]
fn oaRustCore(_py: Python, m: &PyModule) -> PyResult<()> {
    m.add_submodule(oa_audio_mixer_rs::create_module(_py)?)?;
    m.add_submodule(oa_config_engine_rs::create_module(_py)?)?;
    m.add_submodule(oa_async_sink_rs::create_module(_py)?)?;
    m.add_submodule(oa_logging_gate_rs::create_module(_py)?)?;
    m.add_submodule(oa_safety_core_rs::create_module(_py)?)?;
    m.add_submodule(oa_heartbeat_core_rs::create_module(_py)?)?;
    m.add_submodule(oa_thread_pool_rs::create_module(_py)?)?;
    m.add_submodule(oa_clock_sync_rs::create_module(_py)?)?;
    m.add_submodule(oa_core_router_rs::create_module(_py)?)?;
    m.add_submodule(oa_aes70_core_rs::create_module(_py)?)?;
    m.add_submodule(oa_ember_tree_rs::create_module(_py)?)?;
    m.add_submodule(oa_midi_mapper_rs::create_module(_py)?)?;
    m.add_submodule(oa_midi_engine_rs::create_module(_py)?)?;
    m.add_submodule(oa_mqtt_manager_rs::create_module(_py)?)?;
    m.add_submodule(oa_osc_core_rs::create_module(_py)?)?;
    m.add_submodule(oa_fast_api_rs::create_module(_py)?)?;
    m.add_submodule(oa_st2138_codec_rs::create_module(_py)?)?;
    m.add_submodule(oa_mib_cache_rs::create_module(_py)?)?;
    m.add_submodule(oa_snmp_agent_rs::create_module(_py)?)?;
    m.add_submodule(oa_visa_core_rs::create_module(_py)?)?;
    m.add_submodule(oa_visa_format_rs::create_module(_py)?)?;
    m.add_submodule(oa_visa_scanner_rs::create_module(_py)?)?;
    m.add_submodule(oa_ptp_clock_rs::create_module(_py)?)?;
    m.add_submodule(oa_ptp_parser_rs::create_module(_py)?)?;
    m.add_submodule(oa_fast_dir_rs::create_module(_py)?)?;
    m.add_submodule(oa_layout_engine_rs::create_module(_py)?)?;
    m.add_submodule(oa_pattern_engine_rs::create_module(_py)?)?;
    m.add_submodule(oa_geometry_math_rs::create_module(_py)?)?;
    m.add_submodule(oa_editor_state_rs::create_module(_py)?)?;
    m.add_submodule(oa_hitbox_math_rs::create_module(_py)?)?;
    m.add_submodule(oa_metering_engine_rs::create_module(_py)?)?;
    m.add_submodule(oa_cmdp_math_rs::create_module(_py)?)?;
    m.add_submodule(oa_needle_engine_rs::create_module(_py)?)?;
    m.add_submodule(oa_needle_geometry_rs::create_module(_py)?)?;
    m.add_submodule(oa_procedural_art_rs::create_module(_py)?)?;
    m.add_submodule(oa_rotary_core_rs::create_module(_py)?)?;
    m.add_submodule(oa_fast_scanner_rs::create_module(_py)?)?;
    m.add_submodule(oa_blueprint_parser_rs::create_module(_py)?)?;
    m.add_submodule(oa_image_scaler_rs::create_module(_py)?)?;
    m.add_submodule(oa_time_series_db_rs::create_module(_py)?)?;
    m.add_submodule(oa_css_parser_rs::create_module(_py)?)?;
    m.add_submodule(oa_csv_writer_rs::create_module(_py)?)?;
    m.add_submodule(oa_csv_parser_rs::create_module(_py)?)?;
    m.add_submodule(oa_html_scraper_rs::create_module(_py)?)?;
    m.add_submodule(oa_pdf_parser_rs::create_module(_py)?)?;
    m.add_submodule(oa_showfile_unpacker_rs::create_module(_py)?)?;
    m.add_submodule(oa_splink_registry_rs::create_module(_py)?)?;
    m.add_submodule(oa_splink_core_rs::create_module(_py)?)?;
    m.add_submodule(oa_disk_flusher_rs::create_module(_py)?)?;
    m.add_submodule(oa_task_pool_rs::create_module(_py)?)?;
    m.add_submodule(oa_translator_core_rs::create_module(_py)?)?;
    m.add_submodule(oa_trie_rs::create_module(_py)?)?;
    m.add_submodule(oa_state_differ_rs::create_module(_py)?)?;
    m.add_submodule(oa_state_registry_rs::create_module(_py)?)?;
    m.add_submodule(oa_markdown_compiler_rs::create_module(_py)?)?;
    m.add_submodule(oa_log_aligner_rs::create_module(_py)?)?;
    m.add_submodule(oa_debug_toggler_rs::create_module(_py)?)?;
    m.add_submodule(oa_log_processor_rs::create_module(_py)?)?;
    m.add_submodule(oa_manifest_gen_rs::create_module(_py)?)?;
    Ok(())
}