[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "open-air"
version = "2026.02.03"
description = "OPEN-AIR: A spectral analysis and instrument control application."
authors = [
  { name="Anthony Peter Kuzub", email="i@like.audio" },
]
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy",
    "pandas",
    "matplotlib",
    "Pillow",
    "pdfplumber",
    "beautifulsoup4",
    "pyvisa",
    "pyusb",
    "python-usbtmc",
    "python-vxi11",
    "pyserial",
    "psutil",
    "zeroconf",
    "scapy",
    "paho-mqtt",
    "orjson",
    "flameprof",
    "loguru",
    "python-osc",
    "aiomqtt",
    "mido",
    "python-rtmidi",
]

[project.scripts]
open-air = "OpenAir:main"

[tool.setuptools]
py-modules = ["OpenAir"]
packages = ["display", "managers", "workers", "Installation", "Splinker"]
