# oaGui/Constants/builder_constants.py
# Author: Gemini (Collaborator)
# Version: 20260324.1.0
#
# Description: Standard GUI Builder constants for intervals, thresholds and layout.

SCROLL_SYNC_DELAY = 50
RESIZE_THROTTLE_DELAY = 150
RESIZE_WIDTH_THRESHOLD = 5

# BreakLine Constants
BREAKLINE_MIN_THICKNESS = 4
BREAKLINE_DEFAULT_COLOR = "#888888"

# Slicing Registry Constants
SLICING_REGEN_THRESHOLD = 3
SLICING_POSITION_EPSILON = 0.005
SLICING_DELAY_REBUILD = 300
SLICING_DELAY_NORMAL = 100

# Layout and Sizing Constants
DEFAULT_TREE_COLUMN_WIDTH = 100
LARGE_TREE_COLUMN_WIDTH = 400
SMALL_TREE_COLUMN_WIDTH = 80
DEFAULT_ENTRY_WIDTH = 40
GHOST_WIDGET_DEFAULT_SIZE = 100
MAX_LOG_ENTRIES = 1000
