var searchData=
[
  ['d_20pad_0',['DirectionalButtons — D-pad',['../d5/d8e/md_frontEnd_2libControl_2input_2DirectionalButtons_2Readme.html',1,'']]],
  ['data_1',['data',['../d6/dd4/md_oaGuiElements_2Documentation_2lyrics.html',1,'🏷️ Lyrics Data'],['../d6/dbe/md_oaComProtocols_2oaComNmos_2Core_2IS12_2Documentation_2is-12_2releases_2v1_80_81_2APIs_2schemas_2with-refs_2event-data.html',1,'event-data'],['../d4/da0/md_oaComProtocols_2oaComNmos_2Core_2IS12_2Documentation_2is-12_2releases_2v1_80_81_2APIs_2schemas_2event-data.html',1,'event-data'],['../d5/db8/md_oaComProtocols_2oaComNmos_2Core_2IS12_2Documentation_2is-12_2releases_2v1_80_81_2APIs_2schemas_2resolved_2event-data.html',1,'event-data'],['../d9/d88/md_oaComProtocols_2oaComNmos_2Core_2IS12_2Documentation_2is-12_2releases_2v1_80_81_2APIs_2schemac994bfba38e65fee2f68bea53c457758.html',1,'property-changed-event-data'],['../d7/d56/md_oaComProtocols_2oaComNmos_2Core_2IS12_2Documentation_2is-12_2releases_2v1_80_81_2APIs_2schema3a9169d22456c62bc08574ef4cdc9b15.html',1,'property-changed-event-data'],['../de/de1/md_oaComProtocols_2oaComNmos_2Core_2IS12_2Documentation_2is-12_2releases_2v1_80_81_2APIs_2schemas_2property-changed-event-data.html',1,'property-changed-event-data']]],
  ['data_20json_20tree_2',['🏷️ Data Json Tree',['../dd/dec/md_oaGuiElements_2Documentation_2json__tree.html',1,'']]],
  ['data_20radar_3',['🏷️ Data Radar',['../d0/d7b/md_oaGuiElements_2Documentation_2radar.html',1,'']]],
  ['data_20table_4',['OcaTable — data table',['../d1/d06/md_frontEnd_2libControl_2text_2OcaTable_2Readme.html',1,'']]],
  ['data_5ftype_5fdefinition_5fdiscovery_5',['Data_type_definition_discovery',['../db/d13/md_oaComProtocols_2oaComNmos_2Core_2IS12_2Documentation_2is-12_2releases_2v1_80_81_2docs_2Data__type__definition__discovery.html',1,'']]],
  ['data_5ftype_5fmarshalling_6',['Data_type_marshalling',['../dc/d48/md_oaComProtocols_2oaComNmos_2Core_2IS12_2Documentation_2is-12_2releases_2v1_80_81_2docs_2Data__type__marshalling.html',1,'']]],
  ['deadband_20handler_7',['Deadband Handler',['../d1/d2d/md_oaSplinker_2Documentation_2handlers_2deadband.html',1,'']]],
  ['debounce_20handler_8',['Debounce Handler',['../db/d0f/md_oaSplinker_2Documentation_2handlers_2debounce.html',1,'']]],
  ['debugging_20overhaul_202026_2003_2014_9',['Bug Log: Reliability &amp; Debugging Overhaul (2026-03-14)',['../d6/d01/md_oaDocumentation_2Workers_2BugLog_2BUG__20260314__005023.html',1,'']]],
  ['dec_20buttons_10',['🏷️ Input Inc Dec Buttons',['../d6/d3f/md_oaGuiElements_2Documentation_2input__inc__dec__buttons.html',1,'']]],
  ['decrement_11',['IncDecButtons — increment / decrement',['../db/d20/md_frontEnd_2libControl_2input_2IncDecButtons_2Readme.html',1,'']]],
  ['default_20message_12',['[2026-03-16 10:35:28 -0400] chore: Update project files (default message)',['../da/d7e/md_oaDocumentation_2Workers_2ChangeLog_2CHANGELOG__202602.html',1,'']]],
  ['delete_20open_20air_13',['🏷️ Delete Open Air',['../d7/d0b/md_oaComProtocols_2oaComMQTT_2Documentation_2delete__open__air.html',1,'']]],
  ['delete_5fsplink_14',['delete_splink',['../d1/dd5/md_oaSplinker_2Documentation_2functions_2delete__splink.html',1,'']]],
  ['demo_15',['Fader — standalone fader (demo)',['../d3/d82/md_frontEnd_2libControl_2faders_2Fader_2Readme.html',1,'']]],
  ['dependencies_16',['📦 OPEN-AIR Project Dependencies',['../d9/da1/md_oaInstallation_2Documentation_2Dependencies.html',1,'']]],
  ['dependency_20refactor_17',['Bug Report: ImportError in VisaFleetManager (Circular Dependency Refactor)',['../d1/dc5/md_oaDocumentation_2Workers_2BugLog_2BUG__20260316__011800.html',1,'']]],
  ['description_20of_20the_20invention_18',['Description of the Invention',['../de/d63/md_oaDocumentation_2Documentation_2Patent_202__description.html',1,'']]],
  ['design_20lens_19',['Summary.md - The Design Lens',['../d2/d5a/md_oaGuiEditorWYSIWYG_2Documentation_2Summary.html',1,'']]],
  ['device_20',['🏷️ Preset From Device',['../de/da5/md_oaStateCache_2Documentation_2preset__from__device.html',1,'']]],
  ['dial_20composite_21',['FaderDial — fader + dial composite',['../df/dc3/md_frontEnd_2libControl_2faders_2FaderDial_2Readme.html',1,'']]],
  ['dial_20value_22',['🏷️ Composite Horizontal Dial Value',['../da/d0b/md_oaGuiElements_2Documentation_2composite__horizontal__dial__value.html',1,'']]],
  ['dimensional_20panner_23',['MDP — Multi-Dimensional Panner',['../d9/d0b/md_frontEnd_2libControl_2special_2MDP_2Readme.html',1,'']]],
  ['dimensional_20panner_20faders_20variant_24',['MDP — Multi Dimensional Panner (faders variant)',['../da/df8/md_frontEnd_2libControl_2faders_2MDP_2Readme.html',1,'']]],
  ['directional_20buttons_25',['🏷️ Input Directional Buttons',['../dc/d47/md_oaGuiElements_2Documentation_2input__directional__buttons.html',1,'']]],
  ['directionalbuttons_20—_20d_20pad_26',['DirectionalButtons — D-pad',['../d5/d8e/md_frontEnd_2libControl_2input_2DirectionalButtons_2Readme.html',1,'']]],
  ['directory_20based_20notebooks_27',['BUG: GUI Layout Regression for Directory-Based Notebooks',['../df/d55/md_oaDocumentation_2Workers_2BugLog_2BUG__20260314__170217.html',1,'']]],
  ['directory_20name_20parsing_28',['BUG: GUI Layout Regression from Directory Name Parsing',['../db/dbe/md_oaDocumentation_2Workers_2BugLog_2BUG__20260314__161529.html',1,'']]],
  ['disabled_29',['BUG: PanedWindow Sash Dragging Disabled',['../dd/d98/md_oaDocumentation_2Workers_2BugLog_2BUG__20260314__191713.html',1,'']]],
  ['disconnect_20instrument_30',['🏷️ Manager Logic Disconnect Instrument',['../d8/dbc/md_oaComProtocols_2oaComVisa_2Documentation_2logic__disconnect__instrument.html',1,'']]],
  ['discovery_20errors_31',['Bug Report: Graphing Mapping and VISA Discovery Errors',['../db/d1a/md_oaDocumentation_2Workers_2BugLog_2BUG__20260316__011000.html',1,'']]],
  ['discovery_20importerror_32',['Bug Report: Test Discovery ImportError',['../d7/df4/md_oaDocumentation_2Workers_2BugLog_2BUG__20260409__002000.html',1,'']]],
  ['discovery_20orchestrator_33',['🏷️ Discovery Orchestrator',['../d6/d6f/md_oaComProtocols_2oaComVisa_2Documentation_2discovery__orchestrator.html',1,'']]],
  ['dispatch_34',['BUG: Catastrophic Failure of Core Protocol Dispatch',['../df/d86/md_oaDocumentation_2Workers_2BugLog_2BUG__20260314__193426__CORE__SYSTEMS__MEGAFIX.html',1,'']]],
  ['dispatch_20attributeerror_35',['Bug Report: UI Startup Crash and Protocol Dispatch AttributeError',['../db/dd7/md_oaDocumentation_2Workers_2BugLog_2BUG__20260314__234500.html',1,'']]],
  ['displacement_20potentiometer_36',['displacement potentiometer',['../d1/dbc/md_oaGuiElements_2Documentation_2circular__motion__displacement__potentiometer.html',1,'🏷️ Circular Motion Displacement Potentiometer'],['../d3/db4/md_frontEnd_2libControl_2special_2CMDP_2Readme.html',1,'CMDP — Circular Motion Displacement Potentiometer']]],
  ['display_37',['display',['../d8/daf/md_oaGuiElements_2Documentation_2images__animation__display.html',1,'🏷️ Images Animation Display'],['../d3/d1f/md_oaGuiElements_2Documentation_2images__image__display.html',1,'🏷️ Images Image Display']]],
  ['display_20issue_38',['Bug Report: GraphPlotter Display Issue',['../d1/d21/md_oaDocumentation_2BugLog_2BUG__20260403__021630.html',1,'']]],
  ['display_20move_39',['Bug Report: UI Window Collapsing on Display Move',['../d8/dde/md_oaDocumentation_2Workers_2BugLog_2BUG__20260316__012300.html',1,'']]],
  ['display_20units_40',['🏷️ Meter To Display Units',['../db/d1f/md_oaGuiElements_2Documentation_2Meter__to__display__units.html',1,'']]],
  ['divider_20rule_41',['BreakLine — divider rule',['../d5/d1d/md_frontEnd_2libControl_2BreakLine_2Readme.html',1,'']]],
  ['documentation_42',['documentation',['../d9/d69/md_oaComProtocols_2oaComAES70_2Documentation_2ProtocolShifter.html',1,'oaComAES70 Protocol Shifter Documentation'],['../d4/d37/md_oaComProtocols_2oaComEmber_2Documentation_2ProtocolShifter.html',1,'oaComEmber Protocol Shifter Documentation'],['../df/d23/md_oaComProtocols_2oaComMidi_2Documentation_2ProtocolShifter.html',1,'oaComMidi Protocol Shifter Documentation'],['../d3/d16/md_oaComProtocols_2oaComMQTT_2Documentation_2ProtocolShifter.html',1,'oaComMQTT Protocol Shifter Documentation'],['../d5/da9/md_oaComProtocols_2oaComNmos_2Documentation_2ProtocolShifter.html',1,'oaComNmos Protocol Shifter Documentation'],['../d5/d50/md_oaComProtocols_2oaComOSC_2Documentation_2OSCProtocolShifter.html',1,'oaComOSC Protocol Shifter Documentation'],['../d9/d2d/md_oaComProtocols_2oaComREST_2Documentation_2ProtocolShifter.html',1,'oaComREST Protocol Shifter Documentation'],['../dc/d6e/md_oaComProtocols_2oaComSMPTE2138_2Documentation_2ProtocolShifter.html',1,'oaComSMPTE2138 Protocol Shifter Documentation'],['../dc/d90/md_oaComProtocols_2oaComSNMP_2Documentation_2ProtocolShifter.html',1,'oaComSNMP Protocol Shifter Documentation'],['../da/d3d/md_oaComProtocols_2oaComVisa_2Documentation_2ProtocolShifter.html',1,'oaComVisa Protocol Shifter Documentation'],['../dd/d26/md_oaComProtocols_2oaComWebsocket_2Documentation_2ProtocolShifter.html',1,'oaComWebsocket Protocol Shifter Documentation']]],
  ['documentation_20auto_5fscrollbar_20md_43',['oaGui/Documentation/auto_scrollbar.md',['../d8/d2b/md_oaGui_2Documentation_2auto__scrollbar.html',1,'']]],
  ['documentation_20builder_5ffooter_20md_44',['oaGui/Documentation/builder_footer.md',['../d8/d32/md_oaGui_2Documentation_2builder__footer.html',1,'']]],
  ['documentation_20builder_5flayout_5fmanager_20md_45',['oaGui/Documentation/builder_layout_manager.md',['../dc/def/md_oaGui_2Documentation_2builder__layout__manager.html',1,'']]],
  ['documentation_20cache_5fblueprint_5fstore_20py_46',['oaGui/Documentation/cache_blueprint_store.py',['../d1/da7/md_oaGui_2Documentation_2cache__blueprint__store.html',1,'']]],
  ['documentation_20cache_5fimage_5fstore_20md_47',['oaGui/Documentation/cache_image_store.md',['../d4/d4b/md_oaGui_2Documentation_2cache__image__store.html',1,'']]],
  ['documentation_20cache_5flayout_5fstore_20md_48',['oaGui/Documentation/cache_layout_store.md',['../d3/d23/md_oaGui_2Documentation_2cache__layout__store.html',1,'']]],
  ['documentation_20cache_5fwidget_5fcontext_20md_49',['oaGui/Documentation/cache_widget_context.md',['../d3/d7b/md_oaGui_2Documentation_2cache__widget__context.html',1,'']]],
  ['documentation_20canvas_5fviewport_5fmanager_20md_50',['oaGui/Documentation/Canvas_Viewport_Manager.md',['../d7/d98/md_oaGui_2Documentation_2Canvas__Viewport__Manager.html',1,'']]],
  ['documentation_20coordinate_5ftransformer_20md_51',['oaGui/Documentation/coordinate_transformer.md',['../d1/d25/md_oaGui_2Documentation_2coordinate__transformer.html',1,'']]],
  ['documentation_20engine_5fdestruction_5fservice_20md_52',['oaGui/Documentation/engine_destruction_service.md',['../d7/d33/md_oaGui_2Documentation_2engine__destruction__service.html',1,'']]],
  ['documentation_20engine_5fgrid_5flayout_5flogic_20md_53',['oaGui/Documentation/engine_grid_layout_logic.md',['../d8/d07/md_oaGui_2Documentation_2engine__grid__layout__logic.html',1,'']]],
  ['documentation_20engine_5fgui_5fdisplay_20md_54',['oaGui/Documentation/engine_gui_display.md',['../d6/d90/md_oaGui_2Documentation_2engine__gui__display.html',1,'']]],
  ['documentation_20engine_5frefresh_5fcoordinator_20md_55',['oaGui/Documentation/engine_refresh_coordinator.md',['../d8/d0b/md_oaGui_2Documentation_2engine__refresh__coordinator.html',1,'']]],
  ['documentation_20engine_5frender_5fscheduler_20md_56',['oaGui/Documentation/engine_render_scheduler.md',['../d5/dec/md_oaGui_2Documentation_2engine__render__scheduler.html',1,'']]],
  ['documentation_20engine_5fstructural_5fassembler_20md_57',['oaGui/Documentation/engine_structural_assembler.md',['../d3/d1a/md_oaGui_2Documentation_2engine__structural__assembler.html',1,'']]],
  ['documentation_20engine_5ftexture_5fmapper_20md_58',['oaGui/Documentation/engine_texture_mapper.md',['../d4/d02/md_oaGui_2Documentation_2engine__texture__mapper.html',1,'']]],
  ['documentation_20engine_5fvisual_5feffects_20md_59',['oaGui/Documentation/engine_visual_effects.md',['../de/d1f/md_oaGui_2Documentation_2engine__visual__effects.html',1,'']]],
  ['documentation_20engine_5fwidget_5fassembler_20md_60',['oaGui/Documentation/engine_widget_assembler.md',['../dd/dfa/md_oaGui_2Documentation_2engine__widget__assembler.html',1,'']]],
  ['documentation_20engine_5fwidget_5finstantiator_20md_61',['oaGui/Documentation/engine_widget_instantiator.md',['../d7/db0/md_oaGui_2Documentation_2engine__widget__instantiator.html',1,'']]],
  ['documentation_20entry_20md_62',['oaGui/Documentation/Entry.md',['../d7/d9f/md_oaGui_2Documentation_2Entry.html',1,'']]],
  ['documentation_20event_5fplaybook_20md_63',['oaComBroker/Documentation/Event_Playbook.md',['../dd/d49/md_oaComBroker_2Documentation_2Event__Playbook.html',1,'']]],
  ['documentation_20folder_5ffast_5fio_5futility_20md_64',['oaGui/Documentation/folder_fast_io_utility.md',['../d3/d3b/md_oaGui_2Documentation_2folder__fast__io__utility.html',1,'']]],
  ['documentation_20folder_5flayout_5finterpreter_20md_65',['oaGui/Documentation/folder_layout_interpreter.md',['../dd/d8c/md_oaGui_2Documentation_2folder__layout__interpreter.html',1,'']]],
  ['documentation_20folder_5fpath_5fresolver_20md_66',['oaGui/Documentation/folder_path_resolver.md',['../d0/d72/md_oaGui_2Documentation_2folder__path__resolver.html',1,'']]],
  ['documentation_20folder_5frecursive_5fscanner_20md_67',['oaGui/Documentation/folder_recursive_scanner.md',['../dc/d24/md_oaGui_2Documentation_2folder__recursive__scanner.html',1,'']]],
  ['documentation_20interaction_5fdispatcher_20md_68',['oaGui/Documentation/interaction_dispatcher.md',['../d0/ddf/md_oaGui_2Documentation_2interaction__dispatcher.html',1,'']]],
  ['documentation_20interaction_5fmqtt_5fgateway_20md_69',['oaGui/Documentation/interaction_mqtt_gateway.md',['../de/d8a/md_oaGui_2Documentation_2interaction__mqtt__gateway.html',1,'']]],
  ['documentation_20interaction_5fnavigation_20md_70',['oaGui/Documentation/interaction_navigation.md',['../da/da0/md_oaGui_2Documentation_2interaction__navigation.html',1,'']]],
  ['documentation_20interaction_5ftelemetry_5fservice_20md_71',['oaGui/Documentation/interaction_telemetry_service.md',['../da/d33/md_oaGui_2Documentation_2interaction__telemetry__service.html',1,'']]],
  ['documentation_20interaction_5fview_5fstates_20md_72',['oaGui/Documentation/interaction_view_states.md',['../d1/d32/md_oaGui_2Documentation_2interaction__view__states.html',1,'']]],
  ['documentation_20json_5fblueprint_5freader_20md_73',['oaGui/Documentation/json_blueprint_reader.md',['../d4/d21/md_oaGui_2Documentation_2json__blueprint__reader.html',1,'']]],
  ['documentation_20json_5fgui_5fhost_20md_74',['oaGui/Documentation/json_gui_host.md',['../d8/d2a/md_oaGui_2Documentation_2json__gui__host.html',1,'']]],
  ['documentation_20json_5fintegrity_5fvalidator_20md_75',['oaGui/Documentation/json_integrity_validator.md',['../de/d43/md_oaGui_2Documentation_2json__integrity__validator.html',1,'']]],
  ['documentation_20json_5fschema_5fharmonizer_20md_76',['oaGui/Documentation/json_schema_harmonizer.md',['../dd/d66/md_oaGui_2Documentation_2json__schema__harmonizer.html',1,'']]],
  ['documentation_20json_5fschema_5fnormalizer_20md_77',['oaGui/Documentation/json_schema_normalizer.md',['../d8/d14/md_oaGui_2Documentation_2json__schema__normalizer.html',1,'']]],
  ['documentation_20json_5fshorthand_5fresolver_20md_78',['oaGui/Documentation/json_shorthand_resolver.md',['../df/d36/md_oaGui_2Documentation_2json__shorthand__resolver.html',1,'']]],
  ['documentation_20loader_5fbootstrap_5fengine_20md_79',['oaGui/Documentation/loader_bootstrap_engine.md',['../da/d20/md_oaGui_2Documentation_2loader__bootstrap__engine.html',1,'']]],
  ['documentation_20loader_5ffacade_20md_80',['oaGui/Documentation/loader_facade.md',['../da/de9/md_oaGui_2Documentation_2loader__facade.html',1,'']]],
  ['documentation_20loader_5flifecycle_5fservice_20md_81',['oaGui/Documentation/loader_lifecycle_service.md',['../d8/d51/md_oaGui_2Documentation_2loader__lifecycle__service.html',1,'']]],
  ['documentation_20loader_5fmain_5fservice_20md_82',['oaGui/Documentation/loader_main_service.md',['../d6/de0/md_oaGui_2Documentation_2loader__main__service.html',1,'']]],
  ['documentation_20loader_5forchestrator_20md_83',['oaGui/Documentation/loader_orchestrator.md',['../d4/dce/md_oaGui_2Documentation_2loader__orchestrator.html',1,'']]],
  ['documentation_20loader_5fpython_5fengine_20md_84',['oaGui/Documentation/loader_python_engine.md',['../d7/d97/md_oaGui_2Documentation_2loader__python__engine.html',1,'']]],
  ['documentation_20loader_5fservice_5fcomposer_20md_85',['oaGui/Documentation/loader_service_composer.md',['../d2/da6/md_oaGui_2Documentation_2loader__service__composer.html',1,'']]],
  ['documentation_20loader_5fshutdown_5fservice_20md_86',['oaGui/Documentation/loader_shutdown_service.md',['../d9/dee/md_oaGui_2Documentation_2loader__shutdown__service.html',1,'']]],
  ['documentation_20loader_5fsignal_5fhandler_20md_87',['oaGui/Documentation/loader_signal_handler.md',['../dd/ddc/md_oaGui_2Documentation_2loader__signal__handler.html',1,'']]],
  ['documentation_20map_88',['🗺️ OPEN-AIR Documentation Map',['../d0/d4b/md_oaDocumentation_2Documentation_2Project__Map_2Documentation__Map.html',1,'']]],
  ['documentation_20oacombroker_20md_89',['oaComBroker/Documentation/oaComBroker.md',['../d2/dd4/md_oaComBroker_2Documentation_2oaComBroker.html',1,'']]],
  ['documentation_20open_5fair_5fcore_20md_90',['oaComBroker/Documentation/open_air_core.md',['../d6/d56/md_oaComBroker_2Documentation_2open__air__core.html',1,'']]],
  ['documentation_20registry_5fwidget_5fstore_20md_91',['oaGui/Documentation/registry_widget_store.md',['../d3/de5/md_oaGui_2Documentation_2registry__widget__store.html',1,'']]],
  ['documentation_20summary_20md_92',['documentation summary md',['../dd/dda/md_oaComBroker_2Documentation_2Summary.html',1,'oaComBroker/Documentation/Summary.md'],['../de/dd6/md_oaGui_2Documentation_2Summary.html',1,'oaGui/Documentation/Summary.md']]],
  ['documentation_20sync_5fbehavior_20md_93',['oaGui/Documentation/sync_behavior.md',['../de/d77/md_oaGui_2Documentation_2sync__behavior.html',1,'']]],
  ['documentation_20tab_5forchestrator_20md_94',['oaGui/Documentation/tab_orchestrator.md',['../d0/d75/md_oaGui_2Documentation_2tab__orchestrator.html',1,'']]],
  ['documentation_20tab_5fphysical_5fwindow_20md_95',['oaGui/Documentation/tab_physical_window.md',['../df/d2a/md_oaGui_2Documentation_2tab__physical__window.html',1,'']]],
  ['documentation_20tab_5fwindow_5fmanager_20md_96',['oaGui/Documentation/tab_window_manager.md',['../d7/d01/md_oaGui_2Documentation_2tab__window__manager.html',1,'']]],
  ['documentation_20top_5ftoolbar_20md_97',['oaGui/Documentation/top_toolbar.md',['../d5/d1e/md_oaGui_2Documentation_2top__toolbar.html',1,'']]],
  ['documentation_20wysiwyg_5feditor_20md_98',['oaGuiEditorWYSIWYG/Documentation/wysiwyg_editor.md',['../dc/d8a/md_oaGuiEditorWYSIWYG_2Documentation_2wysiwyg__editor.html',1,'']]],
  ['dragging_20disabled_99',['BUG: PanedWindow Sash Dragging Disabled',['../dd/d98/md_oaDocumentation_2Workers_2BugLog_2BUG__20260314__191713.html',1,'']]],
  ['draw_20bargraph_100',['🏷️ Worker Showtime Draw Bargraph',['../d8/d46/md_oaGuiShowtime_2Documentation_2draw__bargraph.html',1,'']]],
  ['drawings_101',['Drawings',['../dc/d66/md_oaDocumentation_2Documentation_2Patent_204__drawings.html',1,'']]],
  ['dropdown_20option_102',['🏷️ Text Gui Dropdown Option',['../d8/dd9/md_oaGuiElements_2Documentation_2text__gui__dropdown__option.html',1,'']]],
  ['dual_103',['🏷️ Fader Dual',['../d5/dfd/md_oaGuiElements_2Documentation_2fader__dual.html',1,'']]],
  ['dualfader_20—_20two_20handle_20fader_104',['DualFader — two-handle fader',['../d8/d18/md_frontEnd_2libControl_2faders_2DualFader_2Readme.html',1,'']]],
  ['due_20to_20cache_20corruption_105',['Bug Report: UI Rendering Failure (Empty Screen) due to Cache Corruption',['../d1/df6/md_oaDocumentation_2Workers_2BugLog_2BUG__20260315__225500.html',1,'']]],
  ['during_20core_20startup_106',['Bug Report: MqttConnectionManager AttributeError during Core Startup',['../d9/d51/md_oaDocumentation_2Workers_2BugLog_2BUG__20260314__220700.html',1,'']]],
  ['dynamic_20bar_20graph_107',['🏷️ Dynamic Bar Graph',['../d4/d6a/md_oaGuiElements_2Documentation_2dynamic__bar__graph.html',1,'']]],
  ['dynamic_20graph_108',['🏷️ Dynamic Graph',['../de/d99/md_oaGuiElements_2Documentation_2dynamic__graph.html',1,'']]],
  ['dynamic_20gui_20mousewheel_20mixin_109',['🏷️ Test Dynamic Gui Mousewheel Mixin',['../d9/d6e/md_oaGuiElements_2Documentation_2test__dynamic__gui__mousewheel__mixin.html',1,'']]],
  ['dynamic_20guis_110',['Bug Report: Broken Scrolling and Invisible Components in Dynamic GUIs',['../d1/d81/md_oaDocumentation_2Workers_2BugLog_2BUG__20260320__003000.html',1,'']]],
  ['dynamicgraph_20—_20live_20echarts_20graph_111',['DynamicGraph — live ECharts graph',['../d6/d0b/md_frontEnd_2libControl_2graphing_2DynamicGraph_2Readme.html',1,'']]]
];
