var searchData=
[
  ['data_0',['data',['../d6/dd4/md_oaGuiElements_2Documentation_2lyrics.html',1,'🏷️ Lyrics Data'],['../d6/dbe/md_oaComProtocols_2oaComNmos_2Core_2IS12_2Documentation_2is-12_2releases_2v1_80_81_2APIs_2schemas_2with-refs_2event-data.html',1,'event-data'],['../d5/db8/md_oaComProtocols_2oaComNmos_2Core_2IS12_2Documentation_2is-12_2releases_2v1_80_81_2APIs_2schemas_2resolved_2event-data.html',1,'event-data'],['../d4/da0/md_oaComProtocols_2oaComNmos_2Core_2IS12_2Documentation_2is-12_2releases_2v1_80_81_2APIs_2schemas_2event-data.html',1,'event-data'],['../d9/d88/md_oaComProtocols_2oaComNmos_2Core_2IS12_2Documentation_2is-12_2releases_2v1_80_81_2APIs_2schemac994bfba38e65fee2f68bea53c457758.html',1,'property-changed-event-data'],['../d7/d56/md_oaComProtocols_2oaComNmos_2Core_2IS12_2Documentation_2is-12_2releases_2v1_80_81_2APIs_2schema3a9169d22456c62bc08574ef4cdc9b15.html',1,'property-changed-event-data'],['../de/de1/md_oaComProtocols_2oaComNmos_2Core_2IS12_2Documentation_2is-12_2releases_2v1_80_81_2APIs_2schemas_2property-changed-event-data.html',1,'property-changed-event-data']]],
  ['data_20json_20tree_1',['🏷️ Data Json Tree',['../dd/dec/md_oaGuiElements_2Documentation_2json__tree.html',1,'']]],
  ['data_20radar_2',['🏷️ Data Radar',['../d0/d7b/md_oaGuiElements_2Documentation_2radar.html',1,'']]],
  ['data_5ftype_5fdefinition_5fdiscovery_3',['Data_type_definition_discovery',['../db/d13/md_oaComProtocols_2oaComNmos_2Core_2IS12_2Documentation_2is-12_2releases_2v1_80_81_2docs_2Data__type__definition__discovery.html',1,'']]],
  ['data_5ftype_5fmarshalling_4',['Data_type_marshalling',['../dc/d48/md_oaComProtocols_2oaComNmos_2Core_2IS12_2Documentation_2is-12_2releases_2v1_80_81_2docs_2Data__type__marshalling.html',1,'']]],
  ['deadband_20handler_5',['Deadband Handler',['../d1/d2d/md_oaSplinker_2Documentation_2handlers_2deadband.html',1,'']]],
  ['debounce_20handler_6',['Debounce Handler',['../db/d0f/md_oaSplinker_2Documentation_2handlers_2debounce.html',1,'']]],
  ['debugging_20overhaul_202026_2003_2014_7',['Bug Log: Reliability &amp; Debugging Overhaul (2026-03-14)',['../d6/d01/md_oaDocumentation_2Workers_2BugLog_2BUG__20260314__005023.html',1,'']]],
  ['dec_20buttons_8',['🏷️ Input Inc Dec Buttons',['../d6/d3f/md_oaGuiElements_2Documentation_2input__inc__dec__buttons.html',1,'']]],
  ['default_20message_9',['[2026-03-16 10:35:28 -0400] chore: Update project files (default message)',['../da/d7e/md_oaDocumentation_2Workers_2ChangeLog_2CHANGELOG__202602.html',1,'']]],
  ['delete_20open_20air_10',['🏷️ Delete Open Air',['../d7/d0b/md_oaComProtocols_2oaComMQTT_2Documentation_2delete__open__air.html',1,'']]],
  ['delete_5fsplink_11',['delete_splink',['../d1/dd5/md_oaSplinker_2Documentation_2functions_2delete__splink.html',1,'']]],
  ['dependencies_12',['📦 OPEN-AIR Project Dependencies',['../d9/da1/md_oaInstallation_2Documentation_2Dependencies.html',1,'']]],
  ['dependency_20refactor_13',['Bug Report: ImportError in VisaFleetManager (Circular Dependency Refactor)',['../d1/dc5/md_oaDocumentation_2Workers_2BugLog_2BUG__20260316__011800.html',1,'']]],
  ['description_20of_20the_20invention_14',['Description of the Invention',['../de/d63/md_oaDocumentation_2Documentation_2Patent_202__description.html',1,'']]],
  ['design_20lens_15',['Summary.md - The Design Lens',['../d2/d5a/md_oaGuiEditorWYSIWYG_2Documentation_2Summary.html',1,'']]],
  ['device_16',['🏷️ Preset From Device',['../de/da5/md_oaStateCache_2Documentation_2preset__from__device.html',1,'']]],
  ['dial_20value_17',['🏷️ Composite Horizontal Dial Value',['../da/d0b/md_oaGuiElements_2Documentation_2composite__horizontal__dial__value.html',1,'']]],
  ['directional_20buttons_18',['🏷️ Input Directional Buttons',['../dc/d47/md_oaGuiElements_2Documentation_2input__directional__buttons.html',1,'']]],
  ['directory_20based_20notebooks_19',['BUG: GUI Layout Regression for Directory-Based Notebooks',['../df/d55/md_oaDocumentation_2Workers_2BugLog_2BUG__20260314__170217.html',1,'']]],
  ['directory_20name_20parsing_20',['BUG: GUI Layout Regression from Directory Name Parsing',['../db/dbe/md_oaDocumentation_2Workers_2BugLog_2BUG__20260314__161529.html',1,'']]],
  ['disabled_21',['BUG: PanedWindow Sash Dragging Disabled',['../dd/d98/md_oaDocumentation_2Workers_2BugLog_2BUG__20260314__191713.html',1,'']]],
  ['disconnect_20instrument_22',['🏷️ Manager Logic Disconnect Instrument',['../d8/dbc/md_oaComProtocols_2oaComVisa_2Documentation_2logic__disconnect__instrument.html',1,'']]],
  ['discovery_20errors_23',['Bug Report: Graphing Mapping and VISA Discovery Errors',['../db/d1a/md_oaDocumentation_2Workers_2BugLog_2BUG__20260316__011000.html',1,'']]],
  ['discovery_20importerror_24',['Bug Report: Test Discovery ImportError',['../d7/df4/md_oaDocumentation_2Workers_2BugLog_2BUG__20260409__002000.html',1,'']]],
  ['discovery_20orchestrator_25',['🏷️ Discovery Orchestrator',['../d6/d6f/md_oaComProtocols_2oaComVisa_2Documentation_2discovery__orchestrator.html',1,'']]],
  ['dispatch_26',['BUG: Catastrophic Failure of Core Protocol Dispatch',['../df/d86/md_oaDocumentation_2Workers_2BugLog_2BUG__20260314__193426__CORE__SYSTEMS__MEGAFIX.html',1,'']]],
  ['dispatch_20attributeerror_27',['Bug Report: UI Startup Crash and Protocol Dispatch AttributeError',['../db/dd7/md_oaDocumentation_2Workers_2BugLog_2BUG__20260314__234500.html',1,'']]],
  ['displacement_20potentiometer_28',['🏷️ Circular Motion Displacement Potentiometer',['../d1/dbc/md_oaGuiElements_2Documentation_2circular__motion__displacement__potentiometer.html',1,'']]],
  ['display_29',['display',['../d8/daf/md_oaGuiElements_2Documentation_2images__animation__display.html',1,'🏷️ Images Animation Display'],['../d3/d1f/md_oaGuiElements_2Documentation_2images__image__display.html',1,'🏷️ Images Image Display']]],
  ['display_20issue_30',['Bug Report: GraphPlotter Display Issue',['../d1/d21/md_oaDocumentation_2BugLog_2BUG__20260403__021630.html',1,'']]],
  ['display_20move_31',['Bug Report: UI Window Collapsing on Display Move',['../d8/dde/md_oaDocumentation_2Workers_2BugLog_2BUG__20260316__012300.html',1,'']]],
  ['display_20units_32',['🏷️ Meter To Display Units',['../db/d1f/md_oaGuiElements_2Documentation_2Meter__to__display__units.html',1,'']]],
  ['documentation_33',['documentation',['../d9/d69/md_oaComProtocols_2oaComAES70_2Documentation_2ProtocolShifter.html',1,'oaComAES70 Protocol Shifter Documentation'],['../d4/d37/md_oaComProtocols_2oaComEmber_2Documentation_2ProtocolShifter.html',1,'oaComEmber Protocol Shifter Documentation'],['../df/d23/md_oaComProtocols_2oaComMidi_2Documentation_2ProtocolShifter.html',1,'oaComMidi Protocol Shifter Documentation'],['../d3/d16/md_oaComProtocols_2oaComMQTT_2Documentation_2ProtocolShifter.html',1,'oaComMQTT Protocol Shifter Documentation'],['../d5/da9/md_oaComProtocols_2oaComNmos_2Documentation_2ProtocolShifter.html',1,'oaComNmos Protocol Shifter Documentation'],['../d5/d50/md_oaComProtocols_2oaComOSC_2Documentation_2OSCProtocolShifter.html',1,'oaComOSC Protocol Shifter Documentation'],['../d9/d2d/md_oaComProtocols_2oaComREST_2Documentation_2ProtocolShifter.html',1,'oaComREST Protocol Shifter Documentation'],['../dc/d6e/md_oaComProtocols_2oaComSMPTE2138_2Documentation_2ProtocolShifter.html',1,'oaComSMPTE2138 Protocol Shifter Documentation'],['../dc/d90/md_oaComProtocols_2oaComSNMP_2Documentation_2ProtocolShifter.html',1,'oaComSNMP Protocol Shifter Documentation'],['../da/d3d/md_oaComProtocols_2oaComVisa_2Documentation_2ProtocolShifter.html',1,'oaComVisa Protocol Shifter Documentation'],['../dd/d26/md_oaComProtocols_2oaComWebsocket_2Documentation_2ProtocolShifter.html',1,'oaComWebsocket Protocol Shifter Documentation']]],
  ['documentation_20event_5fplaybook_20md_34',['oaComBroker/Documentation/Event_Playbook.md',['../dd/d49/md_oaComBroker_2Documentation_2Event__Playbook.html',1,'']]],
  ['documentation_20map_35',['🗺️ OPEN-AIR Documentation Map',['../d0/d4b/md_oaDocumentation_2Documentation_2Project__Map_2Documentation__Map.html',1,'']]],
  ['documentation_20oacombroker_20md_36',['oaComBroker/Documentation/oaComBroker.md',['../d2/dd4/md_oaComBroker_2Documentation_2oaComBroker.html',1,'']]],
  ['documentation_20open_5fair_5fcore_20md_37',['oaComBroker/Documentation/open_air_core.md',['../d6/d56/md_oaComBroker_2Documentation_2open__air__core.html',1,'']]],
  ['documentation_20readme_20md_38',['oaComBroker/Documentation/README.md',['../index.html',1,'']]],
  ['documentation_20summary_20md_39',['oaComBroker/Documentation/Summary.md',['../dd/dda/md_oaComBroker_2Documentation_2Summary.html',1,'']]],
  ['documentation_20wysiwyg_5feditor_20md_40',['oaGuiEditorWYSIWYG/Documentation/wysiwyg_editor.md',['../dc/d8a/md_oaGuiEditorWYSIWYG_2Documentation_2wysiwyg__editor.html',1,'']]],
  ['dragging_20disabled_41',['BUG: PanedWindow Sash Dragging Disabled',['../dd/d98/md_oaDocumentation_2Workers_2BugLog_2BUG__20260314__191713.html',1,'']]],
  ['draw_20bargraph_42',['🏷️ Worker Showtime Draw Bargraph',['../d8/d46/md_oaGuiShowtime_2Documentation_2draw__bargraph.html',1,'']]],
  ['drawings_43',['Drawings',['../dc/d66/md_oaDocumentation_2Documentation_2Patent_204__drawings.html',1,'']]],
  ['dropdown_20option_44',['🏷️ Text Gui Dropdown Option',['../d8/dd9/md_oaGuiElements_2Documentation_2text__gui__dropdown__option.html',1,'']]],
  ['dual_45',['🏷️ Fader Dual',['../d5/dfd/md_oaGuiElements_2Documentation_2fader__dual.html',1,'']]],
  ['due_20to_20cache_20corruption_46',['Bug Report: UI Rendering Failure (Empty Screen) due to Cache Corruption',['../d1/df6/md_oaDocumentation_2Workers_2BugLog_2BUG__20260315__225500.html',1,'']]],
  ['during_20core_20startup_47',['Bug Report: MqttConnectionManager AttributeError during Core Startup',['../d9/d51/md_oaDocumentation_2Workers_2BugLog_2BUG__20260314__220700.html',1,'']]],
  ['dynamic_20bar_20graph_48',['🏷️ Dynamic Bar Graph',['../d4/d6a/md_oaGuiElements_2Documentation_2dynamic__bar__graph.html',1,'']]],
  ['dynamic_20graph_49',['🏷️ Dynamic Graph',['../de/d99/md_oaGuiElements_2Documentation_2dynamic__graph.html',1,'']]],
  ['dynamic_20gui_20mousewheel_20mixin_50',['🏷️ Test Dynamic Gui Mousewheel Mixin',['../d9/d6e/md_oaGuiElements_2Documentation_2test__dynamic__gui__mousewheel__mixin.html',1,'']]],
  ['dynamic_20guis_51',['Bug Report: Broken Scrolling and Invisible Components in Dynamic GUIs',['../d1/d81/md_oaDocumentation_2Workers_2BugLog_2BUG__20260320__003000.html',1,'']]],
  ['dynamicguibuilder_52',['Bug Report: ModuleNotFoundError in DynamicGuiBuilder',['../d3/daf/md_oaDocumentation_2Workers_2BugLog_2BUG__20260316__005200.html',1,'']]]
];
