; Changes to config will only take effect after a restart of application or service

; Paths separated by '|'
; Example: CSV_PATHS = /this/is/a/path|/now/this/is/another/path/|/path/number/three
CSV_PATHS = sample_data.csv
PORTNUM = 9000 ; Default is 9000
