# Core/process_router_event.py
# Author: Anthony Peter Kuzub
# Version: 1.0.0
#
# Description: Brief summary of purpose

import threading
from ..Methods.pipeline import SplinkPipeline

def process_router_event(self, msg):
    self._notify_monitor("router_event", msg)
    
    # ⚡ PANIC CHECK: Bail immediately if emergency stop is active
    if self.panic_active:
        return

    topic, val, source = msg.get("topic"), msg.get("val"), msg.get("source")
    logical_source = msg.get("logical_source", source)
    ts = msg.get("ts")
    
    if not topic:
        return

    # ⚡ LOOP PREVENTION: Ignore messages generated by Splinker (Logical or Transport)
    if source == "SPLINKER" or logical_source == "SPLINKER":
        return
    
    # ⚡ LOOP PREVENTION: Ignore messages with splinker metadata (for MQTT bounceback)
    meta = msg.get("meta", {})
    if isinstance(meta, dict) and (meta.get("splinker_source") or meta.get("splink_active")):
        return
    
    # ⚡ BOOT SEQUENCE: Ignore disk restoration floods
    if isinstance(meta, dict) and meta.get("boot"):
        return
    
    # ⚡ LOOP PREVENTION: Ignore GUID suffixes
    if str(msg.get("guid", "")).endswith("-SPLINK"):
        return

    # --- Handle Commands directly from Router ---
    if "OPEN-AIR/System/Control/Splinker/" in topic:
        # ⚡ BUG FIX: For control topics, the 'value' might be None if it wasn't wrapped in 'val'.
        # In that case, the raw payload is in the metadata.
        cmd_payload = val
        if cmd_payload is None and isinstance(msg.get("meta"), dict):
            # If the whole packet was a JSON dict but had no 'val', the router put it in 'meta'
            cmd_payload = msg["meta"]
            
        self._handle_command(topic, cmd_payload)
        return

    if self.learning_source:
        self._handle_learn(topic)
        return
    if self.teaching_dest:
        self._handle_teach(topic)
        return

    for s in self.splinks:
        if not s.get("active", False): continue
        
        # ⚡ FEEDBACK DETECTION: Track message rate for this splink
        # If rate exceeds threshold (e.g. 25 msgs/sec), trigger emergency stop.
        import time
        now = time.time()
        with self._counter_lock:
            ts_list = self.event_counters.setdefault(s["id"], [])
            ts_list.append(now)
            # Prune timestamps older than 1 second
            self.event_counters[s["id"]] = [t for t in ts_list if now - t < 1.0]
            if len(self.event_counters[s["id"]]) > 25:
                # 🔥 EMERGENCY TRIGGER
                self._handle_panic(trigger_splink_id=s["id"])
                return

        # ⚡ LOOP PREVENTION: Have we already processed THIS event with THIS splink?
        # Use (ts, topic, splink_id) to uniquely identify the operation across partitions
        cache_key = (ts, topic, s["id"])
        with self._cache_lock:
            if cache_key in self.processed_events:
                continue
            self.processed_events[cache_key] = True
            # Trim cache if it gets too big
            if len(self.processed_events) > 5000:
                # Keep latest 2000
                self.processed_events = dict(list(self.processed_events.items())[-2000:])

        # ⚡ EXECUTION LOCK: Prevent recursive re-entry for the SAME splink in THIS partition
        # If this splink is ALREADY busy processing, skip this event to break feedback loops.
        with self._exec_registry_lock:
            if s["id"] not in self.execution_locks:
                self.execution_locks[s["id"]] = threading.Lock()
            splink_lock = self.execution_locks[s["id"]]
        
        # Attempt to acquire the lock WITHOUT blocking
        if not splink_lock.acquire(blocking=False):
            # This splink is currently active. Skip this trigger to prevent recursion.
            continue
            
        try:
            # ⚡ SUB-PATH LOGIC: Check if topic matches base or sub-path
            src_topic, src_key = self._parse_splink_path(s.get("source"))
            dest_topic, dest_key = self._parse_splink_path(s.get("dest"))

            # --- SPLICE: Source -> Destination ---
            if topic == src_topic and s["mode"] in ["SPLICE", "SPLINK", "BOTH"]:
                input_val = val
                if src_key and isinstance(val, dict):
                    input_val = val.get(src_key)
                
                if input_val is not None:
                    pipeline = SplinkPipeline(s, self)
                    splink_state = self.splink_states.setdefault(s["id"], {})
                    
                    # ⚡ STATEFUL CACHE: Preserve original identity in the splink state
                    splink_state["original_ts"] = msg.get("ts")
                    splink_state["original_guid"] = msg.get("logical_guid") or msg.get("guid")
                    
                    # ⚡ ANTI-FEEDBACK SPEC: Carry over spec fields
                    splink_state["msg_guid"] = msg.get("msg_guid")
                    splink_state["msg_type"] = msg.get("msg_type")
                    splink_state["origin_source"] = msg.get("origin_source")
                    
                    processed_val = pipeline.process(input_val, splink_state, direction="FORWARD")
                    
                    if processed_val is not None:
                        # ⚡ TAG METADATA: Notify the router/firehose that this message triggered a splink
                        msg.setdefault("meta", {})["splink_active"] = True
                        msg["meta"]["splink_id"] = s["id"]
                        msg["meta"]["splink_dest"] = s["dest"]
                        
                        self._broker_splice(s, processed_val, source, original_msg=msg)

            # --- LINK: Destination -> Source (Bidirectional) ---
            if topic == dest_topic and s["mode"] in ["LINK", "SPLINK", "BOTH"]:
                input_val = val
                if dest_key and isinstance(val, dict):
                    input_val = val.get(dest_key)
                
                if input_val is not None:
                    pipeline = SplinkPipeline(s, self)
                    splink_state = self.splink_states.setdefault(s["id"], {})
                    
                    # ⚡ STATEFUL CACHE: Preserve original identity
                    splink_state["original_ts"] = msg.get("ts")
                    splink_state["original_guid"] = msg.get("logical_guid") or msg.get("guid")
                    
                    # ⚡ ANTI-FEEDBACK SPEC: Carry over spec fields
                    splink_state["msg_guid"] = msg.get("msg_guid")
                    splink_state["msg_type"] = msg.get("msg_type")
                    splink_state["origin_source"] = msg.get("origin_source")
                    
                    processed_val = pipeline.process(input_val, splink_state, direction="REVERSE")
                    
                    if processed_val is not None:
                        # ⚡ TAG METADATA
                        msg.setdefault("meta", {})["splink_active"] = True
                        msg["meta"]["splink_id"] = s["id"]
                        msg["meta"]["splink_dest"] = s["source"]
                        
                        self._broker_link(s, processed_val, source, original_msg=msg)
        finally:
            # ALWAYS release the lock
            splink_lock.release()
