//! openair-contracts — the Rust mirror of `@openair/contracts`.
//!
//! `topics`, `identity`, and `time` are HAND-WRITTEN (behavior, not shape)
//! and kept honest against the TypeScript implementations by the shared
//! golden-vector files under `contracts/vectors/`. `gen/` is cargo-typify
//! output regenerated by `pnpm gen` — never edited by hand. `heartbeat` and
//! `device_record` are thin wrappers: re-exports of the generated types plus
//! the behavior half of each contract (LWT helper, v40 mapping).

pub mod gen;

pub mod topics;

pub mod identity;

pub mod time;

pub mod heartbeat;

pub mod device_record;
