OPENAIR-MIB DEFINITIONS ::= BEGIN

IMPORTS
    MODULE-IDENTITY, OBJECT-TYPE, enterprises FROM SNMPv2-SMI
    DisplayString FROM SNMPv2-TC;

openAirMIB MODULE-IDENTITY
    LAST-UPDATED "202603190136Z"
    ORGANIZATION "OPEN-AIR Project"
    CONTACT-INFO "Anthony Peter Kuzub"
    DESCRIPTION "MQTT-Aligned OID Tree for OPEN-AIR."
    REVISION "202603190136Z"
    DESCRIPTION "Strictly unique path-aligned generation."
    ::= { enterprises 25030 }

v1 OBJECT IDENTIFIER ::= { openAirMIB 1 }

spectrumff5d OBJECT IDENTIFIER ::= { v1 4582 }
instrument36ce OBJECT IDENTIFIER ::= { spectrumff5d 59555 }
amplitudea555 OBJECT IDENTIFIER ::= { instrument36ce 33244 }
spectrumInstrumentamplitude5e63 OBJECT IDENTIFIER ::= { amplitudea555 45921 }
blocks9f69 OBJECT IDENTIFIER ::= { spectrumInstrumentamplitude5e63 61782 }
referenceLevel6ffc OBJECT IDENTIFIER ::= { blocks9f69 12556 }
refleveldBmb3ba OBJECT IDENTIFIER ::= { referenceLevel6ffc 55167 }
-- MQTT: OPEN-AIR/Spectrum/Instrument/amplitude/Spectrum_Instrument_amplitude/blocks/Reference Level/ref_level_dBm/dial_config
dialconfig3881 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Spectrum/Instrument/amplitude/Spectrum_Instrument_amplitude/blocks/Reference Level/ref_level_dBm/dial_config"
    ::= { refleveldBmb3ba 31585 }

-- MQTT: OPEN-AIR/Spectrum/Instrument/amplitude/Spectrum_Instrument_amplitude/blocks/Reference Level/ref_level_dBm/fader_config
faderconfig3052 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Spectrum/Instrument/amplitude/Spectrum_Instrument_amplitude/blocks/Reference Level/ref_level_dBm/fader_config"
    ::= { refleveldBmb3ba 55856 }

frequencye887 OBJECT IDENTIFIER ::= { instrument36ce 41438 }
spectrumInstrumentfrequency7dc9 OBJECT IDENTIFIER ::= { frequencye887 42633 }
blocks742d OBJECT IDENTIFIER ::= { spectrumInstrumentfrequency7dc9 3561 }
startStop9226 OBJECT IDENTIFIER ::= { blocks742d 17133 }
-- MQTT: OPEN-AIR/Spectrum/Instrument/frequency/Spectrum_Instrument_frequency/blocks/Start Stop/start_freq_MHz
startfreqMHz5c5f OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Spectrum/Instrument/frequency/Spectrum_Instrument_frequency/blocks/Start Stop/start_freq_MHz"
    ::= { startStop9226 25465 }

-- MQTT: OPEN-AIR/Spectrum/Instrument/frequency/Spectrum_Instrument_frequency/blocks/Start Stop/stop_freq_MHz
stopfreqMHzde28 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Spectrum/Instrument/frequency/Spectrum_Instrument_frequency/blocks/Start Stop/stop_freq_MHz"
    ::= { startStop9226 30134 }

frequencydd46 OBJECT IDENTIFIER ::= { blocks742d 57029 }
-- MQTT: OPEN-AIR/Spectrum/Instrument/frequency/Spectrum_Instrument_frequency/blocks/Frequency/span_freq_MHz
spanfreqMHzab37 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Spectrum/Instrument/frequency/Spectrum_Instrument_frequency/blocks/Frequency/span_freq_MHz"
    ::= { frequencydd46 2413 }

-- MQTT: OPEN-AIR/Spectrum/Instrument/frequency/Spectrum_Instrument_frequency/blocks/Frequency/center_freq_MHz
centerfreqMHzceb3 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Spectrum/Instrument/frequency/Spectrum_Instrument_frequency/blocks/Frequency/center_freq_MHz"
    ::= { frequencydd46 4552 }

bandwidth44f1 OBJECT IDENTIFIER ::= { instrument36ce 52386 }
spectrumInstrumentbandwidth6f64 OBJECT IDENTIFIER ::= { bandwidth44f1 14112 }
blocks2839 OBJECT IDENTIFIER ::= { spectrumInstrumentbandwidth6f64 39553 }
videoBandwidthedb8 OBJECT IDENTIFIER ::= { blocks2839 13295 }
vbwMHzef31 OBJECT IDENTIFIER ::= { videoBandwidthedb8 64626 }
-- MQTT: OPEN-AIR/Spectrum/Instrument/bandwidth/Spectrum_Instrument_bandwidth/blocks/Video Bandwidth/vbw_MHz/dial_config
dialconfig8910 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Spectrum/Instrument/bandwidth/Spectrum_Instrument_bandwidth/blocks/Video Bandwidth/vbw_MHz/dial_config"
    ::= { vbwMHzef31 12936 }

resolutionBandwidthbba6 OBJECT IDENTIFIER ::= { blocks2839 16920 }
rBW5597 OBJECT IDENTIFIER ::= { resolutionBandwidthbba6 26181 }
-- MQTT: OPEN-AIR/Spectrum/Instrument/bandwidth/Spectrum_Instrument_bandwidth/blocks/Resolution Bandwidth/RBW/dial_config
dialconfigab15 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Spectrum/Instrument/bandwidth/Spectrum_Instrument_bandwidth/blocks/Resolution Bandwidth/RBW/dial_config"
    ::= { rBW5597 29766 }

-- MQTT: OPEN-AIR/Spectrum/Instrument/bandwidth/Spectrum_Instrument_bandwidth/blocks/Resolution Bandwidth/RBW/fader_config
faderconfig95cb OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Spectrum/Instrument/bandwidth/Spectrum_Instrument_bandwidth/blocks/Resolution Bandwidth/RBW/fader_config"
    ::= { rBW5597 64340 }

unknownInstrument319b OBJECT IDENTIFIER ::= { v1 7871 }
yAKb471 OBJECT IDENTIFIER ::= { unknownInstrument319b 21184 }
unknown9eeb OBJECT IDENTIFIER ::= { yAKb471 6195 }
connectionb306 OBJECT IDENTIFIER ::= { unknown9eeb 33817 }
tablef5ff OBJECT IDENTIFIER ::= { connectionb306 13455 }
-- MQTT: OPEN-AIR/Unknown Instrument/YAK/Unknown/Connection/Table/type
typeb385 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Unknown Instrument/YAK/Unknown/Connection/Table/type"
    ::= { tablef5ff 44637 }

-- MQTT: OPEN-AIR/Unknown Instrument/YAK/Unknown/Connection/Table/description
descriptiona0d5 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Unknown Instrument/YAK/Unknown/Connection/Table/description"
    ::= { tablef5ff 60130 }

zoo994f OBJECT IDENTIFIER ::= { v1 16181 }
knobse91c OBJECT IDENTIFIER ::= { zoo994f 1999 }
knobs410d OBJECT IDENTIFIER ::= { knobse91c 1771 }
knobf1d1 OBJECT IDENTIFIER ::= { knobs410d 60153 }
zooKnobsknobsknobf7af OBJECT IDENTIFIER ::= { knobf1d1 51839 }
blocks9823 OBJECT IDENTIFIER ::= { zooKnobsknobsknobf7af 6553 }
knobZooDriveb444 OBJECT IDENTIFIER ::= { blocks9823 35333 }
-- MQTT: OPEN-AIR/Zoo/Knobs/knobs/knob/Zoo_Knobs_knobs_knob_1/blocks/Knob_Zoo_Drive/knob_drv3
knobdrv8d31 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Knobs/knobs/knob/Zoo_Knobs_knobs_knob_1/blocks/Knob_Zoo_Drive/knob_drv3"
    ::= { knobZooDriveb444 53921 }

graphing1bf1 OBJECT IDENTIFIER ::= { zoo994f 5770 }
xYGraphsd2d9 OBJECT IDENTIFIER ::= { graphing1bf1 39645 }
graphing8b7b OBJECT IDENTIFIER ::= { xYGraphsd2d9 25912 }
zoodatagraphingXYGraphsGraphing6b37 OBJECT IDENTIFIER ::= { graphing8b7b 4064 }
blocksd666 OBJECT IDENTIFIER ::= { zoodatagraphingXYGraphsGraphing6b37 41606 }
blueprintPlot38a3 OBJECT IDENTIFIER ::= { blocksd666 23985 }
oaDataRunningFilesebb9 OBJECT IDENTIFIER ::= { blueprintPlot38a3 48208 }
-- MQTT: OPEN-AIR/Zoo/graphing/XY_Graphs/Graphing/Zoo_data_graphing_XY_Graphs_Graphing_1/blocks/Blueprint_Plot/oaDataRunningFiles/blueprint_line
blueprintline1cd7 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/graphing/XY_Graphs/Graphing/Zoo_data_graphing_XY_Graphs_Graphing_1/blocks/Blueprint_Plot/oaDataRunningFiles/blueprint_line"
    ::= { oaDataRunningFilesebb9 16352 }

comparisonPlot5606 OBJECT IDENTIFIER ::= { blocksd666 28027 }
oaDataRunningFiles4b12 OBJECT IDENTIFIER ::= { comparisonPlot5606 6598 }
-- MQTT: OPEN-AIR/Zoo/graphing/XY_Graphs/Graphing/Zoo_data_graphing_XY_Graphs_Graphing_1/blocks/Comparison_Plot/oaDataRunningFiles/A
a90bb OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/graphing/XY_Graphs/Graphing/Zoo_data_graphing_XY_Graphs_Graphing_1/blocks/Comparison_Plot/oaDataRunningFiles/A"
    ::= { oaDataRunningFiles4b12 59462 }

manyLines47a9 OBJECT IDENTIFIER ::= { blocksd666 38023 }
oaDataRunningFiles6851 OBJECT IDENTIFIER ::= { manyLines47a9 20934 }
-- MQTT: OPEN-AIR/Zoo/graphing/XY_Graphs/Graphing/Zoo_data_graphing_XY_Graphs_Graphing_1/blocks/Many_Lines/oaDataRunningFiles/line1
linea17e OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/graphing/XY_Graphs/Graphing/Zoo_data_graphing_XY_Graphs_Graphing_1/blocks/Many_Lines/oaDataRunningFiles/line1"
    ::= { oaDataRunningFiles6851 42234 }

sunsetPlot2120 OBJECT IDENTIFIER ::= { blocksd666 38298 }
oaDataRunningFilesb637 OBJECT IDENTIFIER ::= { sunsetPlot2120 51625 }
-- MQTT: OPEN-AIR/Zoo/graphing/XY_Graphs/Graphing/Zoo_data_graphing_XY_Graphs_Graphing_1/blocks/Sunset_Plot/oaDataRunningFiles/hill1
hill7360 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/graphing/XY_Graphs/Graphing/Zoo_data_graphing_XY_Graphs_Graphing_1/blocks/Sunset_Plot/oaDataRunningFiles/hill1"
    ::= { oaDataRunningFilesb637 3238 }

ultraMinimalist6566 OBJECT IDENTIFIER ::= { blocksd666 55713 }
oaDataRunningFiles8f4f OBJECT IDENTIFIER ::= { ultraMinimalist6566 32368 }
-- MQTT: OPEN-AIR/Zoo/graphing/XY_Graphs/Graphing/Zoo_data_graphing_XY_Graphs_Graphing_1/blocks/Ultra_Minimalist/oaDataRunningFiles/single_line
singleline15b2 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/graphing/XY_Graphs/Graphing/Zoo_data_graphing_XY_Graphs_Graphing_1/blocks/Ultra_Minimalist/oaDataRunningFiles/single_line"
    ::= { oaDataRunningFiles8f4f 35328 }

zoodatagraphingXYGraphsGraphingf23e OBJECT IDENTIFIER ::= { graphing8b7b 24154 }
blocks58e9 OBJECT IDENTIFIER ::= { zoodatagraphingXYGraphsGraphingf23e 42341 }
dampedSineWaveb23b OBJECT IDENTIFIER ::= { blocks58e9 20439 }
oaDataRunningFilesd51d OBJECT IDENTIFIER ::= { dampedSineWaveb23b 20535 }
-- MQTT: OPEN-AIR/Zoo/graphing/XY_Graphs/Graphing/Zoo_data_graphing_XY_Graphs_Graphing_2/blocks/Damped_Sine_Wave/oaDataRunningFiles/damped_sine
dampedsine5269 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/graphing/XY_Graphs/Graphing/Zoo_data_graphing_XY_Graphs_Graphing_2/blocks/Damped_Sine_Wave/oaDataRunningFiles/damped_sine"
    ::= { oaDataRunningFilesd51d 43463 }

quadraticPlot4e55 OBJECT IDENTIFIER ::= { blocks58e9 24212 }
oaDataRunningFilesb579 OBJECT IDENTIFIER ::= { quadraticPlot4e55 56907 }
-- MQTT: OPEN-AIR/Zoo/graphing/XY_Graphs/Graphing/Zoo_data_graphing_XY_Graphs_Graphing_2/blocks/Quadratic_Plot/oaDataRunningFiles/x_squared
xsquared4b1a OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/graphing/XY_Graphs/Graphing/Zoo_data_graphing_XY_Graphs_Graphing_2/blocks/Quadratic_Plot/oaDataRunningFiles/x_squared"
    ::= { oaDataRunningFilesb579 20826 }

squareRootPlotb3a5 OBJECT IDENTIFIER ::= { blocks58e9 30091 }
oaDataRunningFiles486f OBJECT IDENTIFIER ::= { squareRootPlotb3a5 36167 }
-- MQTT: OPEN-AIR/Zoo/graphing/XY_Graphs/Graphing/Zoo_data_graphing_XY_Graphs_Graphing_2/blocks/Square_Root_Plot/oaDataRunningFiles/sqrt_x
sqrtx7aee OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/graphing/XY_Graphs/Graphing/Zoo_data_graphing_XY_Graphs_Graphing_2/blocks/Square_Root_Plot/oaDataRunningFiles/sqrt_x"
    ::= { oaDataRunningFiles486f 60586 }

stepPlot5ea0 OBJECT IDENTIFIER ::= { blocks58e9 42832 }
oaDataRunningFiles810a OBJECT IDENTIFIER ::= { stepPlot5ea0 30405 }
-- MQTT: OPEN-AIR/Zoo/graphing/XY_Graphs/Graphing/Zoo_data_graphing_XY_Graphs_Graphing_2/blocks/Step_Plot/oaDataRunningFiles/step_data
stepdatafa3e OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/graphing/XY_Graphs/Graphing/Zoo_data_graphing_XY_Graphs_Graphing_2/blocks/Step_Plot/oaDataRunningFiles/step_data"
    ::= { oaDataRunningFiles810a 51331 }

randomWalka4bf OBJECT IDENTIFIER ::= { blocks58e9 59377 }
oaDataRunningFilesf60b OBJECT IDENTIFIER ::= { randomWalka4bf 26320 }
-- MQTT: OPEN-AIR/Zoo/graphing/XY_Graphs/Graphing/Zoo_data_graphing_XY_Graphs_Graphing_2/blocks/Random_Walk/oaDataRunningFiles/random
randoma2d3 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/graphing/XY_Graphs/Graphing/Zoo_data_graphing_XY_Graphs_Graphing_2/blocks/Random_Walk/oaDataRunningFiles/random"
    ::= { oaDataRunningFilesf60b 31253 }

faderse5a7 OBJECT IDENTIFIER ::= { zoo994f 10471 }
verticalc654 OBJECT IDENTIFIER ::= { faderse5a7 57 }
experimental17fd OBJECT IDENTIFIER ::= { verticalc654 19027 }
zooFadersVerticalExperimental5ea0 OBJECT IDENTIFIER ::= { experimental17fd 3350 }
blocks369c OBJECT IDENTIFIER ::= { zooFadersVerticalExperimental5ea0 14262 }
experimentalFaderRiotd184 OBJECT IDENTIFIER ::= { blocks369c 26108 }
-- MQTT: OPEN-AIR/Zoo/Faders/Vertical/Experimental/Zoo_Faders_Vertical_Experimental/blocks/Experimental_Fader_Riot/exp_13
exp6139 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Faders/Vertical/Experimental/Zoo_Faders_Vertical_Experimental/blocks/Experimental_Fader_Riot/exp_13"
    ::= { experimentalFaderRiotd184 2739 }

-- MQTT: OPEN-AIR/Zoo/Faders/Vertical/Experimental/Zoo_Faders_Vertical_Experimental/blocks/Experimental_Fader_Riot/exp_10
expf830 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Faders/Vertical/Experimental/Zoo_Faders_Vertical_Experimental/blocks/Experimental_Fader_Riot/exp_10"
    ::= { experimentalFaderRiotd184 23305 }

-- MQTT: OPEN-AIR/Zoo/Faders/Vertical/Experimental/Zoo_Faders_Vertical_Experimental/blocks/Experimental_Fader_Riot/exp_11
exp8f37 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Faders/Vertical/Experimental/Zoo_Faders_Vertical_Experimental/blocks/Experimental_Fader_Riot/exp_11"
    ::= { experimentalFaderRiotd184 27551 }

-- MQTT: OPEN-AIR/Zoo/Faders/Vertical/Experimental/Zoo_Faders_Vertical_Experimental/blocks/Experimental_Fader_Riot/exp_14
expff5d OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Faders/Vertical/Experimental/Zoo_Faders_Vertical_Experimental/blocks/Experimental_Fader_Riot/exp_14"
    ::= { experimentalFaderRiotd184 40720 }

-- MQTT: OPEN-AIR/Zoo/Faders/Vertical/Experimental/Zoo_Faders_Vertical_Experimental/blocks/Experimental_Fader_Riot/exp_15
exp885a OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Faders/Vertical/Experimental/Zoo_Faders_Vertical_Experimental/blocks/Experimental_Fader_Riot/exp_15"
    ::= { experimentalFaderRiotd184 44934 }

-- MQTT: OPEN-AIR/Zoo/Faders/Vertical/Experimental/Zoo_Faders_Vertical_Experimental/blocks/Experimental_Fader_Riot/exp_17
exp6654 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Faders/Vertical/Experimental/Zoo_Faders_Vertical_Experimental/blocks/Experimental_Fader_Riot/exp_17"
    ::= { experimentalFaderRiotd184 52906 }

-- MQTT: OPEN-AIR/Zoo/Faders/Vertical/Experimental/Zoo_Faders_Vertical_Experimental/blocks/Experimental_Fader_Riot/exp_18
expf6eb OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Faders/Vertical/Experimental/Zoo_Faders_Vertical_Experimental/blocks/Experimental_Fader_Riot/exp_18"
    ::= { experimentalFaderRiotd184 54075 }

-- MQTT: OPEN-AIR/Zoo/Faders/Vertical/Experimental/Zoo_Faders_Vertical_Experimental/blocks/Experimental_Fader_Riot/exp_16
exp1153 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Faders/Vertical/Experimental/Zoo_Faders_Vertical_Experimental/blocks/Experimental_Fader_Riot/exp_16"
    ::= { experimentalFaderRiotd184 65084 }

faderc9b7 OBJECT IDENTIFIER ::= { verticalc654 52391 }
zooFadersVerticalfaderc719 OBJECT IDENTIFIER ::= { faderc9b7 1911 }
blocks6916 OBJECT IDENTIFIER ::= { zooFadersVerticalfaderc719 24449 }
faderZooMASTER8e73 OBJECT IDENTIFIER ::= { blocks6916 13109 }
-- MQTT: OPEN-AIR/Zoo/Faders/Vertical/fader/Zoo_Faders_Vertical_fader/blocks/Fader_Zoo_MASTER/m_2
m92d2 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Faders/Vertical/fader/Zoo_Faders_Vertical_fader/blocks/Fader_Zoo_MASTER/m_2"
    ::= { faderZooMASTER8e73 38495 }

-- MQTT: OPEN-AIR/Zoo/Faders/Vertical/fader/Zoo_Faders_Vertical_fader/blocks/Fader_Zoo_MASTER/m_3
me5d5 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Faders/Vertical/fader/Zoo_Faders_Vertical_fader/blocks/Fader_Zoo_MASTER/m_3"
    ::= { faderZooMASTER8e73 42697 }

-- MQTT: OPEN-AIR/Zoo/Faders/Vertical/fader/Zoo_Faders_Vertical_fader/blocks/Fader_Zoo_MASTER/m_1
mbdbc OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Faders/Vertical/fader/Zoo_Faders_Vertical_fader/blocks/Fader_Zoo_MASTER/m_1"
    ::= { faderZooMASTER8e73 51173 }

gCAac38 OBJECT IDENTIFIER ::= { faderse5a7 34427 }
point31c3 OBJECT IDENTIFIER ::= { gCAac38 8898 }
zooFadersGCApointcf29 OBJECT IDENTIFIER ::= { point31c3 19916 }
blocks8132 OBJECT IDENTIFIER ::= { zooFadersGCApointcf29 64952 }
pointOned678 OBJECT IDENTIFIER ::= { blocks8132 34076 }
compositedrumsb9f8 OBJECT IDENTIFIER ::= { pointOned678 45296 }
-- MQTT: OPEN-AIR/Zoo/Faders/GCA/5point/Zoo_Faders_GCA_5point1/blocks/5 point One/composite_drums/ch_4
ch2de5 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Faders/GCA/5point/Zoo_Faders_GCA_5point1/blocks/5 point One/composite_drums/ch_4"
    ::= { compositedrumsb9f8 4557 }

-- MQTT: OPEN-AIR/Zoo/Faders/GCA/5point/Zoo_Faders_GCA_5point1/blocks/5 point One/composite_drums/ch_3
chb381 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Faders/GCA/5point/Zoo_Faders_GCA_5point1/blocks/5 point One/composite_drums/ch_3"
    ::= { compositedrumsb9f8 33902 }

-- MQTT: OPEN-AIR/Zoo/Faders/GCA/5point/Zoo_Faders_GCA_5point1/blocks/5 point One/composite_drums/ch_2
chc486 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Faders/GCA/5point/Zoo_Faders_GCA_5point1/blocks/5 point One/composite_drums/ch_2"
    ::= { compositedrumsb9f8 46328 }

-- MQTT: OPEN-AIR/Zoo/Faders/GCA/5point/Zoo_Faders_GCA_5point1/blocks/5 point One/composite_drums/ch_1
ch5d8f OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Faders/GCA/5point/Zoo_Faders_GCA_5point1/blocks/5 point One/composite_drums/ch_1"
    ::= { compositedrumsb9f8 58690 }

rGB9619 OBJECT IDENTIFIER ::= { gCAac38 13001 }
zooFadersGCARGB6fe5 OBJECT IDENTIFIER ::= { rGB9619 48817 }
blocksfe05 OBJECT IDENTIFIER ::= { zooFadersGCARGB6fe5 15163 }
rGBMixerDemo6353 OBJECT IDENTIFIER ::= { blocksfe05 56612 }
-- MQTT: OPEN-AIR/Zoo/Faders/GCA/RGB/Zoo_Faders_GCA_RGB/blocks/RGB_Mixer_Demo/ch_1
ch464c OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Faders/GCA/RGB/Zoo_Faders_GCA_RGB/blocks/RGB_Mixer_Demo/ch_1"
    ::= { rGBMixerDemo6353 35857 }

-- MQTT: OPEN-AIR/Zoo/Faders/GCA/RGB/Zoo_Faders_GCA_RGB/blocks/RGB_Mixer_Demo/ch_2
chdf45 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Faders/GCA/RGB/Zoo_Faders_GCA_RGB/blocks/RGB_Mixer_Demo/ch_2"
    ::= { rGBMixerDemo6353 56747 }

zooFadersGCA6506 OBJECT IDENTIFIER ::= { gCAac38 45921 }
blockse991 OBJECT IDENTIFIER ::= { zooFadersGCA6506 30411 }
point8ab8 OBJECT IDENTIFIER ::= { blockse991 39873 }
compositedrumsdcfd OBJECT IDENTIFIER ::= { point8ab8 50842 }
-- MQTT: OPEN-AIR/Zoo/Faders/GCA/Zoo_Faders_GCA_20/blocks/20 point/composite_drums/ch_1
chde18 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Faders/GCA/Zoo_Faders_GCA_20/blocks/20 point/composite_drums/ch_1"
    ::= { compositedrumsdcfd 10471 }

point4877 OBJECT IDENTIFIER ::= { gCAac38 48421 }
zooFadersGCApoint2b41 OBJECT IDENTIFIER ::= { point4877 29481 }
blocks1e85 OBJECT IDENTIFIER ::= { zooFadersGCApoint2b41 63542 }
pointfecc OBJECT IDENTIFIER ::= { blocks1e85 63844 }
compositedrums8e50 OBJECT IDENTIFIER ::= { pointfecc 21307 }
-- MQTT: OPEN-AIR/Zoo/Faders/GCA/20point/Zoo_Faders_GCA_20point4/blocks/20 point 4/composite_drums/ch_2
chd9e5 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Faders/GCA/20point/Zoo_Faders_GCA_20point4/blocks/20 point 4/composite_drums/ch_2"
    ::= { compositedrums8e50 12040 }

-- MQTT: OPEN-AIR/Zoo/Faders/GCA/20point/Zoo_Faders_GCA_20point4/blocks/20 point 4/composite_drums/ch_1
ch40ec OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Faders/GCA/20point/Zoo_Faders_GCA_20point4/blocks/20 point 4/composite_drums/ch_1"
    ::= { compositedrums8e50 32434 }

stereob1dd OBJECT IDENTIFIER ::= { gCAac38 53665 }
zooFadersGCAStereo5341 OBJECT IDENTIFIER ::= { stereob1dd 63889 }
blocks1cbf OBJECT IDENTIFIER ::= { zooFadersGCAStereo5341 17980 }
stereo85ed OBJECT IDENTIFIER ::= { blocks1cbf 42746 }
compositestereo4ac1 OBJECT IDENTIFIER ::= { stereo85ed 33590 }
-- MQTT: OPEN-AIR/Zoo/Faders/GCA/Stereo/Zoo_Faders_GCA_Stereo/blocks/Stereo/composite_stereo/ch_2
ch5466 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Faders/GCA/Stereo/Zoo_Faders_GCA_Stereo/blocks/Stereo/composite_stereo/ch_2"
    ::= { compositestereo4ac1 37549 }

-- MQTT: OPEN-AIR/Zoo/Faders/GCA/Stereo/Zoo_Faders_GCA_Stereo/blocks/Stereo/composite_stereo/ch_1
chcd6f OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Faders/GCA/Stereo/Zoo_Faders_GCA_Stereo/blocks/Stereo/composite_stereo/ch_1"
    ::= { compositestereo4ac1 49943 }

horizontald71b OBJECT IDENTIFIER ::= { faderse5a7 38885 }
classicd86c OBJECT IDENTIFIER ::= { horizontald71b 25574 }
zooFadershorizontalclassic3e29 OBJECT IDENTIFIER ::= { classicd86c 62662 }
blocks265d OBJECT IDENTIFIER ::= { zooFadershorizontalclassic3e29 37257 }
elements8827 OBJECT IDENTIFIER ::= { blocks265d 12923 }
-- MQTT: OPEN-AIR/Zoo/Faders/horizontal/classic/Zoo_Faders_horizontal_classic/blocks/elements1/pan_classic
panclassicb281 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Faders/horizontal/classic/Zoo_Faders_horizontal_classic/blocks/elements1/pan_classic"
    ::= { elements8827 38669 }

elements6629 OBJECT IDENTIFIER ::= { blocks265d 21335 }
-- MQTT: OPEN-AIR/Zoo/Faders/horizontal/classic/Zoo_Faders_horizontal_classic/blocks/elements3/compact_mix
compactmix5a2b OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Faders/horizontal/classic/Zoo_Faders_horizontal_classic/blocks/elements3/compact_mix"
    ::= { elements6629 4126 }

elements112e OBJECT IDENTIFIER ::= { blocks265d 25537 }
-- MQTT: OPEN-AIR/Zoo/Faders/horizontal/classic/Zoo_Faders_horizontal_classic/blocks/elements2/freq_sweep
freqsweepbd5f OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Faders/horizontal/classic/Zoo_Faders_horizontal_classic/blocks/elements2/freq_sweep"
    ::= { elements112e 23443 }

mDP845e OBJECT IDENTIFIER ::= { faderse5a7 46488 }
zooFadersMDP32a1 OBJECT IDENTIFIER ::= { mDP845e 51650 }
blocksa1b6 OBJECT IDENTIFIER ::= { zooFadersMDP32a1 58626 }
mdpdemobd12 OBJECT IDENTIFIER ::= { blocksa1b6 27253 }
mdp1529 OBJECT IDENTIFIER ::= { mdpdemobd12 60880 }
graph8df2 OBJECT IDENTIFIER ::= { mdp1529 31471 }
oaDataRunningFiles87eb OBJECT IDENTIFIER ::= { graph8df2 36219 }
-- MQTT: OPEN-AIR/Zoo/Faders/MDP/Zoo_Faders_MDP/blocks/mdp_demo/mdp_1/graph/oaDataRunningFiles/grid_ref
gridref994b OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Faders/MDP/Zoo_Faders_MDP/blocks/mdp_demo/mdp_1/graph/oaDataRunningFiles/grid_ref"
    ::= { oaDataRunningFiles87eb 23976 }

faderDial4a55 OBJECT IDENTIFIER ::= { faderse5a7 50352 }
moreDialsde89 OBJECT IDENTIFIER ::= { faderDial4a55 33471 }
zooFadersFaderDialMoreDials7238 OBJECT IDENTIFIER ::= { moreDialsde89 15807 }
blockse508 OBJECT IDENTIFIER ::= { zooFadersFaderDialMoreDials7238 4794 }
dialExpansion4809 OBJECT IDENTIFIER ::= { blockse508 60361 }
dial7bc2 OBJECT IDENTIFIER ::= { dialExpansion4809 3650 }
-- MQTT: OPEN-AIR/Zoo/Faders/Fader_Dial/More_Dials/Zoo_Faders_Fader_Dial_More_Dials/blocks/Dial_Expansion/dial_1/fader_config
faderconfig9e9b OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Faders/Fader_Dial/More_Dials/Zoo_Faders_Fader_Dial_More_Dials/blocks/Dial_Expansion/dial_1/fader_config"
    ::= { dial7bc2 42495 }

-- MQTT: OPEN-AIR/Zoo/Faders/Fader_Dial/More_Dials/Zoo_Faders_Fader_Dial_More_Dials/blocks/Dial_Expansion/dial_1/dial_config
dialconfig2094 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Faders/Fader_Dial/More_Dials/Zoo_Faders_Fader_Dial_More_Dials/blocks/Dial_Expansion/dial_1/dial_config"
    ::= { dial7bc2 65161 }

dialf57b OBJECT IDENTIFIER ::= { dialExpansion4809 27689 }
-- MQTT: OPEN-AIR/Zoo/Faders/Fader_Dial/More_Dials/Zoo_Faders_Fader_Dial_More_Dials/blocks/Dial_Expansion/dial_13/dial_config
dialconfigad98 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Faders/Fader_Dial/More_Dials/Zoo_Faders_Fader_Dial_More_Dials/blocks/Dial_Expansion/dial_13/dial_config"
    ::= { dialf57b 25176 }

dial92a1 OBJECT IDENTIFIER ::= { dialExpansion4809 43895 }
-- MQTT: OPEN-AIR/Zoo/Faders/Fader_Dial/More_Dials/Zoo_Faders_Fader_Dial_More_Dials/blocks/Dial_Expansion/dial_7/dial_config
dialconfig8071 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Faders/Fader_Dial/More_Dials/Zoo_Faders_Fader_Dial_More_Dials/blocks/Dial_Expansion/dial_7/dial_config"
    ::= { dial92a1 8532 }

dial1c18 OBJECT IDENTIFIER ::= { dialExpansion4809 51484 }
-- MQTT: OPEN-AIR/Zoo/Faders/Fader_Dial/More_Dials/Zoo_Faders_Fader_Dial_More_Dials/blocks/Dial_Expansion/dial_15/fader_config
faderconfig9700 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Faders/Fader_Dial/More_Dials/Zoo_Faders_Fader_Dial_More_Dials/blocks/Dial_Expansion/dial_15/fader_config"
    ::= { dial1c18 151 }

horizontalwithdialValuef1d2 OBJECT IDENTIFIER ::= { faderDial4a55 44513 }
zooFadersFaderDialHorizontalwithdialValue1311 OBJECT IDENTIFIER ::= { horizontalwithdialValuef1d2 63341 }
blocks266c OBJECT IDENTIFIER ::= { zooFadersFaderDialHorizontalwithdialValue1311 57367 }
dialExpansion1347 OBJECT IDENTIFIER ::= { blocks266c 30146 }
-- MQTT: OPEN-AIR/Zoo/Faders/Fader_Dial/Horizontal_with_dial_Value/Zoo_Faders_Fader_Dial_Horizontal_with_dial_Value/blocks/Dial_Expansion/dial_17
dial6a1a OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Faders/Fader_Dial/Horizontal_with_dial_Value/Zoo_Faders_Fader_Dial_Horizontal_with_dial_Value/blocks/Dial_Expansion/dial_17"
    ::= { dialExpansion1347 11457 }

diala566 OBJECT IDENTIFIER ::= { dialExpansion1347 17152 }
-- MQTT: OPEN-AIR/Zoo/Faders/Fader_Dial/Horizontal_with_dial_Value/Zoo_Faders_Fader_Dial_Horizontal_with_dial_Value/blocks/Dial_Expansion/dial_1/fader_config
faderconfigedfa OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Faders/Fader_Dial/Horizontal_with_dial_Value/Zoo_Faders_Fader_Dial_Horizontal_with_dial_Value/blocks/Dial_Expansion/dial_1/fader_config"
    ::= { diala566 16689 }

-- MQTT: OPEN-AIR/Zoo/Faders/Fader_Dial/Horizontal_with_dial_Value/Zoo_Faders_Fader_Dial_Horizontal_with_dial_Value/blocks/Dial_Expansion/dial_1/dial_config
dialconfig9d66 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Faders/Fader_Dial/Horizontal_with_dial_Value/Zoo_Faders_Fader_Dial_Horizontal_with_dial_Value/blocks/Dial_Expansion/dial_1/dial_config"
    ::= { diala566 45838 }

dial1a70 OBJECT IDENTIFIER ::= { dialExpansion1347 55374 }
-- MQTT: OPEN-AIR/Zoo/Faders/Fader_Dial/Horizontal_with_dial_Value/Zoo_Faders_Fader_Dial_Horizontal_with_dial_Value/blocks/Dial_Expansion/dial_12/fader_config
faderconfig8e62 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Faders/Fader_Dial/Horizontal_with_dial_Value/Zoo_Faders_Fader_Dial_Horizontal_with_dial_Value/blocks/Dial_Expansion/dial_12/fader_config"
    ::= { dial1a70 9220 }

-- MQTT: OPEN-AIR/Zoo/Faders/Fader_Dial/Horizontal_with_dial_Value/Zoo_Faders_Fader_Dial_Horizontal_with_dial_Value/blocks/Dial_Expansion/dial_12/dial_config
dialconfig36f5 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Faders/Fader_Dial/Horizontal_with_dial_Value/Zoo_Faders_Fader_Dial_Horizontal_with_dial_Value/blocks/Dial_Expansion/dial_12/dial_config"
    ::= { dial1a70 24339 }

dialdf53 OBJECT IDENTIFIER ::= { dialExpansion1347 60065 }
-- MQTT: OPEN-AIR/Zoo/Faders/Fader_Dial/Horizontal_with_dial_Value/Zoo_Faders_Fader_Dial_Horizontal_with_dial_Value/blocks/Dial_Expansion/dial_20/dial_config
dialconfig1f52 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Faders/Fader_Dial/Horizontal_with_dial_Value/Zoo_Faders_Fader_Dial_Horizontal_with_dial_Value/blocks/Dial_Expansion/dial_20/dial_config"
    ::= { dialdf53 53123 }

classiccb53 OBJECT IDENTIFIER ::= { faderDial4a55 58835 }
zooFadersFaderDialClassicc464 OBJECT IDENTIFIER ::= { classiccb53 7095 }
blocksc2e8 OBJECT IDENTIFIER ::= { zooFadersFaderDialClassicc464 35194 }
elementsdbdb OBJECT IDENTIFIER ::= { blocksc2e8 48975 }
examplefields1947 OBJECT IDENTIFIER ::= { elementsdbdb 61913 }
-- MQTT: OPEN-AIR/Zoo/Faders/Fader_Dial/Classic/Zoo_Faders_Fader_Dial_Classic/blocks/elements1/examplefields/dial_config
dialconfig555b OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Faders/Fader_Dial/Classic/Zoo_Faders_Fader_Dial_Classic/blocks/elements1/examplefields/dial_config"
    ::= { examplefields1947 8278 }

-- MQTT: OPEN-AIR/Zoo/Faders/Fader_Dial/Classic/Zoo_Faders_Fader_Dial_Classic/blocks/elements1/examplefields/fader_config
faderconfig8882 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Faders/Fader_Dial/Classic/Zoo_Faders_Fader_Dial_Classic/blocks/elements1/examplefields/fader_config"
    ::= { examplefields1947 42340 }

elements94b4 OBJECT IDENTIFIER ::= { blocksc2e8 61173 }
examplefields83a9 OBJECT IDENTIFIER ::= { elements94b4 39840 }
-- MQTT: OPEN-AIR/Zoo/Faders/Fader_Dial/Classic/Zoo_Faders_Fader_Dial_Classic/blocks/elements2/examplefields/fader_config
faderconfig8a5c OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Faders/Fader_Dial/Classic/Zoo_Faders_Fader_Dial_Classic/blocks/elements2/examplefields/fader_config"
    ::= { examplefields83a9 41539 }

lTPcf5e OBJECT IDENTIFIER ::= { faderse5a7 52734 }
zooFadersLTP81a2 OBJECT IDENTIFIER ::= { lTPcf5e 40504 }
blocks3854 OBJECT IDENTIFIER ::= { zooFadersLTP81a2 9086 }
lTPFreestyleConsolef2c3 OBJECT IDENTIFIER ::= { blocks3854 11423 }
cH86ea OBJECT IDENTIFIER ::= { lTPFreestyleConsolef2c3 44371 }
-- MQTT: OPEN-AIR/Zoo/Faders/LTP/Zoo_Faders_LTP/blocks/LTP_Freestyle_Console/CH1/rotation
rotationba52 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Faders/LTP/Zoo_Faders_LTP/blocks/LTP_Freestyle_Console/CH1/rotation"
    ::= { cH86ea 9343 }

cH9167 OBJECT IDENTIFIER ::= { lTPFreestyleConsolef2c3 64745 }
-- MQTT: OPEN-AIR/Zoo/Faders/LTP/Zoo_Faders_LTP/blocks/LTP_Freestyle_Console/CH2/rotation
rotation5165 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Faders/LTP/Zoo_Faders_LTP/blocks/LTP_Freestyle_Console/CH2/rotation"
    ::= { cH9167 40828 }

lTPDemoBottomeed8 OBJECT IDENTIFIER ::= { blocks3854 57616 }
he3e1 OBJECT IDENTIFIER ::= { lTPDemoBottomeed8 655 }
-- MQTT: OPEN-AIR/Zoo/Faders/LTP/Zoo_Faders_LTP/blocks/LTP_Demo_Bottom/H1/rotation
rotation39d1 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Faders/LTP/Zoo_Faders_LTP/blocks/LTP_Demo_Bottom/H1/rotation"
    ::= { he3e1 4648 }

h7ae8 OBJECT IDENTIFIER ::= { lTPDemoBottomeed8 21301 }
-- MQTT: OPEN-AIR/Zoo/Faders/LTP/Zoo_Faders_LTP/blocks/LTP_Demo_Bottom/H2/rotation
rotationd2e6 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Faders/LTP/Zoo_Faders_LTP/blocks/LTP_Demo_Bottom/H2/rotation"
    ::= { h7ae8 43307 }

buttons2a5a OBJECT IDENTIFIER ::= { zoo994f 32801 }
winkafb0 OBJECT IDENTIFIER ::= { buttons2a5a 3706 }
winktowinktexte4c5 OBJECT IDENTIFIER ::= { winkafb0 45225 }
zoobuttonsWinkwinktowinktext5393 OBJECT IDENTIFIER ::= { winktowinktexte4c5 20043 }
blockse7f6 OBJECT IDENTIFIER ::= { zoobuttonsWinkwinktowinktext5393 5571 }
winkButtonsDemoce7c OBJECT IDENTIFIER ::= { blockse7f6 18797 }
-- MQTT: OPEN-AIR/Zoo/buttons/Wink/wink_to_wink_text/Zoo_buttons_Wink_wink_to_wink_text/blocks/Wink_Buttons_Demo_2/wink_05_rect_cyan
winkrectcyan6013 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/buttons/Wink/wink_to_wink_text/Zoo_buttons_Wink_wink_to_wink_text/blocks/Wink_Buttons_Demo_2/wink_05_rect_cyan"
    ::= { winkButtonsDemoce7c 59839 }

trapezoidb9df OBJECT IDENTIFIER ::= { buttons2a5a 56965 }
trapezoidbuttonb1ac OBJECT IDENTIFIER ::= { trapezoidb9df 16987 }
zoobuttonsTrapezoidtrapezoidbuttonc17c OBJECT IDENTIFIER ::= { trapezoidbuttonb1ac 52511 }
blocks7f40 OBJECT IDENTIFIER ::= { zoobuttonsTrapezoidtrapezoidbuttonc17c 47031 }
trapezoidButtonMUTEVariations83b9 OBJECT IDENTIFIER ::= { blocks7f40 10154 }
-- MQTT: OPEN-AIR/Zoo/buttons/Trapezoid/trapezoid_button/Zoo_buttons_Trapezoid_trapezoid_button_2/blocks/Trapezoid_Button_MUTE_Variations/solo_latching_blue
sololatchingblue8a06 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/buttons/Trapezoid/trapezoid_button/Zoo_buttons_Trapezoid_trapezoid_button_2/blocks/Trapezoid_Button_MUTE_Variations/solo_latching_blue"
    ::= { trapezoidButtonMUTEVariations83b9 6602 }

-- MQTT: OPEN-AIR/Zoo/buttons/Trapezoid/trapezoid_button/Zoo_buttons_Trapezoid_trapezoid_button_2/blocks/Trapezoid_Button_MUTE_Variations/mute_momentary_red
mutemomentaryredd086 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/buttons/Trapezoid/trapezoid_button/Zoo_buttons_Trapezoid_trapezoid_button_2/blocks/Trapezoid_Button_MUTE_Variations/mute_momentary_red"
    ::= { trapezoidButtonMUTEVariations83b9 42494 }

meteringf6b9 OBJECT IDENTIFIER ::= { zoo994f 37923 }
barMeterd000 OBJECT IDENTIFIER ::= { meteringf6b9 53297 }
multichannelc924 OBJECT IDENTIFIER ::= { barMeterd000 131 }
zooMeteringBarMetermultichanneld7b4 OBJECT IDENTIFIER ::= { multichannelc924 1711 }
blockse2c8 OBJECT IDENTIFIER ::= { zooMeteringBarMetermultichanneld7b4 52670 }
stereoMonitoringStation11ea OBJECT IDENTIFIER ::= { blockse2c8 40185 }
gangof24db OBJECT IDENTIFIER ::= { stereoMonitoringStation11ea 15691 }
-- MQTT: OPEN-AIR/Zoo/Metering/Bar_Meter/multi_channel/Zoo_Metering_Bar_Meter_multi_channel/blocks/Stereo_Monitoring_Station/Gang_of_8/G1
gb014 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Metering/Bar_Meter/multi_channel/Zoo_Metering_Bar_Meter_multi_channel/blocks/Stereo_Monitoring_Station/Gang_of_8/G1"
    ::= { gangof24db 1138 }

-- MQTT: OPEN-AIR/Zoo/Metering/Bar_Meter/multi_channel/Zoo_Metering_Bar_Meter_multi_channel/blocks/Stereo_Monitoring_Station/Gang_of_8/G3
g5e1a OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Metering/Bar_Meter/multi_channel/Zoo_Metering_Bar_Meter_multi_channel/blocks/Stereo_Monitoring_Station/Gang_of_8/G3"
    ::= { gangof24db 25950 }

stereoBankA8e60 OBJECT IDENTIFIER ::= { stereoMonitoringStation11ea 45582 }
-- MQTT: OPEN-AIR/Zoo/Metering/Bar_Meter/multi_channel/Zoo_Metering_Bar_Meter_multi_channel/blocks/Stereo_Monitoring_Station/Stereo_Bank_A/pair4_R
pairR3ba8 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Metering/Bar_Meter/multi_channel/Zoo_Metering_Bar_Meter_multi_channel/blocks/Stereo_Monitoring_Station/Stereo_Bank_A/pair4_R"
    ::= { stereoBankA8e60 36793 }

surround4f81 OBJECT IDENTIFIER ::= { barMeterd000 16226 }
zooMeteringBarMeterSurround70c3 OBJECT IDENTIFIER ::= { surround4f81 45376 }
blocks8ba1 OBJECT IDENTIFIER ::= { zooMeteringBarMeterSurround70c3 9710 }
surroundMonitoringStationb8f2 OBJECT IDENTIFIER ::= { blocks8ba1 10033 }
surroundVerte52f OBJECT IDENTIFIER ::= { surroundMonitoringStationb8f2 45232 }
-- MQTT: OPEN-AIR/Zoo/Metering/Bar_Meter/Surround/Zoo_Metering_Bar_Meter_Surround/blocks/Surround_Monitoring_Station/Surround_5_1_Vert/L
l3865 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Metering/Bar_Meter/Surround/Zoo_Metering_Bar_Meter_Surround/blocks/Surround_Monitoring_Station/Surround_5_1_Vert/L"
    ::= { surroundVerte52f 65530 }

verticalbar77f6 OBJECT IDENTIFIER ::= { barMeterd000 28232 }
zooMeteringBarMeterVerticalbarf97f OBJECT IDENTIFIER ::= { verticalbar77f6 51833 }
blocks92d9 OBJECT IDENTIFIER ::= { zooMeteringBarMeterVerticalbarf97f 9417 }
wideVerticald07e OBJECT IDENTIFIER ::= { blocks92d9 6056 }
-- MQTT: OPEN-AIR/Zoo/Metering/Bar_Meter/Vertical_bar/Zoo_Metering_Bar_Meter_Vertical_bar/blocks/Wide_Vertical/demo_01_standard_bottom
demostandardbottom4a2e OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Metering/Bar_Meter/Vertical_bar/Zoo_Metering_Bar_Meter_Vertical_bar/blocks/Wide_Vertical/demo_01_standard_bottom"
    ::= { wideVerticald07e 6330 }

-- MQTT: OPEN-AIR/Zoo/Metering/Bar_Meter/Vertical_bar/Zoo_Metering_Bar_Meter_Vertical_bar/blocks/Wide_Vertical/demo_09_thick_bar_top
demothickbartop5fa2 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Metering/Bar_Meter/Vertical_bar/Zoo_Metering_Bar_Meter_Vertical_bar/blocks/Wide_Vertical/demo_09_thick_bar_top"
    ::= { wideVerticald07e 8894 }

-- MQTT: OPEN-AIR/Zoo/Metering/Bar_Meter/Vertical_bar/Zoo_Metering_Bar_Meter_Vertical_bar/blocks/Wide_Vertical/demo_05_no_label_above
demonolabelabovee07b OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Metering/Bar_Meter/Vertical_bar/Zoo_Metering_Bar_Meter_Vertical_bar/blocks/Wide_Vertical/demo_05_no_label_above"
    ::= { wideVerticald07e 10985 }

-- MQTT: OPEN-AIR/Zoo/Metering/Bar_Meter/Vertical_bar/Zoo_Metering_Bar_Meter_Vertical_bar/blocks/Wide_Vertical/demo_08_inverted_colors
demoinvertedcolors1246 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Metering/Bar_Meter/Vertical_bar/Zoo_Metering_Bar_Meter_Vertical_bar/blocks/Wide_Vertical/demo_08_inverted_colors"
    ::= { wideVerticald07e 18146 }

-- MQTT: OPEN-AIR/Zoo/Metering/Bar_Meter/Vertical_bar/Zoo_Metering_Bar_Meter_Vertical_bar/blocks/Wide_Vertical/demo_03_no_ticks_bottom_text
demonoticksbottomtextbfaa OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Metering/Bar_Meter/Vertical_bar/Zoo_Metering_Bar_Meter_Vertical_bar/blocks/Wide_Vertical/demo_03_no_ticks_bottom_text"
    ::= { wideVerticald07e 37041 }

-- MQTT: OPEN-AIR/Zoo/Metering/Bar_Meter/Vertical_bar/Zoo_Metering_Bar_Meter_Vertical_bar/blocks/Wide_Vertical/demo_07_minimalist_none
demominimalistnone645a OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Metering/Bar_Meter/Vertical_bar/Zoo_Metering_Bar_Meter_Vertical_bar/blocks/Wide_Vertical/demo_07_minimalist_none"
    ::= { wideVerticald07e 41539 }

-- MQTT: OPEN-AIR/Zoo/Metering/Bar_Meter/Vertical_bar/Zoo_Metering_Bar_Meter_Vertical_bar/blocks/Wide_Vertical/demo_04_ticks_no_text
demoticksnotext28f3 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Metering/Bar_Meter/Vertical_bar/Zoo_Metering_Bar_Meter_Vertical_bar/blocks/Wide_Vertical/demo_04_ticks_no_text"
    ::= { wideVerticald07e 42370 }

-- MQTT: OPEN-AIR/Zoo/Metering/Bar_Meter/Vertical_bar/Zoo_Metering_Bar_Meter_Vertical_bar/blocks/Wide_Vertical/demo_02_scale_top
demoscaletope3b8 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Metering/Bar_Meter/Vertical_bar/Zoo_Metering_Bar_Meter_Vertical_bar/blocks/Wide_Vertical/demo_02_scale_top"
    ::= { wideVerticald07e 45492 }

-- MQTT: OPEN-AIR/Zoo/Metering/Bar_Meter/Vertical_bar/Zoo_Metering_Bar_Meter_Vertical_bar/blocks/Wide_Vertical/demo_06_rect_peak_top
demorectpeaktopb339 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Metering/Bar_Meter/Vertical_bar/Zoo_Metering_Bar_Meter_Vertical_bar/blocks/Wide_Vertical/demo_06_rect_peak_top"
    ::= { wideVerticald07e 55132 }

wideRangeverticaldemoca0d OBJECT IDENTIFIER ::= { blocks92d9 55104 }
-- MQTT: OPEN-AIR/Zoo/Metering/Bar_Meter/Vertical_bar/Zoo_Metering_Bar_Meter_Vertical_bar/blocks/Wide_Range_vertical_demo/demo_03_no_ticks_bottom_text
demonoticksbottomtextb40e OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Metering/Bar_Meter/Vertical_bar/Zoo_Metering_Bar_Meter_Vertical_bar/blocks/Wide_Range_vertical_demo/demo_03_no_ticks_bottom_text"
    ::= { wideRangeverticaldemoca0d 22457 }

-- MQTT: OPEN-AIR/Zoo/Metering/Bar_Meter/Vertical_bar/Zoo_Metering_Bar_Meter_Vertical_bar/blocks/Wide_Range_vertical_demo/demo_01_standard_bottom
demostandardbottom5e95 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Metering/Bar_Meter/Vertical_bar/Zoo_Metering_Bar_Meter_Vertical_bar/blocks/Wide_Range_vertical_demo/demo_01_standard_bottom"
    ::= { wideRangeverticaldemoca0d 25931 }

-- MQTT: OPEN-AIR/Zoo/Metering/Bar_Meter/Vertical_bar/Zoo_Metering_Bar_Meter_Vertical_bar/blocks/Wide_Range_vertical_demo/demo_05_no_label_above
demonolabelabove5a5a OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Metering/Bar_Meter/Vertical_bar/Zoo_Metering_Bar_Meter_Vertical_bar/blocks/Wide_Range_vertical_demo/demo_05_no_label_above"
    ::= { wideRangeverticaldemoca0d 38133 }

-- MQTT: OPEN-AIR/Zoo/Metering/Bar_Meter/Vertical_bar/Zoo_Metering_Bar_Meter_Vertical_bar/blocks/Wide_Range_vertical_demo/demo_04_ticks_no_text
demoticksnotextd97b OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Metering/Bar_Meter/Vertical_bar/Zoo_Metering_Bar_Meter_Vertical_bar/blocks/Wide_Range_vertical_demo/demo_04_ticks_no_text"
    ::= { wideRangeverticaldemoca0d 48246 }

-- MQTT: OPEN-AIR/Zoo/Metering/Bar_Meter/Vertical_bar/Zoo_Metering_Bar_Meter_Vertical_bar/blocks/Wide_Range_vertical_demo/demo_06_rect_peak_top
demorectpeaktop42b1 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Metering/Bar_Meter/Vertical_bar/Zoo_Metering_Bar_Meter_Vertical_bar/blocks/Wide_Range_vertical_demo/demo_06_rect_peak_top"
    ::= { wideRangeverticaldemoca0d 52904 }

-- MQTT: OPEN-AIR/Zoo/Metering/Bar_Meter/Vertical_bar/Zoo_Metering_Bar_Meter_Vertical_bar/blocks/Wide_Range_vertical_demo/demo_07_minimalist_none
demominimalistnone12fe OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Metering/Bar_Meter/Vertical_bar/Zoo_Metering_Bar_Meter_Vertical_bar/blocks/Wide_Range_vertical_demo/demo_07_minimalist_none"
    ::= { wideRangeverticaldemoca0d 57266 }

-- MQTT: OPEN-AIR/Zoo/Metering/Bar_Meter/Vertical_bar/Zoo_Metering_Bar_Meter_Vertical_bar/blocks/Wide_Range_vertical_demo/demo_02_scale_top
demoscaletop6b4e OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Metering/Bar_Meter/Vertical_bar/Zoo_Metering_Bar_Meter_Vertical_bar/blocks/Wide_Range_vertical_demo/demo_02_scale_top"
    ::= { wideRangeverticaldemoca0d 61731 }

horizontalbarc9a4 OBJECT IDENTIFIER ::= { barMeterd000 44422 }
zooMeteringBarMeterHorizontalbar1be8 OBJECT IDENTIFIER ::= { horizontalbarc9a4 59104 }
blocks87b7 OBJECT IDENTIFIER ::= { zooMeteringBarMeterHorizontalbar1be8 41176 }
wideRangetribardemo6c76 OBJECT IDENTIFIER ::= { blocks87b7 26169 }
-- MQTT: OPEN-AIR/Zoo/Metering/Bar_Meter/Horizontal_bar/Zoo_Metering_Bar_Meter_Horizontal_bar/blocks/Wide_Range_tribar_demo/demo_06_rect_peak_top
demorectpeaktopc5ec OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Metering/Bar_Meter/Horizontal_bar/Zoo_Metering_Bar_Meter_Horizontal_bar/blocks/Wide_Range_tribar_demo/demo_06_rect_peak_top"
    ::= { wideRangetribardemo6c76 5086 }

-- MQTT: OPEN-AIR/Zoo/Metering/Bar_Meter/Horizontal_bar/Zoo_Metering_Bar_Meter_Horizontal_bar/blocks/Wide_Range_tribar_demo/demo_07_minimalist_none
demominimalistnone93f9 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Metering/Bar_Meter/Horizontal_bar/Zoo_Metering_Bar_Meter_Horizontal_bar/blocks/Wide_Range_tribar_demo/demo_07_minimalist_none"
    ::= { wideRangetribardemo6c76 10486 }

-- MQTT: OPEN-AIR/Zoo/Metering/Bar_Meter/Horizontal_bar/Zoo_Metering_Bar_Meter_Horizontal_bar/blocks/Wide_Range_tribar_demo/demo_03_no_ticks_bottom_text
demonoticksbottomtext251b OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Metering/Bar_Meter/Horizontal_bar/Zoo_Metering_Bar_Meter_Horizontal_bar/blocks/Wide_Range_tribar_demo/demo_03_no_ticks_bottom_text"
    ::= { wideRangetribardemo6c76 14497 }

-- MQTT: OPEN-AIR/Zoo/Metering/Bar_Meter/Horizontal_bar/Zoo_Metering_Bar_Meter_Horizontal_bar/blocks/Wide_Range_tribar_demo/demo_04_ticks_no_text
demoticksnotext5e26 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Metering/Bar_Meter/Horizontal_bar/Zoo_Metering_Bar_Meter_Horizontal_bar/blocks/Wide_Range_tribar_demo/demo_04_ticks_no_text"
    ::= { wideRangetribardemo6c76 24832 }

-- MQTT: OPEN-AIR/Zoo/Metering/Bar_Meter/Horizontal_bar/Zoo_Metering_Bar_Meter_Horizontal_bar/blocks/Wide_Range_tribar_demo/demo_01_standard_bottom
demostandardbottomdf92 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Metering/Bar_Meter/Horizontal_bar/Zoo_Metering_Bar_Meter_Horizontal_bar/blocks/Wide_Range_tribar_demo/demo_01_standard_bottom"
    ::= { wideRangetribardemo6c76 37391 }

-- MQTT: OPEN-AIR/Zoo/Metering/Bar_Meter/Horizontal_bar/Zoo_Metering_Bar_Meter_Horizontal_bar/blocks/Wide_Range_tribar_demo/demo_08_inverted_colors
demoinvertedcolors95ae OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Metering/Bar_Meter/Horizontal_bar/Zoo_Metering_Bar_Meter_Horizontal_bar/blocks/Wide_Range_tribar_demo/demo_08_inverted_colors"
    ::= { wideRangetribardemo6c76 52311 }

-- MQTT: OPEN-AIR/Zoo/Metering/Bar_Meter/Horizontal_bar/Zoo_Metering_Bar_Meter_Horizontal_bar/blocks/Wide_Range_tribar_demo/demo_02_scale_top
demoscaletopfd4a OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Metering/Bar_Meter/Horizontal_bar/Zoo_Metering_Bar_Meter_Horizontal_bar/blocks/Wide_Range_tribar_demo/demo_02_scale_top"
    ::= { wideRangetribardemo6c76 56910 }

-- MQTT: OPEN-AIR/Zoo/Metering/Bar_Meter/Horizontal_bar/Zoo_Metering_Bar_Meter_Horizontal_bar/blocks/Wide_Range_tribar_demo/demo_09_thick_bar_top
demothickbartop732f OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Metering/Bar_Meter/Horizontal_bar/Zoo_Metering_Bar_Meter_Horizontal_bar/blocks/Wide_Range_tribar_demo/demo_09_thick_bar_top"
    ::= { wideRangetribardemo6c76 58940 }

horizontalTri3a85 OBJECT IDENTIFIER ::= { barMeterd000 64058 }
zooMeteringBarMeterHorizontalTri8877 OBJECT IDENTIFIER ::= { horizontalTri3a85 46929 }
blocks3ac4 OBJECT IDENTIFIER ::= { zooMeteringBarMeterHorizontalTri8877 49429 }
wideRangeHorizontalf8c4 OBJECT IDENTIFIER ::= { blocks3ac4 51322 }
-- MQTT: OPEN-AIR/Zoo/Metering/Bar_Meter/Horizontal_Tri/Zoo_Metering_Bar_Meter_Horizontal_Tri/blocks/Wide_Range_Horizontal/demo_06_rect_peak_top
demorectpeaktop9965 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Metering/Bar_Meter/Horizontal_Tri/Zoo_Metering_Bar_Meter_Horizontal_Tri/blocks/Wide_Range_Horizontal/demo_06_rect_peak_top"
    ::= { wideRangeHorizontalf8c4 2984 }

-- MQTT: OPEN-AIR/Zoo/Metering/Bar_Meter/Horizontal_Tri/Zoo_Metering_Bar_Meter_Horizontal_Tri/blocks/Wide_Range_Horizontal/demo_07_minimalist_none
demominimalistnonef9f0 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Metering/Bar_Meter/Horizontal_Tri/Zoo_Metering_Bar_Meter_Horizontal_Tri/blocks/Wide_Range_Horizontal/demo_07_minimalist_none"
    ::= { wideRangeHorizontalf8c4 12889 }

-- MQTT: OPEN-AIR/Zoo/Metering/Bar_Meter/Horizontal_Tri/Zoo_Metering_Bar_Meter_Horizontal_Tri/blocks/Wide_Range_Horizontal/demo_04_ticks_no_text
demoticksnotext2af7 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Metering/Bar_Meter/Horizontal_Tri/Zoo_Metering_Bar_Meter_Horizontal_Tri/blocks/Wide_Range_Horizontal/demo_04_ticks_no_text"
    ::= { wideRangeHorizontalf8c4 31094 }

-- MQTT: OPEN-AIR/Zoo/Metering/Bar_Meter/Horizontal_Tri/Zoo_Metering_Bar_Meter_Horizontal_Tri/blocks/Wide_Range_Horizontal/demo_01_standard_bottom
demostandardbottomb59b OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Metering/Bar_Meter/Horizontal_Tri/Zoo_Metering_Bar_Meter_Horizontal_Tri/blocks/Wide_Range_Horizontal/demo_01_standard_bottom"
    ::= { wideRangeHorizontalf8c4 34976 }

-- MQTT: OPEN-AIR/Zoo/Metering/Bar_Meter/Horizontal_Tri/Zoo_Metering_Bar_Meter_Horizontal_Tri/blocks/Wide_Range_Horizontal/demo_10_ultra_fast_bottom
demoultrafastbottom5eef OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Metering/Bar_Meter/Horizontal_Tri/Zoo_Metering_Bar_Meter_Horizontal_Tri/blocks/Wide_Range_Horizontal/demo_10_ultra_fast_bottom"
    ::= { wideRangeHorizontalf8c4 37481 }

-- MQTT: OPEN-AIR/Zoo/Metering/Bar_Meter/Horizontal_Tri/Zoo_Metering_Bar_Meter_Horizontal_Tri/blocks/Wide_Range_Horizontal/demo_08_inverted_colors
demoinvertedcolorsffa7 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Metering/Bar_Meter/Horizontal_Tri/Zoo_Metering_Bar_Meter_Horizontal_Tri/blocks/Wide_Range_Horizontal/demo_08_inverted_colors"
    ::= { wideRangeHorizontalf8c4 55032 }

-- MQTT: OPEN-AIR/Zoo/Metering/Bar_Meter/Horizontal_Tri/Zoo_Metering_Bar_Meter_Horizontal_Tri/blocks/Wide_Range_Horizontal/demo_02_scale_top
demoscaletopf42a OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Metering/Bar_Meter/Horizontal_Tri/Zoo_Metering_Bar_Meter_Horizontal_Tri/blocks/Wide_Range_Horizontal/demo_02_scale_top"
    ::= { wideRangeHorizontalf8c4 62552 }

rEF71f6 OBJECT IDENTIFIER ::= { barMeterd000 65509 }
zooMeteringBarMeterREFedb1 OBJECT IDENTIFIER ::= { rEF71f6 11219 }
blocks2544 OBJECT IDENTIFIER ::= { zooMeteringBarMeterREFedb1 63164 }
hardwareScalesBar6fb1 OBJECT IDENTIFIER ::= { blocks2544 10779 }
-- MQTT: OPEN-AIR/Zoo/Metering/Bar_Meter/REF/Zoo_Metering_Bar_Meter_REF/blocks/Hardware_Scales_1_Bar/Scale_BBC_Bar
scaleBBCBarc351 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Metering/Bar_Meter/REF/Zoo_Metering_Bar_Meter_REF/blocks/Hardware_Scales_1_Bar/Scale_BBC_Bar"
    ::= { hardwareScalesBar6fb1 31415 }

-- MQTT: OPEN-AIR/Zoo/Metering/Bar_Meter/REF/Zoo_Metering_Bar_Meter_REF/blocks/Hardware_Scales_1_Bar/Scale_ABC_West_Bar
scaleABCWestBar87ba OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Metering/Bar_Meter/REF/Zoo_Metering_Bar_Meter_REF/blocks/Hardware_Scales_1_Bar/Scale_ABC_West_Bar"
    ::= { hardwareScalesBar6fb1 46497 }

protectionMetersBar24ff OBJECT IDENTIFIER ::= { blocks2544 17142 }
-- MQTT: OPEN-AIR/Zoo/Metering/Bar_Meter/REF/Zoo_Metering_Bar_Meter_REF/blocks/Protection_Meters_Bar/PPM_Type_II_Bar
pPMTypeIIBar38ce OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Metering/Bar_Meter/REF/Zoo_Metering_Bar_Meter_REF/blocks/Protection_Meters_Bar/PPM_Type_II_Bar"
    ::= { protectionMetersBar24ff 4068 }

-- MQTT: OPEN-AIR/Zoo/Metering/Bar_Meter/REF/Zoo_Metering_Bar_Meter_REF/blocks/Protection_Meters_Bar/PPM_Type_I_Bar
pPMTypeIBar4fc7 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Metering/Bar_Meter/REF/Zoo_Metering_Bar_Meter_REF/blocks/Protection_Meters_Bar/PPM_Type_I_Bar"
    ::= { protectionMetersBar24ff 37717 }

averagingMetersBar6c7c OBJECT IDENTIFIER ::= { blocks2544 30481 }
-- MQTT: OPEN-AIR/Zoo/Metering/Bar_Meter/REF/Zoo_Metering_Bar_Meter_REF/blocks/Averaging_Meters_Bar/Standard_VU_Bar
standardVUBar7593 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Metering/Bar_Meter/REF/Zoo_Metering_Bar_Meter_REF/blocks/Averaging_Meters_Bar/Standard_VU_Bar"
    ::= { averagingMetersBar6c7c 49591 }

-- MQTT: OPEN-AIR/Zoo/Metering/Bar_Meter/REF/Zoo_Metering_Bar_Meter_REF/blocks/Averaging_Meters_Bar/RMS_Meter_Bar
rMSMeterBara28e OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Metering/Bar_Meter/REF/Zoo_Metering_Bar_Meter_REF/blocks/Averaging_Meters_Bar/RMS_Meter_Bar"
    ::= { averagingMetersBar6c7c 52389 }

digitalMetersBar1317 OBJECT IDENTIFIER ::= { blocks2544 37135 }
-- MQTT: OPEN-AIR/Zoo/Metering/Bar_Meter/REF/Zoo_Metering_Bar_Meter_REF/blocks/Digital_Meters_Bar/LUFS_ShortTerm_Bar
lUFSShortTermBar75cf OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Metering/Bar_Meter/REF/Zoo_Metering_Bar_Meter_REF/blocks/Digital_Meters_Bar/LUFS_ShortTerm_Bar"
    ::= { digitalMetersBar1317 25165 }

-- MQTT: OPEN-AIR/Zoo/Metering/Bar_Meter/REF/Zoo_Metering_Bar_Meter_REF/blocks/Digital_Meters_Bar/Digital_True_Peak_Bar
digitalTruePeakBarfc56 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Metering/Bar_Meter/REF/Zoo_Metering_Bar_Meter_REF/blocks/Digital_Meters_Bar/Digital_True_Peak_Bar"
    ::= { digitalMetersBar1317 56822 }

-- MQTT: OPEN-AIR/Zoo/Metering/Bar_Meter/REF/Zoo_Metering_Bar_Meter_REF/blocks/Digital_Meters_Bar/LUFS_Momentary_Bar
lUFSMomentaryBar8a69 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Zoo/Metering/Bar_Meter/REF/Zoo_Metering_Bar_Meter_REF/blocks/Digital_Meters_Bar/LUFS_Momentary_Bar"
    ::= { digitalMetersBar1317 57158 }

-- MQTT: OPEN-AIR/status
status7b00 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/status"
    ::= { v1 25884 }

oaGuiDefinitionsa30c OBJECT IDENTIFIER ::= { v1 38698 }
spectrum4b8c OBJECT IDENTIFIER ::= { oaGuiDefinitionsa30c 11186 }
instrumente51a OBJECT IDENTIFIER ::= { spectrum4b8c 55763 }
bandwidth81bd OBJECT IDENTIFIER ::= { instrumente51a 38545 }
spectrumInstrumentbandwidth7704 OBJECT IDENTIFIER ::= { bandwidth81bd 17056 }
blocksdde5 OBJECT IDENTIFIER ::= { spectrumInstrumentbandwidth7704 58428 }
sweepTimec329 OBJECT IDENTIFIER ::= { blocksdde5 8642 }
sweeptimesetting9b2e OBJECT IDENTIFIER ::= { sweepTimec329 53837 }
-- MQTT: OPEN-AIR/oaGuiDefinitions/Spectrum/Instrument/bandwidth/Spectrum_Instrument_bandwidth/blocks/Sweep Time/sweep_time_setting/dial_config
dialconfig40ad OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/oaGuiDefinitions/Spectrum/Instrument/bandwidth/Spectrum_Instrument_bandwidth/blocks/Sweep Time/sweep_time_setting/dial_config"
    ::= { sweeptimesetting9b2e 30608 }

resolutionBandwidth11b8 OBJECT IDENTIFIER ::= { blocksdde5 35133 }
rBWbdc3 OBJECT IDENTIFIER ::= { resolutionBandwidth11b8 13761 }
-- MQTT: OPEN-AIR/oaGuiDefinitions/Spectrum/Instrument/bandwidth/Spectrum_Instrument_bandwidth/blocks/Resolution Bandwidth/RBW/dial_config
dialconfig1899 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/oaGuiDefinitions/Spectrum/Instrument/bandwidth/Spectrum_Instrument_bandwidth/blocks/Resolution Bandwidth/RBW/dial_config"
    ::= { rBWbdc3 40509 }

amplitude6019 OBJECT IDENTIFIER ::= { instrumente51a 56303 }
spectrumInstrumentamplitude4603 OBJECT IDENTIFIER ::= { amplitude6019 50913 }
blocks400f OBJECT IDENTIFIER ::= { spectrumInstrumentamplitude4603 36843 }
referenceLeveldaf3 OBJECT IDENTIFIER ::= { blocks400f 6743 }
refleveldBmd376 OBJECT IDENTIFIER ::= { referenceLeveldaf3 40681 }
-- MQTT: OPEN-AIR/oaGuiDefinitions/Spectrum/Instrument/amplitude/Spectrum_Instrument_amplitude/blocks/Reference Level/ref_level_dBm/dial_config
dialconfig2886 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/oaGuiDefinitions/Spectrum/Instrument/amplitude/Spectrum_Instrument_amplitude/blocks/Reference Level/ref_level_dBm/dial_config"
    ::= { refleveldBmd376 5244 }

frequency2dcb OBJECT IDENTIFIER ::= { instrumente51a 64493 }
spectrumInstrumentfrequency65a9 OBJECT IDENTIFIER ::= { frequency2dcb 54025 }
blocksab4b OBJECT IDENTIFIER ::= { spectrumInstrumentfrequency65a9 29524 }
frequencyd520 OBJECT IDENTIFIER ::= { blocksab4b 7323 }
-- MQTT: OPEN-AIR/oaGuiDefinitions/Spectrum/Instrument/frequency/Spectrum_Instrument_frequency/blocks/Frequency/center_freq_MHz
centerfreqMHz248e OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/oaGuiDefinitions/Spectrum/Instrument/frequency/Spectrum_Instrument_frequency/blocks/Frequency/center_freq_MHz"
    ::= { frequencyd520 674 }

-- MQTT: OPEN-AIR/oaGuiDefinitions/Spectrum/Instrument/frequency/Spectrum_Instrument_frequency/blocks/Frequency/span_freq_MHz
spanfreqMHz47b0 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/oaGuiDefinitions/Spectrum/Instrument/frequency/Spectrum_Instrument_frequency/blocks/Frequency/span_freq_MHz"
    ::= { frequencyd520 48682 }

zoo6ba2 OBJECT IDENTIFIER ::= { oaGuiDefinitionsa30c 55842 }
fadersfd7c OBJECT IDENTIFIER ::= { zoo6ba2 56788 }
faderDial34b4 OBJECT IDENTIFIER ::= { fadersfd7c 23306 }
classice1fb OBJECT IDENTIFIER ::= { faderDial34b4 49120 }
zooFadersFaderDialClassicdc04 OBJECT IDENTIFIER ::= { classice1fb 28215 }
blocks1d8e OBJECT IDENTIFIER ::= { zooFadersFaderDialClassicdc04 63431 }
elements5db7 OBJECT IDENTIFIER ::= { blocks1d8e 32017 }
examplefieldsf5c0 OBJECT IDENTIFIER ::= { elements5db7 18078 }
-- MQTT: OPEN-AIR/oaGuiDefinitions/Zoo/Faders/Fader_Dial/Classic/Zoo_Faders_Fader_Dial_Classic/blocks/elements1/examplefields/dial_config
dialconfigbfcb OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/oaGuiDefinitions/Zoo/Faders/Fader_Dial/Classic/Zoo_Faders_Fader_Dial_Classic/blocks/elements1/examplefields/dial_config"
    ::= { examplefieldsf5c0 30126 }

mDPa46f OBJECT IDENTIFIER ::= { fadersfd7c 55150 }
zooFadersMDPf7ed OBJECT IDENTIFIER ::= { mDPa46f 37873 }
blocks49b8 OBJECT IDENTIFIER ::= { zooFadersMDPf7ed 55840 }
mdpdemoe7d0 OBJECT IDENTIFIER ::= { blocks49b8 25395 }
mdp7c57 OBJECT IDENTIFIER ::= { mdpdemoe7d0 60219 }
graphb2d7 OBJECT IDENTIFIER ::= { mdp7c57 17166 }
oaDataRunningFiles8f8d OBJECT IDENTIFIER ::= { graphb2d7 20261 }
-- MQTT: OPEN-AIR/oaGuiDefinitions/Zoo/Faders/MDP/Zoo_Faders_MDP/blocks/mdp_demo/mdp_1/graph/oaDataRunningFiles/grid_ref
gridref1f6d OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/oaGuiDefinitions/Zoo/Faders/MDP/Zoo_Faders_MDP/blocks/mdp_demo/mdp_1/graph/oaDataRunningFiles/grid_ref"
    ::= { oaDataRunningFiles8f8d 31924 }

gCA8c09 OBJECT IDENTIFIER ::= { fadersfd7c 58509 }
point4f22 OBJECT IDENTIFIER ::= { gCA8c09 48504 }
zooFadersGCApoint8ff1 OBJECT IDENTIFIER ::= { point4f22 4146 }
blockse84c OBJECT IDENTIFIER ::= { zooFadersGCApoint8ff1 64339 }
pointOne1f8a OBJECT IDENTIFIER ::= { blockse84c 27245 }
compositedrums82c7 OBJECT IDENTIFIER ::= { pointOne1f8a 49891 }
-- MQTT: OPEN-AIR/oaGuiDefinitions/Zoo/Faders/GCA/5point/Zoo_Faders_GCA_5point1/blocks/5 point One/composite_drums/ch_1
cha87c OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/oaGuiDefinitions/Zoo/Faders/GCA/5point/Zoo_Faders_GCA_5point1/blocks/5 point One/composite_drums/ch_1"
    ::= { compositedrums82c7 11666 }

scan4792 OBJECT IDENTIFIER ::= { oaGuiDefinitionsa30c 56204 }
scana4a8 OBJECT IDENTIFIER ::= { scan4792 62765 }
blocksb2dd OBJECT IDENTIFIER ::= { scana4a8 10275 }
multidatasetgraphc2f8 OBJECT IDENTIFIER ::= { blocksb2dd 6467 }
oaDataRunningFiles4442 OBJECT IDENTIFIER ::= { multidatasetgraphc2f8 26867 }
-- MQTT: OPEN-AIR/oaGuiDefinitions/scan/scan/blocks/multi_dataset_graph/oaDataRunningFiles/ref_linear
reflinear6a0c OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/oaGuiDefinitions/scan/scan/blocks/multi_dataset_graph/oaDataRunningFiles/ref_linear"
    ::= { oaDataRunningFiles4442 53438 }

dMM53cf OBJECT IDENTIFIER ::= { v1 45793 }
yAK32aa OBJECT IDENTIFIER ::= { dMM53cf 5745 }
a2a39 OBJECT IDENTIFIER ::= { yAK32aa 44112 }
connection9560 OBJECT IDENTIFIER ::= { a2a39 61057 }
tablef5c5 OBJECT IDENTIFIER ::= { connection9560 24000 }
-- MQTT: OPEN-AIR/DMM/YAK/34401A/Connection/Table/description
descriptionb66a OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/DMM/YAK/34401A/Connection/Table/description"
    ::= { tablef5c5 30767 }

-- MQTT: OPEN-AIR/DMM/YAK/34401A/Connection/Table/type
type6f4b OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/DMM/YAK/34401A/Connection/Table/type"
    ::= { tablef5c5 47370 }

scanc4b3 OBJECT IDENTIFIER ::= { v1 45998 }
scanc81a OBJECT IDENTIFIER ::= { scanc4b3 45562 }
blocks5387 OBJECT IDENTIFIER ::= { scanc81a 20061 }
multidatasetgraph2af6 OBJECT IDENTIFIER ::= { blocks5387 9825 }
oaDataRunningFilesc463 OBJECT IDENTIFIER ::= { multidatasetgraph2af6 24572 }
-- MQTT: OPEN-AIR/scan/scan/blocks/multi_dataset_graph/oaDataRunningFiles/ref_linear
reflinearb56a OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/scan/scan/blocks/multi_dataset_graph/oaDataRunningFiles/ref_linear"
    ::= { oaDataRunningFilesc463 44547 }

console3603 OBJECT IDENTIFIER ::= { v1 53174 }
nodeb584 OBJECT IDENTIFIER ::= { console3603 17030 }
fieldsac22 OBJECT IDENTIFIER ::= { nodeb584 2165 }
ch4b85 OBJECT IDENTIFIER ::= { fieldsac22 54367 }
soloCHOnd239 OBJECT IDENTIFIER ::= { ch4b85 37992 }
-- MQTT: OPEN-AIR/Console/9/fields/ch9/Solo_CH_On/ch_on
chon32c9 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Console/9/fields/ch9/Solo_CH_On/ch_on"
    ::= { soloCHOnd239 2543 }

-- MQTT: OPEN-AIR/Console/9/fields/ch9/Solo_CH_On/solo
solobf32 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Console/9/fields/ch9/Solo_CH_On/solo"
    ::= { soloCHOnd239 22606 }

-- MQTT: OPEN-AIR/Console/9/fields/ch9/fader
fader1c6a OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Console/9/fields/ch9/fader"
    ::= { ch4b85 44886 }

nodebb5f OBJECT IDENTIFIER ::= { console3603 51892 }
fields7fc7 OBJECT IDENTIFIER ::= { nodebb5f 5056 }
ch4352 OBJECT IDENTIFIER ::= { fields7fc7 10899 }
-- MQTT: OPEN-AIR/Console/1/fields/ch1/fader
fader38d4 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Console/1/fields/ch1/fader"
    ::= { ch4352 20285 }

-- MQTT: OPEN-AIR/Console/1/fields/ch1/needle
needlec366 OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION "Source: OPEN-AIR/Console/1/fields/ch1/needle"
    ::= { ch4352 62500 }

END