[package]
name = "oaRustCore"
version = "0.1.0"
edition = "2021"

[lib]
name = "oaRustCore"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21.2", features = ["extension-module"] }
# Add any other dependencies that were common across modules
numpy = "0.21.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
