var namespaceio_1_1error =
[
    [ "base", "d6/d09/structio_1_1error_1_1base.html", "d6/d09/structio_1_1error_1_1base" ],
    [ "can_not_open_file", "d4/dbd/structio_1_1error_1_1can__not__open__file.html", "d4/dbd/structio_1_1error_1_1can__not__open__file" ],
    [ "duplicated_column_in_header", "d0/d03/structio_1_1error_1_1duplicated__column__in__header.html", "d0/d03/structio_1_1error_1_1duplicated__column__in__header" ],
    [ "escaped_string_not_closed", "d1/de8/structio_1_1error_1_1escaped__string__not__closed.html", "d1/de8/structio_1_1error_1_1escaped__string__not__closed" ],
    [ "extra_column_in_header", "d6/dc8/structio_1_1error_1_1extra__column__in__header.html", "d6/dc8/structio_1_1error_1_1extra__column__in__header" ],
    [ "header_missing", "dd/dd7/structio_1_1error_1_1header__missing.html", "dd/dd7/structio_1_1error_1_1header__missing" ],
    [ "integer_must_be_positive", "da/d64/structio_1_1error_1_1integer__must__be__positive.html", "da/d64/structio_1_1error_1_1integer__must__be__positive" ],
    [ "integer_overflow", "d4/dec/structio_1_1error_1_1integer__overflow.html", "d4/dec/structio_1_1error_1_1integer__overflow" ],
    [ "integer_underflow", "d8/d9f/structio_1_1error_1_1integer__underflow.html", "d8/d9f/structio_1_1error_1_1integer__underflow" ],
    [ "invalid_single_character", "dd/d70/structio_1_1error_1_1invalid__single__character.html", "dd/d70/structio_1_1error_1_1invalid__single__character" ],
    [ "line_length_limit_exceeded", "db/d37/structio_1_1error_1_1line__length__limit__exceeded.html", "db/d37/structio_1_1error_1_1line__length__limit__exceeded" ],
    [ "missing_column_in_header", "d1/d8a/structio_1_1error_1_1missing__column__in__header.html", "d1/d8a/structio_1_1error_1_1missing__column__in__header" ],
    [ "no_digit", "da/d0e/structio_1_1error_1_1no__digit.html", "da/d0e/structio_1_1error_1_1no__digit" ],
    [ "too_few_columns", "d4/ddb/structio_1_1error_1_1too__few__columns.html", "d4/ddb/structio_1_1error_1_1too__few__columns" ],
    [ "too_many_columns", "d1/d2d/structio_1_1error_1_1too__many__columns.html", "d1/d2d/structio_1_1error_1_1too__many__columns" ],
    [ "with_column_content", "db/dbd/structio_1_1error_1_1with__column__content.html", "db/dbd/structio_1_1error_1_1with__column__content" ],
    [ "with_column_name", "d6/dbd/structio_1_1error_1_1with__column__name.html", "d6/dbd/structio_1_1error_1_1with__column__name" ],
    [ "with_errno", "d2/dc1/structio_1_1error_1_1with__errno.html", "d2/dc1/structio_1_1error_1_1with__errno" ],
    [ "with_file_line", "d2/d34/structio_1_1error_1_1with__file__line.html", "d2/d34/structio_1_1error_1_1with__file__line" ],
    [ "with_file_name", "d0/d77/structio_1_1error_1_1with__file__name.html", "d0/d77/structio_1_1error_1_1with__file__name" ],
    [ "max_column_content_length", "d7/dda/namespaceio_1_1error.html#a5a641f4f0837f4c94416e05461a62749", null ],
    [ "max_column_name_length", "d7/dda/namespaceio_1_1error.html#ae17181bae477fe72ddad096b6b1d6963", null ],
    [ "max_file_name_length", "d7/dda/namespaceio_1_1error.html#ac757e93a049ae7a5f23e522933de68e4", null ]
];