# Core/factory_mapping.py
# Author: Anthony Peter Kuzub
# Version: 1.0.0
#
# Description: Brief summary of purpose

def get_core_factory_mapping(self):
    """Returns the core dictionary mapping JSON keys to creator methods."""
    return {
        # Standard Widgets
        "_sliderValue": self._lazy_wrap("oaGuiElements.Core.utils.slider_value.Core.slider_value", "BuilderSliderValueCreator", "make_slider_value"),
        "_Horizontal_with_dial_Value": self._lazy_wrap("oaGuiElements.Core.utils.composite_horizontal_dial_value.Core.composite_horizontal_dial_value", "BuilderCompositeHorizontalDialValueCreator", "make_composite_horizontal_dial_value"),
        "HorizontalWithValue": self._lazy_wrap("oaGuiElements.Core.utils.composite_horizontal_dial_value.Core.composite_horizontal_dial_value", "BuilderCompositeHorizontalDialValueCreator", "make_composite_horizontal_dial_value"),
        "_GuiButtonToggle": self._lazy_wrap("oaGuiElements.Core.buttons.button_toggle.Core.button_toggle", "BuilderButtonToggleCreator", "make_button_toggle"),
        "_SmartToggle": self._lazy_wrap("oaGuiElements.Core.buttons.button_toggle.Core.button_toggle", "BuilderButtonToggleCreator", "make_button_toggle"),
        "_GuiButtonToggler": self._lazy_wrap("oaGuiElements.Core.buttons.button_toggler.Core.button_toggler", "BuilderButtonTogglerCreator", "make_button_toggler"),
        "_SmartToggler": self._lazy_wrap("oaGuiElements.Core.buttons.button_toggler.Core.button_toggler", "BuilderButtonTogglerCreator", "make_button_toggler"),
        "_GuiDropDownOption": self._lazy_wrap("oaGuiElements.Core.text.text_gui_dropdown_option.Core.text_gui_dropdown_option", "BuilderTextGuiDropdownOptionCreator", "make_text_gui_dropdown_option"),
        "_Value": self._lazy_wrap("oaGuiElements.Core.text.text_value_box.Core.text_value_box", "BuilderTextValueBoxCreator", "make_text_value_box"),
        "_SmartValue": self._lazy_wrap("oaGuiElements.Core.text.text_value_box.Core.text_value_box", "BuilderTextValueBoxCreator", "make_text_value_box"),
        "_GuiValue": self._lazy_wrap("oaGuiElements.Core.text.text_value_box.Core.text_value_box", "BuilderTextValueBoxCreator", "make_text_value_box"),
        "_Label": self._lazy_wrap("oaGuiElements.Core.text.text_label_from_config.Core.text_label_from_config", "BuilderTextLabelFromConfigCreator", "make_text_label_from_config"),
        "_SmartLabel": self._lazy_wrap("oaGuiElements.Core.text.text_label_from_config.Core.text_label_from_config", "BuilderTextLabelFromConfigCreator", "make_text_label_from_config"),
        "_GuiLabel": self._lazy_wrap("oaGuiElements.Core.text.text_label_from_config.Core.text_label_from_config", "BuilderTextLabelFromConfigCreator", "make_text_label_from_config"),
        "_GuiActuator": self._lazy_wrap("oaGuiElements.Core.buttons.button_actuator.Core.button_actuator", "BuilderButtonActuatorCreator", "make_button_actuator"),
        "_SmartActuator": self._lazy_wrap("oaGuiElements.Core.buttons.button_actuator.Core.button_actuator", "BuilderButtonActuatorCreator", "make_button_actuator"),
        "_GuiButton": self._lazy_wrap("oaGuiElements.Core.buttons.button_actuator.Core.button_actuator", "BuilderButtonActuatorCreator", "make_button_actuator"),
        "_GuiCheckbox": self._lazy_wrap("oaGuiElements.Core.utils.checkbox.Core.checkbox", "BuilderCheckboxCreator", "make_checkbox"),
        "_SmartCheckbox": self._lazy_wrap("oaGuiElements.Core.utils.checkbox.Core.checkbox", "BuilderCheckboxCreator", "make_checkbox"),
        "_GuiListbox": self._lazy_wrap("oaGuiElements.Core.utils.listbox.Core.listbox", "BuilderListboxCreator", "make_listbox"),
        "_SmartList": self._lazy_wrap("oaGuiElements.Core.utils.listbox.Core.listbox", "BuilderListboxCreator", "make_listbox"),
        "_ProgressBar": self._lazy_wrap("oaGuiElements.Core.images.images_progress_bar.Core.images_progress_bar", "BuilderImagesProgressBarCreator", "make_images_progress_bar"),
        "ProgressBar": self._lazy_wrap("oaGuiElements.Core.images.images_progress_bar.Core.images_progress_bar", "BuilderImagesProgressBarCreator", "make_images_progress_bar"),
        "_SmartProgress": self._lazy_wrap("oaGuiElements.Core.images.images_progress_bar.Core.images_progress_bar", "BuilderImagesProgressBarCreator", "make_images_progress_bar"),
        "OcaTable": self._lazy_wrap("oaGuiElements.Core.text.text_table.Core.text_table", "BuilderTextTableCreator", "make_text_table"),
        "GuiTable": self._lazy_wrap("oaGuiElements.Core.text.text_table.Core.text_table", "BuilderTextTableCreator", "make_text_table"),
        "DynamicGuiTable": self._lazy_wrap("oaGuiElements.Core.text.text_table.Core.text_table", "BuilderTextTableCreator", "make_text_table"),
        "_TextInput": self._lazy_wrap("oaGuiElements.Core.text.text_value_with_units.Core.text_value_with_units", "BuilderTextValueWithUnitsCreator", "make_text_value_with_units"),
        "_SmartInput": self._lazy_wrap("oaGuiElements.Core.text.text_value_with_units.Core.text_value_with_units", "BuilderTextValueWithUnitsCreator", "make_text_value_with_units"),
        "_WebLink": self._lazy_wrap("oaGuiElements.Core.text.text_web_link.Core.text_web_link", "BuilderTextWebLinkCreator", "make_text_web_link"),
        "_SmartLink": self._lazy_wrap("oaGuiElements.Core.text.text_web_link.Core.text_web_link", "BuilderTextWebLinkCreator", "make_text_web_link"),
        "_ImageDisplay": self._lazy_wrap("oaGuiElements.Core.images.images_image_display.Core.images_image_display", "BuilderImagesImageDisplayCreator", "make_images_image_display"),
        "_SmartImage": self._lazy_wrap("oaGuiElements.Core.images.images_image_display.Core.images_image_display", "BuilderImagesImageDisplayCreator", "make_images_image_display"),
        "_GuiImage": self._lazy_wrap("oaGuiElements.Core.images.images_image_display.Core.images_image_display", "BuilderImagesImageDisplayCreator", "make_images_image_display"),
        "AnimationDisplay": self._lazy_wrap("oaGuiElements.Core.images.images_animation_display.Core.images_animation_display", "BuilderImagesAnimationDisplayCreator", "make_images_animation_display"),
        "_AnimationDisplay": self._lazy_wrap("oaGuiElements.Core.images.images_animation_display.Core.images_animation_display", "BuilderImagesAnimationDisplayCreator", "make_images_animation_display"),
        "_GuiAnimation": self._lazy_wrap("oaGuiElements.Core.images.images_animation_display.Core.images_animation_display", "BuilderImagesAnimationDisplayCreator", "make_images_animation_display"),
        "_SmartAnimation": self._lazy_wrap("oaGuiElements.Core.images.images_animation_display.Core.images_animation_display", "BuilderImagesAnimationDisplayCreator", "make_images_animation_display"),
        "_JsonTree": self._lazy_wrap("oaGuiElements.Core.utils.json_tree.Core.json_tree", "BuilderDataJsonTreeCreator", "make_data_json_tree"),
        "JsonTree": self._lazy_wrap("oaGuiElements.Core.utils.json_tree.Core.json_tree", "BuilderDataJsonTreeCreator", "make_data_json_tree"),
        "_BarGraph": self._lazy_wrap("oaGuiElements.Core.metering.meter_bar.Core.meter_bar", "BuilderMeterBarCreator", "make_meter_bar"),
        "_SmartMeter": self._lazy_wrap("oaGuiElements.Core.metering.meter_bar.Core.meter_bar", "BuilderMeterBarCreator", "make_meter_bar"),
        "_MeterBar": self._lazy_wrap("oaGuiElements.Core.metering.meter_bar.Core.meter_bar", "BuilderMeterBarCreator", "make_meter_bar"),
        "MeterBar": self._lazy_wrap("oaGuiElements.Core.metering.meter_bar.Core.meter_bar", "BuilderMeterBarCreator", "make_meter_bar"),
        "_Fader": self._lazy_wrap("oaGuiElements.Core.faders.fader.Core.fader", "BuilderFaderCreator", "make_fader"),
        "_GuiVerticalFader": self._lazy_wrap("oaGuiElements.Core.faders.fader.Core.fader", "BuilderFaderCreator", "make_fader"),
        "_Knob": self._lazy_wrap("oaGuiElements.Core.utils.knob.Core.knob", "BuilderKnobCreator", "make_knob"),
        "_SmartKnob": self._lazy_wrap("oaGuiElements.Core.utils.knob.Core.knob", "BuilderKnobCreator", "make_knob"),
        "_GuiHorizontalKnob": self._lazy_wrap("oaGuiElements.Core.utils.knob.Core.knob", "BuilderKnobCreator", "make_knob"),
        "SelectorSwitch": self._lazy_wrap("oaGuiElements.Core.utils.knob_rotary_selector.Core.knob_rotary_selector", "BuilderKnobRotarySelectorCreator", "make_knob_rotary_selector"),
        "_SelectorSwitch": self._lazy_wrap("oaGuiElements.Core.utils.knob_rotary_selector.Core.knob_rotary_selector", "BuilderKnobRotarySelectorCreator", "make_knob_rotary_selector"),
        "_IncDecButtons": self._lazy_wrap("oaGuiElements.Core.input.input_inc_dec_buttons.Core.input_inc_dec_buttons", "BuilderInputIncDecButtonsCreator", "make_input_inc_dec_buttons"),
        "_SmartIncDec": self._lazy_wrap("oaGuiElements.Core.input.input_inc_dec_buttons.Core.input_inc_dec_buttons", "BuilderInputIncDecButtonsCreator", "make_input_inc_dec_buttons"),
        "_DirectionalButtons": self._lazy_wrap("oaGuiElements.Core.input.input_directional_buttons.Core.input_directional_buttons", "BuilderInputDirectionalButtonsCreator", "make_input_directional_buttons"),
        "_SmartNav": self._lazy_wrap("oaGuiElements.Core.input.input_directional_buttons.Core.input_directional_buttons", "BuilderInputDirectionalButtonsCreator", "make_input_directional_buttons"),
        "_CustomFader": self._lazy_wrap("oaGuiElements.Core.faders.fader.Core.fader", "BuilderFaderCreator", "make_fader"),
        "_SmartFader": self._lazy_wrap("oaGuiElements.Core.faders.fader.Core.fader", "BuilderFaderCreator", "make_fader"),
        "_CustomHorizontalFader": self._lazy_wrap("oaGuiElements.Core.faders.fader_horizontal.Core.fader_horizontal", "BuilderFaderHorizontalCreator", "make_fader_horizontal"),
        "_CustomDualHorizontalFader": self._lazy_wrap("oaGuiElements.Core.faders.fader_dual.Core.fader_dual", "BuilderFaderDualCreator", "make_fader_dual"),
        "_CustomDualVerticalFader": self._lazy_wrap("oaGuiElements.Core.faders.fader_dual.Core.fader_dual", "BuilderFaderDualCreator", "make_fader_dual"),
        "_CustomLTP": self._lazy_wrap("oaGuiElements.Core.faders.fader_linear_travelling_potentiometer.Core.fader_linear_travelling_potentiometer", "BuilderFaderLinearTravellingPotentiometerCreator", "make_fader_linear_travelling_potentiometer"),
        "_NeedleVUMeter": self._lazy_wrap("oaGuiElements.Core.metering.meter_needle.Core.meter_needle", "BuilderMeterNeedleCreator", "make_meter_needle"),
        "_GuiAnalogGauge": self._lazy_wrap("oaGuiElements.Core.metering.meter_needle.Core.meter_needle", "BuilderMeterNeedleCreator", "make_meter_needle"),
        "_TrapezoidButton": self._lazy_wrap("oaGuiElements.Core.buttons.button_trapezoid.Core.button_trapezoid", "BuilderButtonTrapezoidCreator", "make_button_trapezoid"),
        "_TrapezoidButtonToggler": self._lazy_wrap("oaGuiElements.Core.buttons.button_trapezoid_toggler.Core.button_trapezoid_toggler", "BuilderButtonTrapezoidTogglerCreator", "make_button_trapezoid_toggler"),
        "_HeaderStatusLight": self._lazy_wrap("oaGuiElements.Core.utils.status_light.Core.status_light", "BuilderStatusLightCreator", "make_status_light"),
        "_SmartLight": self._lazy_wrap("oaGuiElements.Core.utils.status_light.Core.status_light", "BuilderStatusLightCreator", "make_status_light"),
        "_WinkButton": self._lazy_wrap("oaGuiElements.Core.buttons.button_wink.Core.button_wink", "BuilderButtonWinkCreator", "make_button_wink"),
        "_WinkButtonToggler": self._lazy_wrap("oaGuiElements.Core.buttons.button_wink_toggler.Core.button_wink_toggler", "BuilderButtonWinkTogglerCreator", "make_button_wink_toggler"),
        "wink_toggler": self._lazy_wrap("oaGuiElements.Core.buttons.button_wink_toggler.Core.button_wink_toggler", "BuilderButtonWinkTogglerCreator", "make_button_wink_toggler"),
        "_VUMeterKnob": self._lazy_wrap("oaGuiElements.Core.metering.meter_knob_with_vu_meter.Core.meter_knob_with_vu_meter", "BuilderMeterKnobWithVuMeterCreator", "make_meter_knob_with_vu_meter"),
        "_BarGraphKnob": self._lazy_wrap("oaGuiElements.Core.metering.meter_knob_with_vu_meter.Core.meter_knob_with_vu_meter", "BuilderMeterKnobWithVuMeterCreator", "make_meter_knob_with_vu_meter"),
        "_Radar": self._lazy_wrap("oaGuiElements.Core.graphing.radar.Core.radar", "BuilderDataRadarCreator", "make_data_radar"),
        "plot_widget": self._lazy_wrap("oaGuiElements.Core.graphing.Methods.plot_widget_adapter", "BuilderGraphingCreator", "make"),
        "bar_graph": self._lazy_wrap("oaGuiElements.Core.graphing.Methods.plot_widget_adapter", "BuilderGraphingCreator", "make"),
        "_GuiGraph": self._lazy_wrap("oaGuiElements.Core.graphing.Methods.plot_widget_adapter", "BuilderGraphingCreator", "make"),
        "DynamicGraph": self._lazy_wrap("oaGuiElements.Core.graphing.Methods.plot_widget_adapter", "BuilderGraphingCreator", "make"),
        "DynamicBarGraph": self._lazy_wrap("oaGuiElements.Core.graphing.Methods.plot_widget_adapter", "BuilderGraphingCreator", "make"),
        "_CompositeFader": self._lazy_wrap("oaGuiElements.Core.faders.fader_ganged_controlled_array.Core.fader_ganged_controlled_array", "BuilderFaderGangedControlledArrayCreator", "make_fader_ganged_controlled_array"),
        "_FaderWithBarGraph": self._lazy_wrap("oaGuiElements.Core.faders.fader_bar_graph.Core.fader_bar_graph", "BuilderFaderBarGraphCreator", "make_fader_bar_graph"),
        "_MDP": self._lazy_wrap("oaGuiElements.Core.utils.composite_mdp.Core.composite_mdp", "BuilderCompositeMdpCreator", "make_composite_mdp"),
        "_CMDP": self._lazy_wrap("oaGuiElements.Core.utils.circular_motion_displacement_potentiometer.Core.circular_motion_displacement_potentiometer", "BuilderCircularMotionDisplacementPotentiometerCreator", "make_circular_motion_displacement_potentiometer"),
        "HeaderStatusLight": self._lazy_wrap("oaGuiElements.Core.utils.status_light.Core.status_light", "BuilderStatusLightCreator", "make_status_light"),
        # Complex Adapters (Some might be missing - need to verify paths)
        "OcaArray": self._lazy_wrap("oaGui.Core.array.array", "BuilderArrayCreator", "make"),
        "OcaCollapsibleBlock": self._lazy_wrap("oaGui.Core.array.array", "BuilderArrayCreator", "make"),
        "OcaBlock": self._lazy_wrap("oaGui.Core.array.array", "BuilderArrayCreator", "make"),
        "OcaBin": self._lazy_wrap("oaGui.Core.array.array", "BuilderArrayCreator", "make"),
        "Block": self._lazy_wrap("oaGui.Core.array.array", "BuilderArrayCreator", "make"),
        "Array": self._lazy_wrap("oaGui.Core.array.array", "BuilderArrayCreator", "make"),
        "Bin": self._lazy_wrap("oaGui.Core.array.array", "BuilderArrayCreator", "make"),
        "OcaFold": self._lazy_wrap("oaGuiElements.Core.utils.break_line.Core.hidden_BreakLine", "BuilderBreakLineCreator", "make"),
    }
